<a href="https://colab.research.google.com/github/Miguithub/NPP_Cripto_5min/blob/main/ID(Ingenieria%20de%20Datos)11/2024-01/2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Mounted at /content/drive

# Merge

In [ ]:
from google.colab import drive
import pandas as pd

drive.mount("/content/drive")

ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

nombres = [
    "01-2026.parquet", "12-2025.parquet", "11-2025.parquet",
    "10-2025.parquet", "09-2025.parquet", "08-2025.parquet",
    "07-2025.parquet", "06-2025.parquet", "05-2025.parquet",
    "04-2025.parquet", "03-2025.parquet", "02-2025.parquet",
    "01-2025.parquet", "12-2024.parquet", "11-2024.parquet"
]

dfs = [pd.read_parquet(ruta + nombre) for nombre in nombres]

df = pd.concat(dfs, ignore_index=True)

df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,bar_start,bar_end,0G_y,1000CAT_y,1000CHEEMS_y,1000SATS_y,1INCH_y,1MBABYDOGE_y,2Z_y,A_y,...,UNFI_turnover_usdt_proxy,UNFI_range_rel_proxy,UNFI_illiquidity_proxy,UNFI_activity_trades_proxy,UNFI_taker_buy_usdt_proxy,UNFI_taker_sell_usdt_proxy,UNFI_active_users,UNFI_spot_account_liquidity,UNFI_exchange_reserves,UNFI_orderbook_depth
0,2026-01-01 00:00:00+00:00,2026-01-01 00:05:00+00:00,13257.45140,38467.684080,7588.099646,2476.548982,1009.95258,1669.213238,11639.17548,6763.32426,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-01-01 00:05:00+00:00,2026-01-01 00:10:00+00:00,10717.11312,1197.164863,3593.027633,2709.237500,334.76625,4225.288885,5448.53120,10694.40188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-01-01 00:10:00+00:00,2026-01-01 00:15:00+00:00,4722.59128,16652.066400,1824.357712,1735.660531,8612.38335,839.040509,2508.82896,1650.52390,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-01-01 00:15:00+00:00,2026-01-01 00:20:00+00:00,3168.83480,2922.529140,5420.152314,1438.856048,1072.13054,3362.111833,53096.61604,9318.84291,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-01-01 00:20:00+00:00,2026-01-01 00:25:00+00:00,8026.96068,754.859250,1793.224546,677.362716,1376.93140,16317.297922,13827.46360,656.75720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 9183 entries, bar_start to UNFI_orderbook_depth
dtypes: bool(329), boolean(1020), datetime64[ns, UTC](2), float64(7141), object(181), string(510)
memory usage: 8.0+ GB

In [ ]:
df.columns.tolist()

['bar_start',
 'bar_end',
 '0G_y',
 '1000CAT_y',
 '1000CHEEMS_y',
 '1000SATS_y',
 '1INCH_y',
 '1MBABYDOGE_y',
 '2Z_y',
 'A_y',
 'A2Z_y',
 'AAVE_y',
 'ACA_y',
 'ACE_y',
 'ACH_y',
 'ACM_y',
 'ACT_y',
 'ACX_y',
 'ADA_y',
 'ADX_y',
 'AEUR_y',
 'AEVO_y',
 'AGLD_y',
 'AI_y',
 'AIXBT_y',
 'ALCX_y',
 'ALGO_y',
 'ALICE_y',
 'ALLO_y',
 'ALPINE_y',
 'ALT_y',
 'AMP_y',
 'ANIME_y',
 'ANKR_y',
 'APE_y',
 'API3_y',
 'APT_y',
 'AR_y',
 'ARB_y',
 'ARDR_y',
 'ARK_y',
 'ARKM_y',
 'ARPA_y',
 'ASR_y',
 'ASTER_y',
 'ASTR_y',
 'AT_y',
 'ATA_y',
 'ATM_y',
 'ATOM_y',
 'AUCTION_y',
 'AUDIO_y',
 'AVA_y',
 'AVAX_y',
 'AVNT_y',
 'AWE_y',
 'AXL_y',
 'AXS_y',
 'BABY_y',
 'BANANA_y',
 'BANANAS31_y',
 'BAND_y',
 'BANK_y',
 'BAR_y',
 'BARD_y',
 'BAT_y',
 'BB_y',
 'BCH_y',
 'BEAMX_y',
 'BEL_y',
 'BERA_y',
 'BFUSD_y',
 'BICO_y',
 'BIFI_y',
 'BIGTIME_y',
 'BIO_y',
 'BLUR_y',
 'BMT_y',
 'BNB_y',
 'BNSOL_y',
 'BNT_y',
 'BOME_y',
 'BONK_y',
 'BREV_y',
 'BROCCOLI714_y',
 'BTC_y',
 'BTTC_y',
 'C_y',
 'C98_y',
 'CAKE_y',
 'CATI_y',
 'CELO_y',
 'CELR_y',
 'CETUS_y',
 'CFX_y',
 'CGPT_y',
 'CHESS_y',
 'CHR_y',
 'CHZ_y',
 'CITY_y',
 'CKB_y',
 'COMP_y',
 'COOKIE_y',
 'COS_y',
 'COTI_y',
 'COW_y',
 'CRV_y',
 'CTK_y',
 'CTSI_y',
 'CVC_y',
 'CVX_y',
 'CYBER_y',
 'D_y',
 'DAI_y',
 'DASH_y',
 'DATA_y',
 'DCR_y',
 'DEGO_y',
 'DENT_y',
 'DEXE_y',
 'DF_y',
 'DGB_y',
 'DIA_y',
 'DODO_y',
 'DOGE_y',
 'DOGS_y',
 'DOLO_y',
 'DOT_y',
 'DUSK_y',
 'DYDX_y',
 'DYM_y',
 'EDEN_y',
 'EDU_y',
 'EGLD_y',
 'EIGEN_y',
 'ENA_y',
 'ENJ_y',
 'ENS_y',
 'ENSO_y',
 'EPIC_y',
 'ERA_y',
 'ETC_y',
 'ETH_y',
 'ETHFI_y',
 'EUL_y',
 'EUR_y',
 'EURI_y',
 'F_y',
 'FARM_y',
 'FDUSD_y',
 'FET_y',
 'FF_y',
 'FIDA_y',
 'FIL_y',
 'FIO_y',
 'FLOKI_y',
 'FLOW_y',
 'FLUX_y',
 'FOGO_y',
 'FORM_y',
 'FORTH_y',
 'FRAX_y',
 'FTT_y',
 'FUN_y',
 'FXS_y',
 'G_y',
 'GALA_y',
 'GAS_y',
 'GHST_y',
 'GIGGLE_y',
 'GLM_y',
 'GLMR_y',
 'GMT_y',
 'GMX_y',
 'GNO_y',
 'GNS_y',
 'GPS_y',
 'GRT_y',
 'GTC_y',
 'GUN_y',
 'HAEDAL_y',
 'HBAR_y',
 'HEI_y',
 'HEMI_y',
 'HFT_y',
 'HIGH_y',
 'HIVE_y',
 'HMSTR_y',
 'HOLO_y',
 'HOME_y',
 'HOOK_y',
 'HOT_y',
 'HUMA_y',
 'HYPER_y',
 'ICP_y',
 'ICX_y',
 'ID_y',
 'IDEX_y',
 'ILV_y',
 'IMX_y',
 'INIT_y',
 'INJ_y',
 'IO_y',
 'IOST_y',
 'IOTA_y',
 'IOTX_y',
 'IQ_y',
 'JASMY_y',
 'JOE_y',
 'JST_y',
 'JTO_y',
 'JUP_y',
 'JUV_y',
 'KAIA_y',
 'KAITO_y',
 'KAVA_y',
 'KERNEL_y',
 'KGST_y',
 'KITE_y',
 'KMNO_y',
 'KNC_y',
 'KSM_y',
 'LA_y',
 'LAYER_y',
 'LAZIO_y',
 'LDO_y',
 'LINEA_y',
 'LINK_y',
 'LISTA_y',
 'LPT_y',
 'LQTY_y',
 'LRC_y',
 'LSK_y',
 'LTC_y',
 'LUMIA_y',
 'LUNA_y',
 'LUNC_y',
 'MAGIC_y',
 'MANA_y',
 'MANTA_y',
 'MASK_y',
 'MAV_y',
 'MBL_y',
 'MBOX_y',
 'MDT_y',
 'ME_y',
 'MEME_y',
 'MET_y',
 'METIS_y',
 'MINA_y',
 'MIRA_y',
 'MITO_y',
 'MLN_y',
 'MMT_y',
 'MORPHO_y',
 'MOVE_y',
 'MOVR_y',
 'MTL_y',
 'MUBARAK_y',
 'NEAR_y',
 'NEIRO_y',
 'NEO_y',
 'NEWT_y',
 'NEXO_y',
 'NFP_y',
 'NIL_y',
 'NKN_y',
 'NMR_y',
 'NOM_y',
 'NOT_y',
 'NTRN_y',
 'NXPC_y',
 'OG_y',
 'OGN_y',
 'OM_y',
 'ONDO_y',
 'ONE_y',
 'ONG_y',
 'ONT_y',
 'OP_y',
 'OPEN_y',
 'ORCA_y',
 'ORDI_y',
 'OSMO_y',
 'OXT_y',
 'PARTI_y',
 'PAXG_y',
 'PENDLE_y',
 'PENGU_y',
 'PEOPLE_y',
 'PEPE_y',
 'PHA_y',
 'PHB_y',
 'PIVX_y',
 'PIXEL_y',
 'PLUME_y',
 'PNUT_y',
 'POL_y',
 'POLYX_y',
 'POND_y',
 'PORTAL_y',
 'PORTO_y',
 'POWR_y',
 'PROM_y',
 'PROVE_y',
 'PSG_y',
 'PUMP_y',
 'PUNDIX_y',
 'PYR_y',
 'PYTH_y',
 'QI_y',
 'QKC_y',
 'QNT_y',
 'QTUM_y',
 'QUICK_y',
 'RAD_y',
 'RARE_y',
 'RAY_y',
 'RDNT_y',
 'RED_y',
 'RENDER_y',
 'REQ_y',
 'RESOLV_y',
 'REZ_y',
 'RIF_y',
 'RLC_y',
 'RLUSD_y',
 'RONIN_y',
 'ROSE_y',
 'RPL_y',
 'RSR_y',
 'RUNE_y',
 'RVN_y',
 'S_y',
 'SAGA_y',
 'SAHARA_y',
 'SAND_y',
 'SANTOS_y',
 'SAPIEN_y',
 'SC_y',
 'SCR_y',
 'SCRT_y',
 'SEI_y',
 'SENT_y',
 'SFP_y',
 'SHELL_y',
 'SHIB_y',
 'SIGN_y',
 'SKL_y',
 'SKY_y',
 'SLP_y',
 'SNX_y',
 'SOL_y',
 'SOLV_y',
 'SOMI_y',
 'SOPH_y',
 'SPELL_y',
 'SPK_y',
 'SSV_y',
 'STEEM_y',
 'STG_y',
 'STO_y',
 'STORJ_y',
 'STRAX_y',
 'STRK_y',
 'STX_y',
 'SUI_y',
 'SUN_y',
 'SUPER_y',
 'SUSHI_y',
 'SXP_y',
 'SXT_y',
 'SYN_y',
 'SYRUP_y',
 'SYS_y',
 'T_y',
 'TAO_y',
 'TFUEL_y',
 'THE_y',
 'THETA_y',
 'TIA_y',
 'TKO_y',
 'TLM_y',
 'TNSR_y',
 'TON_y',
 'TOWNS_y',
 'TRB_y',
 'TREE_y',
 'TRU_y',
 'TRUMP_y',
 'TRX_y',
 'TST_y',
 'TURBO_y',
 'TURTLE_y',
 'TUSD_y',
 'TUT_y',
 'TWT_y',
 'U_y',
 'UMA_y',
 'UNI_y',
 'USD1_y',
 'USDC_y',
 'USDE_y',
 'USDP_y',
 'USDT_y',
 'USTC_y',
 'USUAL_y',
 'UTK_y',
 'VANA_y',
 'VANRY_y',
 'VELODROME_y',
 'VET_y',
 'VIC_y',
 'VIRTUAL_y',
 'VTHO_y',
 'W_y',
 'WAL_y',
 'WAN_y',
 'WAXP_y',
 'WBETH_y',
 'WBTC_y',
 'WCT_y',
 'WIF_y',
 'WIN_y',
 'WLD_y',
 'WLFI_y',
 'WOO_y',
 'XAI_y',
 'XEC_y',
 'XLM_y',
 'XNO_y',
 'XPL_y',
 'XRP_y',
 'XTZ_y',
 'XUSD_y',
 'XVG_y',
 'XVS_y',
 'YB_y',
 'YFI_y',
 'YGG_y',
 'ZBT_y',
 'ZEC_y',
 'ZEN_y',
 'ZIL_y',
 'ZK_y',
 'ZKC_y',
 'ZKP_y',
 'ZRO_y',
 'ZRX_y',
 '币安人生_y',
 'YS',
 '0GUSDT',
 '1000CATUSDT',
 '1000CHEEMSUSDT',
 '1000SATSUSDT',
 '1INCHUSDT',
 '1MBABYDOGEUSDT',
 '2ZUSDT',
 'AUSDT',
 'A2ZUSDT',
 'AAVEUSDT',
 'ACAUSDT',
 'ACEUSDT',
 'ACHUSDT',
 'ACMUSDT',
 'ACTUSDT',
 'ACXUSDT',
 'ADAUSDT',
 'ADXUSDT',
 'AEURUSDT',
 'AEVOUSDT',
 'AGLDUSDT',
 'AIUSDT',
 'AIXBTUSDT',
 'ALCXUSDT',
 'ALGOUSDT',
 'ALICEUSDT',
 'ALLOUSDT',
 'ALPINEUSDT',
 'ALTUSDT',
 'AMPUSDT',
 'ANIMEUSDT',
 'ANKRUSDT',
 'APEUSDT',
 'API3USDT',
 'APTUSDT',
 'ARUSDT',
 'ARBUSDT',
 'ARDRUSDT',
 'ARKUSDT',
 'ARKMUSDT',
 'ARPAUSDT',
 'ASRUSDT',
 'ASTERUSDT',
 'ASTRUSDT',
 'ATUSDT',
 'ATAUSDT',
 'ATMUSDT',
 'ATOMUSDT',
 'AUCTIONUSDT',
 'AUDIOUSDT',
 'AVAUSDT',
 'AVAXUSDT',
 'AVNTUSDT',
 'AWEUSDT',
 'AXLUSDT',
 'AXSUSDT',
 'BABYUSDT',
 'BANANAUSDT',
 'BANANAS31USDT',
 'BANDUSDT',
 'BANKUSDT',
 'BARUSDT',
 'BARDUSDT',
 'BATUSDT',
 'BBUSDT',
 'BCHUSDT',
 'BEAMXUSDT',
 'BELUSDT',
 'BERAUSDT',
 'BFUSDUSDT',
 'BICOUSDT',
 'BIFIUSDT',
 'BIGTIMEUSDT',
 'BIOUSDT',
 'BLURUSDT',
 'BMTUSDT',
 'BNBUSDT',
 'BNSOLUSDT',
 'BNTUSDT',
 'BOMEUSDT',
 'BONKUSDT',
 'BREVUSDT',
 'BROCCOLI714USDT',
 'BTCUSDT',
 'BTTCUSDT',
 'CUSDT',
 'C98USDT',
 'CAKEUSDT',
 'CATIUSDT',
 'CELOUSDT',
 'CELRUSDT',
 'CETUSUSDT',
 'CFXUSDT',
 'CGPTUSDT',
 'CHESSUSDT',
 'CHRUSDT',
 'CHZUSDT',
 'CITYUSDT',
 'CKBUSDT',
 'COMPUSDT',
 'COOKIEUSDT',
 'COSUSDT',
 'COTIUSDT',
 'COWUSDT',
 'CRVUSDT',
 'CTKUSDT',
 'CTSIUSDT',
 'CVCUSDT',
 'CVXUSDT',
 'CYBERUSDT',
 'DUSDT',
 'DAIUSDT',
 'DASHUSDT',
 'DATAUSDT',
 'DCRUSDT',
 'DEGOUSDT',
 'DENTUSDT',
 'DEXEUSDT',
 'DFUSDT',
 'DGBUSDT',
 'DIAUSDT',
 'DODOUSDT',
 'DOGEUSDT',
 'DOGSUSDT',
 'DOLOUSDT',
 'DOTUSDT',
 'DUSKUSDT',
 'DYDXUSDT',
 'DYMUSDT',
 'EDENUSDT',
 'EDUUSDT',
 'EGLDUSDT',
 'EIGENUSDT',
 'ENAUSDT',
 'ENJUSDT',
 'ENSUSDT',
 'ENSOUSDT',
 'EPICUSDT',
 'ERAUSDT',
 'ETCUSDT',
 'ETHUSDT',
 'ETHFIUSDT',
 'EULUSDT',
 'EURUSDT',
 'EURIUSDT',
 'FUSDT',
 'FARMUSDT',
 'FDUSDUSDT',
 'FETUSDT',
 'FFUSDT',
 'FIDAUSDT',
 'FILUSDT',
 'FIOUSDT',
 'FLOKIUSDT',
 'FLOWUSDT',
 'FLUXUSDT',
 'FOGOUSDT',
 'FORMUSDT',
 'FORTHUSDT',
 'FRAXUSDT',
 'FTTUSDT',
 'FUNUSDT',
 'FXSUSDT',
 'GUSDT',
 'GALAUSDT',
 'GASUSDT',
 'GHSTUSDT',
 'GIGGLEUSDT',
 'GLMUSDT',
 'GLMRUSDT',
 'GMTUSDT',
 'GMXUSDT',
 'GNOUSDT',
 'GNSUSDT',
 'GPSUSDT',
 'GRTUSDT',
 'GTCUSDT',
 'GUNUSDT',
 'HAEDALUSDT',
 'HBARUSDT',
 'HEIUSDT',
 'HEMIUSDT',
 'HFTUSDT',
 'HIGHUSDT',
 'HIVEUSDT',
 'HMSTRUSDT',
 'HOLOUSDT',
 'HOMEUSDT',
 'HOOKUSDT',
 'HOTUSDT',
 'HUMAUSDT',
 'HYPERUSDT',
 'ICPUSDT',
 'ICXUSDT',
 'IDUSDT',
 'IDEXUSDT',
 'ILVUSDT',
 'IMXUSDT',
 'INITUSDT',
 'INJUSDT',
 'IOUSDT',
 'IOSTUSDT',
 'IOTAUSDT',
 'IOTXUSDT',
 'IQUSDT',
 'JASMYUSDT',
 'JOEUSDT',
 'JSTUSDT',
 'JTOUSDT',
 'JUPUSDT',
 'JUVUSDT',
 'KAIAUSDT',
 'KAITOUSDT',
 'KAVAUSDT',
 'KERNELUSDT',
 'KGSTUSDT',
 'KITEUSDT',
 'KMNOUSDT',
 'KNCUSDT',
 'KSMUSDT',
 'LAUSDT',
 'LAYERUSDT',
 'LAZIOUSDT',
 'LDOUSDT',
 'LINEAUSDT',
 'LINKUSDT',
 'LISTAUSDT',
 'LPTUSDT',
 'LQTYUSDT',
 'LRCUSDT',
 'LSKUSDT',
 'LTCUSDT',
 'LUMIAUSDT',
 'LUNAUSDT',
 'LUNCUSDT',
 'MAGICUSDT',
 'MANAUSDT',
 'MANTAUSDT',
 'MASKUSDT',
 'MAVUSDT',
 'MBLUSDT',
 'MBOXUSDT',
 'MDTUSDT',
 'MEUSDT',
 'MEMEUSDT',
 'METUSDT',
 'METISUSDT',
 'MINAUSDT',
 'MIRAUSDT',
 'MITOUSDT',
 'MLNUSDT',
 'MMTUSDT',
 'MORPHOUSDT',
 'MOVEUSDT',
 'MOVRUSDT',
 'MTLUSDT',
 'MUBARAKUSDT',
 'NEARUSDT',
 'NEIROUSDT',
 'NEOUSDT',
 'NEWTUSDT',
 'NEXOUSDT',
 'NFPUSDT',
 'NILUSDT',
 'NKNUSDT',
 'NMRUSDT',
 'NOMUSDT',
 'NOTUSDT',
 'NTRNUSDT',
 'NXPCUSDT',
 'OGUSDT',
 'OGNUSDT',
 'OMUSDT',
 'ONDOUSDT',
 'ONEUSDT',
 'ONGUSDT',
 'ONTUSDT',
 'OPUSDT',
 'OPENUSDT',
 'ORCAUSDT',
 'ORDIUSDT',
 'OSMOUSDT',
 'OXTUSDT',
 'PARTIUSDT',
 'PAXGUSDT',
 'PENDLEUSDT',
 'PENGUUSDT',
 'PEOPLEUSDT',
 'PEPEUSDT',
 'PHAUSDT',
 'PHBUSDT',
 'PIVXUSDT',
 'PIXELUSDT',
 'PLUMEUSDT',
 'PNUTUSDT',
 'POLUSDT',
 'POLYXUSDT',
 'PONDUSDT',
 'PORTALUSDT',
 'PORTOUSDT',
 'POWRUSDT',
 'PROMUSDT',
 'PROVEUSDT',
 'PSGUSDT',
 'PUMPUSDT',
 'PUNDIXUSDT',
 'PYRUSDT',
 'PYTHUSDT',
 'QIUSDT',
 'QKCUSDT',
 'QNTUSDT',
 'QTUMUSDT',
 'QUICKUSDT',
 'RADUSDT',
 'RAREUSDT',
 'RAYUSDT',
 'RDNTUSDT',
 'REDUSDT',
 'RENDERUSDT',
 'REQUSDT',
 'RESOLVUSDT',
 'REZUSDT',
 'RIFUSDT',
 'RLCUSDT',
 'RLUSDUSDT',
 'RONINUSDT',
 'ROSEUSDT',
 'RPLUSDT',
 'RSRUSDT',
 'RUNEUSDT',
 'RVNUSDT',
 'SUSDT',
 'SAGAUSDT',
 'SAHARAUSDT',
 'SANDUSDT',
 'SANTOSUSDT',
 'SAPIENUSDT',
 'SCUSDT',
 'SCRUSDT',
 'SCRTUSDT',
 'SEIUSDT',
 'SENTUSDT',
 'SFPUSDT',
 'SHELLUSDT',
 'SHIBUSDT',
 'SIGNUSDT',
 'SKLUSDT',
 'SKYUSDT',
 'SLPUSDT',
 'SNXUSDT',
 'SOLUSDT',
 'SOLVUSDT',
 'SOMIUSDT',
 'SOPHUSDT',
 'SPELLUSDT',
 'SPKUSDT',
 'SSVUSDT',
 'STEEMUSDT',
 'STGUSDT',
 'STOUSDT',
 'STORJUSDT',
 'STRAXUSDT',
 'STRKUSDT',
 'STXUSDT',
 'SUIUSDT',
 'SUNUSDT',
 'SUPERUSDT',
 'SUSHIUSDT',
 'SXPUSDT',
 'SXTUSDT',
 'SYNUSDT',
 'SYRUPUSDT',
 'SYSUSDT',
 'TUSDT',
 'TAOUSDT',
 'TFUELUSDT',
 'THEUSDT',
 'THETAUSDT',
 'TIAUSDT',
 'TKOUSDT',
 'TLMUSDT',
 'TNSRUSDT',
 'TONUSDT',
 'TOWNSUSDT',
 'TRBUSDT',
 'TREEUSDT',
 'TRUUSDT',
 'TRUMPUSDT',
 'TRXUSDT',
 'TSTUSDT',
 'TURBOUSDT',
 'TURTLEUSDT',
 'TUSDUSDT',
 'TUTUSDT',
 'TWTUSDT',
 'UUSDT',
 'UMAUSDT',
 'UNIUSDT',
 'USD1USDT',
 'USDCUSDT',
 'USDEUSDT',
 'USDPUSDT',
 'USDTUSDT',
 'USTCUSDT',
 'USUALUSDT',
 'UTKUSDT',
 'VANAUSDT',
 'VANRYUSDT',
 'VELODROMEUSDT',
 'VETUSDT',
 'VICUSDT',
 'VIRTUALUSDT',
 'VTHOUSDT',
 'WUSDT',
 'WALUSDT',
 'WANUSDT',
 'WAXPUSDT',
 'WBETHUSDT',
 'WBTCUSDT',
 'WCTUSDT',
 'WIFUSDT',
 'WINUSDT',
 'WLDUSDT',
 'WLFIUSDT',
 'WOOUSDT',
 'XAIUSDT',
 'XECUSDT',
 'XLMUSDT',
 'XNOUSDT',
 'XPLUSDT',
 'XRPUSDT',
 'XTZUSDT',
 'XUSDUSDT',
 'XVGUSDT',
 'XVSUSDT',
 'YBUSDT',
 'YFIUSDT',
 'YGGUSDT',
 'ZBTUSDT',
 'ZECUSDT',
 'ZENUSDT',
 'ZILUSDT',
 'ZKUSDT',
 'ZKCUSDT',
 'ZKPUSDT',
 'ZROUSDT',
 'ZRXUSDT',
 '币安人生USDT',
 '0G_v',
 '1000CAT_v',
 '1000CHEEMS_v',
 '1000SATS_v',
 '1INCH_v',
 '1MBABYDOGE_v',
 '2Z_v',
 'A_v',
 'A2Z_v',
 'AAVE_v',
 'ACA_v',
 'ACE_v',
 'ACH_v',
 'ACM_v',
 'ACT_v',
 'ACX_v',
 'ADA_v',
 'ADX_v',
 'AEUR_v',
 'AEVO_v',
 'AGLD_v',
 'AI_v',
 'AIXBT_v',
 'ALCX_v',
 'ALGO_v',
 'ALICE_v',
 'ALLO_v',
 'ALPINE_v',
 'ALT_v',
 'AMP_v',
 'ANIME_v',
 'ANKR_v',
 'APE_v',
 'API3_v',
 'APT_v',
 'AR_v',
 'ARB_v',
 'ARDR_v',
 'ARK_v',
 'ARKM_v',
 'ARPA_v',
 'ASR_v',
 'ASTER_v',
 'ASTR_v',
 'AT_v',
 'ATA_v',
 'ATM_v',
 'ATOM_v',
 'AUCTION_v',
 'AUDIO_v',
 'AVA_v',
 'AVAX_v',
 'AVNT_v',
 'AWE_v',
 'AXL_v',
 'AXS_v',
 'BABY_v',
 'BANANA_v',
 'BANANAS31_v',
 'BAND_v',
 'BANK_v',
 'BAR_v',
 'BARD_v',
 'BAT_v',
 'BB_v',
 'BCH_v',
 'BEAMX_v',
 'BEL_v',
 'BERA_v',
 'BFUSD_v',
 'BICO_v',
 'BIFI_v',
 'BIGTIME_v',
 'BIO_v',
 'BLUR_v',
 'BMT_v',
 'BNB_v',
 'BNSOL_v',
 'BNT_v',
 'BOME_v',
 'BONK_v',
 'BREV_v',
 'BROCCOLI714_v',
 'BTC_v',
 'BTTC_v',
 'C_v',
 'C98_v',
 'CAKE_v',
 'CATI_v',
 'CELO_v',
 'CELR_v',
 'CETUS_v',
 'CFX_v',
 'CGPT_v',
 'CHESS_v',
 'CHR_v',
 'CHZ_v',
 'CITY_v',
 'CKB_v',
 'COMP_v',
 'COOKIE_v',
 ...]

In [ ]:
[column for column in df.columns if "WBTC" in column.upper()]

['WBTC_y',
 'WBTCUSDT',
 'WBTC_v',
 'WBTC_yp',
 'WBTC_source_pair',
 'WBTC_price_is_proxy',
 'WBTC_observed',
 'WBTC_active_trading',
 'WBTC_turnover_usdt_proxy',
 'WBTC_range_rel_proxy',
 'WBTC_illiquidity_proxy',
 'WBTC_activity_trades_proxy',
 'WBTC_taker_buy_usdt_proxy',
 'WBTC_taker_sell_usdt_proxy',
 'WBTC_active_users',
 'WBTC_spot_account_liquidity',
 'WBTC_exchange_reserves',
 'WBTC_orderbook_depth']

## Diccionario de `df`
Ejemplo para BTC; el mismo esquema se aplica a cada activo base observado ese mes.

| Columna | Unidad / significado |
|---|---|
| `timestamp` (índice) | UTC; momento de disponibilidad asumida con margen |
| `bar_start`, `bar_end` | Inicio y final real de la vela |
| `BTC_y` | Cierre en USDT × volumen en BTC; columna original de `dftu` |
| `YS` | Suma observada de las columnas `_y` |
| `BTCUSDT` | USDT por BTC; directo o sintético según bandera |
| `BTC_v` | BTC negociados en el mercado seleccionado |
| `BTC_yp` | Participación entre 0 y 1 sobre `YS` |
| `BTC_source_pair` | Par que aporta precio y volumen; nulo si no hay dato utilizable |
| `BTC_price_is_proxy` | Verdadero si no se usa directamente BTCUSDT |
| `BTC_observed` | Hay vela y precio utilizable en el mercado seleccionado |
| `BTC_active_trading` | Número de operaciones > 0 en ese mercado; nulo sin observación |
| `BTC_turnover_usdt_proxy` | `quote_volume × quote/USDT`; proxy de liquidez por actividad |
| `BTC_range_rel_proxy` | `(high−low)/close`, adimensional; rango, no spread |
| `BTC_illiquidity_proxy` | `abs(close/open−1)/turnover_usdt`; variante intravela, inverso de USDT |
| `BTC_activity_trades_proxy` | Cantidad de operaciones; NO personas ni cuentas únicas |
| `BTC_taker_buy_usdt_proxy` | Flujo de compras agresoras en USDT aproximados |
| `BTC_taker_sell_usdt_proxy` | Flujo de ventas agresoras en USDT aproximados |
| `BTC_active_users` | `NaN`: dato no disponible |
| `BTC_spot_account_liquidity` | `NaN`: saldo agregado de cuentas spot no disponible |
| `BTC_exchange_reserves` | `NaN`: reservas históricas 5m no disponibles |
| `BTC_orderbook_depth` | `NaN`: no se reconstruye profundidad con velas |

Los flujos de takers no son depósitos/retiros ni cambios del saldo custodiado. Los proxies
de actividad y liquidez no permiten inferir los stocks de cuentas del paso 6.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 9183 entries, bar_start to UNFI_orderbook_depth
dtypes: bool(329), boolean(1020), datetime64[ns, UTC](2), float64(7141), object(181), string(510)
memory usage: 8.0+ GB

In [ ]:
df["BTC_orderbook_depth"].isna().sum()

np.int64(131616)

In [ ]:
porcentaje_nan = df.isna().mean()

columnas_100_nan = porcentaje_nan[porcentaje_nan == 1].index.tolist()
columnas_50_nan = porcentaje_nan[porcentaje_nan >= 0.5].index.tolist()

print("Columnas enteramente NaN:", len(columnas_100_nan))
print(columnas_100_nan)

print("\nColumnas con 50% o más de NaN:", len(columnas_50_nan))
print(columnas_50_nan)

Columnas enteramente NaN: 2040

In [ ]:
nan_por_columna = (
    df.isna()
      .sum()
      .rename_axis("columna")
      .reset_index(name="cantidad_nan")
)

nan_por_columna.to_csv("nan_por_columna.csv", index=False)

nan_por_columna.shape

(9183, 2)

In [ ]:
archivo_salida = ruta + "nan por columna merge 11-2024-12-2025.csv"

nan_por_columna.to_csv(archivo_salida, index=False)

print(f"Guardado en: {archivo_salida}")

Guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/nan por columna merge 11-2024-12-2025.csv

In [ ]:
columnas_y = [columna for columna in df.columns if columna.endswith("_y")]

print(f"Total: {len(columnas_y)}")
columnas_y

Total: 510

['0G_y',
 '1000CAT_y',
 '1000CHEEMS_y',
 '1000SATS_y',
 '1INCH_y',
 '1MBABYDOGE_y',
 '2Z_y',
 'A_y',
 'A2Z_y',
 'AAVE_y',
 'ACA_y',
 'ACE_y',
 'ACH_y',
 'ACM_y',
 'ACT_y',
 'ACX_y',
 'ADA_y',
 'ADX_y',
 'AEUR_y',
 'AEVO_y',
 'AGLD_y',
 'AI_y',
 'AIXBT_y',
 'ALCX_y',
 'ALGO_y',
 'ALICE_y',
 'ALLO_y',
 'ALPINE_y',
 'ALT_y',
 'AMP_y',
 'ANIME_y',
 'ANKR_y',
 'APE_y',
 'API3_y',
 'APT_y',
 'AR_y',
 'ARB_y',
 'ARDR_y',
 'ARK_y',
 'ARKM_y',
 'ARPA_y',
 'ASR_y',
 'ASTER_y',
 'ASTR_y',
 'AT_y',
 'ATA_y',
 'ATM_y',
 'ATOM_y',
 'AUCTION_y',
 'AUDIO_y',
 'AVA_y',
 'AVAX_y',
 'AVNT_y',
 'AWE_y',
 'AXL_y',
 'AXS_y',
 'BABY_y',
 'BANANA_y',
 'BANANAS31_y',
 'BAND_y',
 'BANK_y',
 'BAR_y',
 'BARD_y',
 'BAT_y',
 'BB_y',
 'BCH_y',
 'BEAMX_y',
 'BEL_y',
 'BERA_y',
 'BFUSD_y',
 'BICO_y',
 'BIFI_y',
 'BIGTIME_y',
 'BIO_y',
 'BLUR_y',
 'BMT_y',
 'BNB_y',
 'BNSOL_y',
 'BNT_y',
 'BOME_y',
 'BONK_y',
 'BREV_y',
 'BROCCOLI714_y',
 'BTC_y',
 'BTTC_y',
 'C_y',
 'C98_y',
 'CAKE_y',
 'CATI_y',
 'CELO_y',
 'CELR_y',
 'CETUS_y',
 'CFX_y',
 'CGPT_y',
 'CHESS_y',
 'CHR_y',
 'CHZ_y',
 'CITY_y',
 'CKB_y',
 'COMP_y',
 'COOKIE_y',
 'COS_y',
 'COTI_y',
 'COW_y',
 'CRV_y',
 'CTK_y',
 'CTSI_y',
 'CVC_y',
 'CVX_y',
 'CYBER_y',
 'D_y',
 'DAI_y',
 'DASH_y',
 'DATA_y',
 'DCR_y',
 'DEGO_y',
 'DENT_y',
 'DEXE_y',
 'DF_y',
 'DGB_y',
 'DIA_y',
 'DODO_y',
 'DOGE_y',
 'DOGS_y',
 'DOLO_y',
 'DOT_y',
 'DUSK_y',
 'DYDX_y',
 'DYM_y',
 'EDEN_y',
 'EDU_y',
 'EGLD_y',
 'EIGEN_y',
 'ENA_y',
 'ENJ_y',
 'ENS_y',
 'ENSO_y',
 'EPIC_y',
 'ERA_y',
 'ETC_y',
 'ETH_y',
 'ETHFI_y',
 'EUL_y',
 'EUR_y',
 'EURI_y',
 'F_y',
 'FARM_y',
 'FDUSD_y',
 'FET_y',
 'FF_y',
 'FIDA_y',
 'FIL_y',
 'FIO_y',
 'FLOKI_y',
 'FLOW_y',
 'FLUX_y',
 'FOGO_y',
 'FORM_y',
 'FORTH_y',
 'FRAX_y',
 'FTT_y',
 'FUN_y',
 'FXS_y',
 'G_y',
 'GALA_y',
 'GAS_y',
 'GHST_y',
 'GIGGLE_y',
 'GLM_y',
 'GLMR_y',
 'GMT_y',
 'GMX_y',
 'GNO_y',
 'GNS_y',
 'GPS_y',
 'GRT_y',
 'GTC_y',
 'GUN_y',
 'HAEDAL_y',
 'HBAR_y',
 'HEI_y',
 'HEMI_y',
 'HFT_y',
 'HIGH_y',
 'HIVE_y',
 'HMSTR_y',
 'HOLO_y',
 'HOME_y',
 'HOOK_y',
 'HOT_y',
 'HUMA_y',
 'HYPER_y',
 'ICP_y',
 'ICX_y',
 'ID_y',
 'IDEX_y',
 'ILV_y',
 'IMX_y',
 'INIT_y',
 'INJ_y',
 'IO_y',
 'IOST_y',
 'IOTA_y',
 'IOTX_y',
 'IQ_y',
 'JASMY_y',
 'JOE_y',
 'JST_y',
 'JTO_y',
 'JUP_y',
 'JUV_y',
 'KAIA_y',
 'KAITO_y',
 'KAVA_y',
 'KERNEL_y',
 'KGST_y',
 'KITE_y',
 'KMNO_y',
 'KNC_y',
 'KSM_y',
 'LA_y',
 'LAYER_y',
 'LAZIO_y',
 'LDO_y',
 'LINEA_y',
 'LINK_y',
 'LISTA_y',
 'LPT_y',
 'LQTY_y',
 'LRC_y',
 'LSK_y',
 'LTC_y',
 'LUMIA_y',
 'LUNA_y',
 'LUNC_y',
 'MAGIC_y',
 'MANA_y',
 'MANTA_y',
 'MASK_y',
 'MAV_y',
 'MBL_y',
 'MBOX_y',
 'MDT_y',
 'ME_y',
 'MEME_y',
 'MET_y',
 'METIS_y',
 'MINA_y',
 'MIRA_y',
 'MITO_y',
 'MLN_y',
 'MMT_y',
 'MORPHO_y',
 'MOVE_y',
 'MOVR_y',
 'MTL_y',
 'MUBARAK_y',
 'NEAR_y',
 'NEIRO_y',
 'NEO_y',
 'NEWT_y',
 'NEXO_y',
 'NFP_y',
 'NIL_y',
 'NKN_y',
 'NMR_y',
 'NOM_y',
 'NOT_y',
 'NTRN_y',
 'NXPC_y',
 'OG_y',
 'OGN_y',
 'OM_y',
 'ONDO_y',
 'ONE_y',
 'ONG_y',
 'ONT_y',
 'OP_y',
 'OPEN_y',
 'ORCA_y',
 'ORDI_y',
 'OSMO_y',
 'OXT_y',
 'PARTI_y',
 'PAXG_y',
 'PENDLE_y',
 'PENGU_y',
 'PEOPLE_y',
 'PEPE_y',
 'PHA_y',
 'PHB_y',
 'PIVX_y',
 'PIXEL_y',
 'PLUME_y',
 'PNUT_y',
 'POL_y',
 'POLYX_y',
 'POND_y',
 'PORTAL_y',
 'PORTO_y',
 'POWR_y',
 'PROM_y',
 'PROVE_y',
 'PSG_y',
 'PUMP_y',
 'PUNDIX_y',
 'PYR_y',
 'PYTH_y',
 'QI_y',
 'QKC_y',
 'QNT_y',
 'QTUM_y',
 'QUICK_y',
 'RAD_y',
 'RARE_y',
 'RAY_y',
 'RDNT_y',
 'RED_y',
 'RENDER_y',
 'REQ_y',
 'RESOLV_y',
 'REZ_y',
 'RIF_y',
 'RLC_y',
 'RLUSD_y',
 'RONIN_y',
 'ROSE_y',
 'RPL_y',
 'RSR_y',
 'RUNE_y',
 'RVN_y',
 'S_y',
 'SAGA_y',
 'SAHARA_y',
 'SAND_y',
 'SANTOS_y',
 'SAPIEN_y',
 'SC_y',
 'SCR_y',
 'SCRT_y',
 'SEI_y',
 'SENT_y',
 'SFP_y',
 'SHELL_y',
 'SHIB_y',
 'SIGN_y',
 'SKL_y',
 'SKY_y',
 'SLP_y',
 'SNX_y',
 'SOL_y',
 'SOLV_y',
 'SOMI_y',
 'SOPH_y',
 'SPELL_y',
 'SPK_y',
 'SSV_y',
 'STEEM_y',
 'STG_y',
 'STO_y',
 'STORJ_y',
 'STRAX_y',
 'STRK_y',
 'STX_y',
 'SUI_y',
 'SUN_y',
 'SUPER_y',
 'SUSHI_y',
 'SXP_y',
 'SXT_y',
 'SYN_y',
 'SYRUP_y',
 'SYS_y',
 'T_y',
 'TAO_y',
 'TFUEL_y',
 'THE_y',
 'THETA_y',
 'TIA_y',
 'TKO_y',
 'TLM_y',
 'TNSR_y',
 'TON_y',
 'TOWNS_y',
 'TRB_y',
 'TREE_y',
 'TRU_y',
 'TRUMP_y',
 'TRX_y',
 'TST_y',
 'TURBO_y',
 'TURTLE_y',
 'TUSD_y',
 'TUT_y',
 'TWT_y',
 'U_y',
 'UMA_y',
 'UNI_y',
 'USD1_y',
 'USDC_y',
 'USDE_y',
 'USDP_y',
 'USDT_y',
 'USTC_y',
 'USUAL_y',
 'UTK_y',
 'VANA_y',
 'VANRY_y',
 'VELODROME_y',
 'VET_y',
 'VIC_y',
 'VIRTUAL_y',
 'VTHO_y',
 'W_y',
 'WAL_y',
 'WAN_y',
 'WAXP_y',
 'WBETH_y',
 'WBTC_y',
 'WCT_y',
 'WIF_y',
 'WIN_y',
 'WLD_y',
 'WLFI_y',
 'WOO_y',
 'XAI_y',
 'XEC_y',
 'XLM_y',
 'XNO_y',
 'XPL_y',
 'XRP_y',
 'XTZ_y',
 'XUSD_y',
 'XVG_y',
 'XVS_y',
 'YB_y',
 'YFI_y',
 'YGG_y',
 'ZBT_y',
 'ZEC_y',
 'ZEN_y',
 'ZIL_y',
 'ZK_y',
 'ZKC_y',
 'ZKP_y',
 'ZRO_y',
 'ZRX_y',
 '币安人生_y',
 'FIS_y',
 'REI_y',
 'VOXEL_y',
 'FLM_y',
 'KDA_y',
 'PERP_y',
 'BAKE_y',
 'HIFI_y',
 'MKR_y',
 'OMNI_y',
 'SLF_y',
 'ALPHA_y',
 'BSW_y',
 'KMD_y',
 'LEVER_y',
 'LOKA_y',
 'LTO_y',
 'ALPACA_y',
 'EOS_y',
 'PDA_y',
 'STPT_y',
 'VIB_y',
 'WING_y',
 'BADGER_y',
 'BAL_y',
 'BETA_y',
 'CREAM_y',
 'CTXC_y',
 'ELF_y',
 'FIRO_y',
 'HARD_y',
 'NULS_y',
 'PROS_y',
 'SNT_y',
 'TROY_y',
 'UFT_y',
 'VIDT_y',
 'AERGO_y',
 'AST_y',
 'BNX_y',
 'BURGER_y',
 'COMBO_y',
 'ERN_y',
 'LINA_y',
 'AMB_y',
 'CLV_y',
 'LIT_y',
 'STMX_y',
 'VITE_y',
 'DAR_y',
 'FTM_y',
 'AKRO_y',
 'BLZ_y',
 'GFT_y',
 'IRIS_y',
 'KEY_y',
 'OAX_y',
 'REN_y',
 'WRX_y',
 'KP3R_y',
 'OOKI_y',
 'UNFI_y']

##1 checkpoint

In [ ]:
archivo_salida = ruta + "112024-122025.parquet"

df.to_parquet(archivo_salida, index=False)

print(f"Guardado en: {archivo_salida}")

Guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025.parquet

APERTURA

In [ ]:
df = pd.read_parquet('/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025.parquet')

In [ ]:
terminaciones = (
    "_active_users",
    "_spot_account_liquidity",
    "_exchange_reserves",
    "_orderbook_depth",
)

columnas_eliminar = [
    columna for columna in df.columns
    if columna.strip().endswith(terminaciones)
]

df.drop(columns=columnas_eliminar, inplace=True)

print(f"Columnas eliminadas: {len(columnas_eliminar)}")
print(f"Columnas restantes: {df.shape[1]}")

Columnas eliminadas: 510
Columnas restantes: 7143

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 7653 entries, bar_start to UNFI_active_users
dtypes: bool(329), boolean(1020), datetime64[ns, UTC](2), float64(5611), object(181), string(510)
memory usage: 6.5+ GB

In [ ]:
columnas_proxy = [
    columna for columna in df.columns
    if columna.strip().endswith("_price_is_proxy")
]

conteo_verdadero = pd.DataFrame({
    "columna": columnas_proxy,
    "cantidad_verdadero": [
        df[columna].astype(str).str.strip().str.lower()
        .isin(["verdadero", "true"])
        .sum()
        for columna in columnas_proxy
    ]
})

conteo_verdadero

                       columna  cantidad_verdadero
0            0G_price_is_proxy                   0
1       1000CAT_price_is_proxy                   0
2    1000CHEEMS_price_is_proxy                   0
3      1000SATS_price_is_proxy                   0
4         1INCH_price_is_proxy                   0
..                         ...                 ...
505         REN_price_is_proxy                   0
506         WRX_price_is_proxy                   0
507        KP3R_price_is_proxy                   0
508        OOKI_price_is_proxy                   0
509        UNFI_price_is_proxy                   0

[510 rows x 2 columns]

In [ ]:
terminaciones = (
    "_price_is_proxy",
    "_source_pair",
)

columnas_eliminar = [
    columna for columna in df.columns
    if columna.strip().endswith(terminaciones)
]

df.drop(columns=columnas_eliminar, inplace=True)

print(f"Columnas eliminadas: {len(columnas_eliminar)}")
print(f"Columnas restantes: {df.shape[1]}")

Columnas eliminadas: 0
Columnas restantes: 6123

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 6123 entries, bar_start to UNFI_taker_sell_usdt_proxy
dtypes: bool(329), boolean(510), datetime64[ns, UTC](2), float64(5101), object(181)
memory usage: 5.3+ GB

In [ ]:
columnas_btc = [columna for columna in df.columns if columna.startswith("BTC")]

resumen_btc = pd.DataFrame({
    "columna": columnas_btc,
    "tipo_dato": [str(df[columna].dtype) for columna in columnas_btc],
    "cantidad_nan": [df[columna].isna().sum() for columna in columnas_btc]
})

resumen_btc

                      columna tipo_dato  cantidad_nan
0                       BTC_y   float64             0
1                     BTCUSDT   float64             0
2                       BTC_v   float64             0
3                      BTC_yp   float64             0
4                BTC_observed      bool             0
5          BTC_active_trading   boolean             0
6     BTC_turnover_usdt_proxy   float64             0
7         BTC_range_rel_proxy   float64             0
8       BTC_illiquidity_proxy   float64             0
9   BTC_activity_trades_proxy   float64             0
10   BTC_taker_buy_usdt_proxy   float64             0
11  BTC_taker_sell_usdt_proxy   float64             0

In [ ]:
terminaciones_excluidas = ("_observed", "_active_trading")

columnas_rellenar = [
    columna for columna in df.columns
    if not columna.strip().endswith(terminaciones_excluidas)
]

columnas_string = df[columnas_rellenar].select_dtypes(include="string").columns
df[columnas_string] = df[columnas_string].astype(object)

df[columnas_rellenar] = df[columnas_rellenar].fillna(0)

In [ ]:
df[["BTC_observed", "BTC_active_trading"]].apply(
    lambda columna: columna.unique()
)

   BTC_observed  BTC_active_trading
0          True                True

In [ ]:
for columna in ["0G_observed", "0G_active_trading"]:
    print(f"\n{columna}:")
    print(df[columna].value_counts(dropna=False))

0G_observed:
0G_observed
False    93720
True     37896
Name: count, dtype: int64

0G_active_trading:
0G_active_trading
<NA>     93720
True     37884
False       12
Name: count, dtype: Int64

In [ ]:
terminaciones = ("_observed", "_active_trading")

columnas_binarias = [
    columna for columna in df.columns
    if columna.strip().endswith(terminaciones)
]

for columna in columnas_binarias:
    df[columna] = (
        df[columna]
        .astype(str)
        .str.strip()
        .str.lower()
        .isin(["true", "verdadero", "1"])
        .astype("int8")
    )

print(f"Columnas transformadas: {len(columnas_binarias)}")

Columnas transformadas: 1020

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 6123 entries, bar_start to UNFI_taker_sell_usdt_proxy
dtypes: datetime64[ns, UTC](2), float64(5101), int8(1020)
memory usage: 5.1 GB

In [ ]:
df.fillna(0, inplace=True)

print("NaN restantes:", df.isna().sum().sum())

NaN restantes: 0

##2 checkpoint

In [ ]:
ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

archivo_salida = ruta + "112024-122025_clean.parquet"

df.to_parquet(archivo_salida, index=False)

print(f"Guardado en: {archivo_salida}")

NameError: name 'df' is not defined

***APERTURA***

In [ ]:
df = pd.read_parquet('/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025_clean.parquet')

In [ ]:
columnas = [
    "BTC_v",
    "BTC_y",
    "BTCUSDT",
    "BTC_yp",
    "BTC_turnover_usdt_proxy",
    "BTC_taker_buy_usdt_proxy",
    "BTC_taker_sell_usdt_proxy",
]

df[columnas].head(10)

,BTC_v,BTC_y,BTCUSDT,BTC_yp,BTC_turnover_usdt_proxy,BTC_taker_buy_usdt_proxy,BTC_taker_sell_usdt_proxy
0,18.44460,1.617627e+06,87701.91,0.101281,1.616916e+06,1.030904e+06,5.860119e+05
1,57.78717,5.071637e+06,87764.06,0.121691,5.071411e+06,3.156417e+06,1.914995e+06
2,9.86578,8.656493e+05,87742.61,0.041887,8.657513e+05,4.469103e+05,4.188411e+05
3,9.47001,8.310899e+05,87760.19,0.060476,8.310241e+05,4.535474e+05,3.774766e+05
4,4.62578,4.060231e+05,87773.97,0.047821,4.060062e+05,2.246350e+05,1.813713e+05
5,10.01792,8.793347e+05,87776.18,0.105609,8.792995e+05,4.991542e+05,3.801452e+05
6,30.28030,2.657060e+06,87748.79,0.239094,2.657410e+06,1.728764e+06,9.286457e+05
7,13.56688,1.190468e+06,87748.10,0.137939,1.190437e+06,7.603544e+05,4.300828e+05
8,8.00349,7.022974e+05,87748.89,0.106331,7.023146e+05,3.131658e+05,3.891488e+05
9,10.14603,8.909551e+05,87813.17,0.099907,8.904335e+05,7.385142e+05,1.519194e+05

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 7143 entries, bar_start to UNFI_taker_sell_usdt_proxy
dtypes: bool(329), boolean(1020), datetime64[ns, UTC](2), float64(5101), object(181), string(510)
memory usage: 6.0+ GB

In [ ]:
columnas_eth = [
    columna for columna in df.columns
    if columna.upper().startswith("ETHFI")
]

print(f"Total de columnas: {len(columnas_eth)}")
print(columnas_eth)

df[columnas_eth].head(10)

Total de columnas: 14
['ETHFI_y', 'ETHFIUSDT', 'ETHFI_v', 'ETHFI_yp', 'ETHFI_source_pair', 'ETHFI_price_is_proxy', 'ETHFI_observed', 'ETHFI_active_trading', 'ETHFI_turnover_usdt_proxy', 'ETHFI_range_rel_proxy', 'ETHFI_illiquidity_proxy', 'ETHFI_activity_trades_proxy', 'ETHFI_taker_buy_usdt_proxy', 'ETHFI_taker_sell_usdt_proxy']

,ETHFI_y,ETHFIUSDT,ETHFI_v,ETHFI_yp,ETHFI_source_pair,ETHFI_price_is_proxy,ETHFI_observed,ETHFI_active_trading,ETHFI_turnover_usdt_proxy,ETHFI_range_rel_proxy,ETHFI_illiquidity_proxy,ETHFI_activity_trades_proxy,ETHFI_taker_buy_usdt_proxy,ETHFI_taker_sell_usdt_proxy
0,2146.0972,0.689,3114.8,0.000134,ETHFIUSDT,False,True,True,2145.8058,0.002903,6.773625e-07,29.0,1974.7433,171.0625
1,36112.2814,0.689,52412.6,0.000866,ETHFIUSDT,False,True,True,36174.8459,0.002903,0.000000e+00,170.0,20134.7933,16040.0526
2,10806.6912,0.688,15707.4,0.000523,ETHFIUSDT,False,True,True,10812.1127,0.002907,2.680837e-07,62.0,593.8572,10218.2555
3,5369.3081,0.689,7792.9,0.000391,ETHFIUSDT,False,True,True,5368.8536,0.001451,2.707260e-07,50.0,3900.8013,1468.0523
4,1850.7180,0.690,2682.2,0.000218,ETHFIUSDT,False,True,True,1848.5967,0.001449,0.000000e+00,15.0,337.0650,1511.5317
5,10702.0683,0.693,15443.1,0.001285,ETHFIUSDT,False,True,True,10693.8648,0.002886,2.706558e-07,53.0,6659.4385,4034.4263
6,685.3568,0.692,990.4,0.000062,ETHFIUSDT,False,True,True,685.3568,0.000000,0.000000e+00,17.0,234.1036,451.2532
7,8343.7208,0.692,12057.4,0.000967,ETHFIUSDT,False,True,True,8343.5552,0.002890,0.000000e+00,105.0,2933.7519,5409.8033
8,6800.6147,0.691,9841.7,0.001030,ETHFIUSDT,False,True,True,6810.2683,0.001447,2.121923e-07,86.0,382.3992,6427.8691
9,3164.1700,0.692,4572.5,0.000355,ETHFIUSDT,False,True,True,3160.0175,0.002890,4.579652e-07,34.0,2571.7560,588.2615

In [ ]:
terminaciones = (
    "_price_is_proxy",
    "_source_pair",
)

columnas_eliminar = [
    columna for columna in df.columns
    if columna.strip().endswith(terminaciones)
]

df.drop(columns=columnas_eliminar, inplace=True)

print(f"Columnas eliminadas: {len(columnas_eliminar)}")
print(f"Columnas restantes: {df.shape[1]}")

Columnas eliminadas: 1020
Columnas restantes: 6123

In [ ]:
terminaciones = ("_observed", "_active_trading")

columnas_binarias = [
    columna for columna in df.columns
    if columna.strip().endswith(terminaciones)
]

for columna in columnas_binarias:
    df[columna] = (
        df[columna]
        .astype(str)
        .str.strip()
        .str.lower()
        .isin(["true", "verdadero", "1"])
        .astype("int8")
    )

print(f"Columnas transformadas: {len(columnas_binarias)}")

Columnas transformadas: 1020

In [ ]:
columnas_eth = [
    columna for columna in df.columns
    if columna.upper().startswith("ETHFI")
]

print(f"Total de columnas: {len(columnas_eth)}")
print(columnas_eth)

df[columnas_eth].head(10)

Total de columnas: 12
['ETHFI_y', 'ETHFIUSDT', 'ETHFI_v', 'ETHFI_yp', 'ETHFI_observed', 'ETHFI_active_trading', 'ETHFI_turnover_usdt_proxy', 'ETHFI_range_rel_proxy', 'ETHFI_illiquidity_proxy', 'ETHFI_activity_trades_proxy', 'ETHFI_taker_buy_usdt_proxy', 'ETHFI_taker_sell_usdt_proxy']

,ETHFI_y,ETHFIUSDT,ETHFI_v,ETHFI_yp,ETHFI_observed,ETHFI_active_trading,ETHFI_turnover_usdt_proxy,ETHFI_range_rel_proxy,ETHFI_illiquidity_proxy,ETHFI_activity_trades_proxy,ETHFI_taker_buy_usdt_proxy,ETHFI_taker_sell_usdt_proxy
0,2146.0972,0.689,3114.8,0.000134,1,1,2145.8058,0.002903,6.773625e-07,29.0,1974.7433,171.0625
1,36112.2814,0.689,52412.6,0.000866,1,1,36174.8459,0.002903,0.000000e+00,170.0,20134.7933,16040.0526
2,10806.6912,0.688,15707.4,0.000523,1,1,10812.1127,0.002907,2.680837e-07,62.0,593.8572,10218.2555
3,5369.3081,0.689,7792.9,0.000391,1,1,5368.8536,0.001451,2.707260e-07,50.0,3900.8013,1468.0523
4,1850.7180,0.690,2682.2,0.000218,1,1,1848.5967,0.001449,0.000000e+00,15.0,337.0650,1511.5317
5,10702.0683,0.693,15443.1,0.001285,1,1,10693.8648,0.002886,2.706558e-07,53.0,6659.4385,4034.4263
6,685.3568,0.692,990.4,0.000062,1,1,685.3568,0.000000,0.000000e+00,17.0,234.1036,451.2532
7,8343.7208,0.692,12057.4,0.000967,1,1,8343.5552,0.002890,0.000000e+00,105.0,2933.7519,5409.8033
8,6800.6147,0.691,9841.7,0.001030,1,1,6810.2683,0.001447,2.121923e-07,86.0,382.3992,6427.8691
9,3164.1700,0.692,4572.5,0.000355,1,1,3160.0175,0.002890,4.579652e-07,34.0,2571.7560,588.2615

In [ ]:
columnas_eth = [
    columna for columna in df.columns
    if columna.upper().startswith("BTC")
]

print(f"Total de columnas: {len(columnas_eth)}")
print(columnas_eth)

df[columnas_eth].head(10)

Total de columnas: 12
['BTC_y', 'BTCUSDT', 'BTC_v', 'BTC_yp', 'BTC_observed', 'BTC_active_trading', 'BTC_turnover_usdt_proxy', 'BTC_range_rel_proxy', 'BTC_illiquidity_proxy', 'BTC_activity_trades_proxy', 'BTC_taker_buy_usdt_proxy', 'BTC_taker_sell_usdt_proxy']

,BTC_y,BTCUSDT,BTC_v,BTC_yp,BTC_observed,BTC_active_trading,BTC_turnover_usdt_proxy,BTC_range_rel_proxy,BTC_illiquidity_proxy,BTC_activity_trades_proxy,BTC_taker_buy_usdt_proxy,BTC_taker_sell_usdt_proxy
0,1.617627e+06,87701.91,18.44460,0.101281,1,1,1.616916e+06,0.000789,3.789168e-10,4776.0,1.030904e+06,5.860119e+05
1,5.071637e+06,87764.06,57.78717,0.121691,1,1,5.071411e+06,0.001300,1.397344e-10,10412.0,3.156417e+06,1.914995e+06
2,8.656493e+05,87742.61,9.86578,0.041887,1,1,8.657513e+05,0.000245,2.823043e-10,2065.0,4.469103e+05,4.188411e+05
3,8.310899e+05,87760.19,9.47001,0.060476,1,1,8.310241e+05,0.000200,2.409614e-10,2382.0,4.535474e+05,3.774766e+05
4,4.060231e+05,87773.97,4.62578,0.047821,1,1,4.060062e+05,0.000157,3.867399e-10,1941.0,2.246350e+05,1.813713e+05
5,8.793347e+05,87776.18,10.01792,0.105609,1,1,8.792995e+05,0.000088,2.850494e-11,1745.0,4.991542e+05,3.801452e+05
6,2.657060e+06,87748.79,30.28030,0.239094,1,1,2.657410e+06,0.000312,1.174668e-10,2863.0,1.728764e+06,9.286457e+05
7,1.190468e+06,87748.10,13.56688,0.137939,1,1,1.190437e+06,0.000309,6.509705e-12,2745.0,7.603544e+05,4.300828e+05
8,7.022974e+05,87748.89,8.00349,0.106331,1,1,7.023146e+05,0.000138,1.298137e-11,1753.0,3.131658e+05,3.891488e+05
9,8.909551e+05,87813.17,10.14603,0.099907,1,1,8.904335e+05,0.000732,8.226834e-10,5201.0,7.385142e+05,1.519194e+05

In [ ]:
columnas_eth = [
    columna for columna in df.columns
    if columna.upper().startswith("ETH")
]

print(f"Total de columnas: {len(columnas_eth)}")
print(columnas_eth)

df[columnas_eth].head(10)

Total de columnas: 24
['ETH_y', 'ETHFI_y', 'ETHUSDT', 'ETHFIUSDT', 'ETH_v', 'ETHFI_v', 'ETH_yp', 'ETHFI_yp', 'ETH_observed', 'ETH_active_trading', 'ETH_turnover_usdt_proxy', 'ETH_range_rel_proxy', 'ETH_illiquidity_proxy', 'ETH_activity_trades_proxy', 'ETH_taker_buy_usdt_proxy', 'ETH_taker_sell_usdt_proxy', 'ETHFI_observed', 'ETHFI_active_trading', 'ETHFI_turnover_usdt_proxy', 'ETHFI_range_rel_proxy', 'ETHFI_illiquidity_proxy', 'ETHFI_activity_trades_proxy', 'ETHFI_taker_buy_usdt_proxy', 'ETHFI_taker_sell_usdt_proxy']

,ETH_y,ETHFI_y,ETHUSDT,ETHFIUSDT,ETH_v,ETHFI_v,ETH_yp,ETHFI_yp,ETH_observed,ETH_active_trading,...,ETH_taker_buy_usdt_proxy,ETH_taker_sell_usdt_proxy,ETHFI_observed,ETHFI_active_trading,ETHFI_turnover_usdt_proxy,ETHFI_range_rel_proxy,ETHFI_illiquidity_proxy,ETHFI_activity_trades_proxy,ETHFI_taker_buy_usdt_proxy,ETHFI_taker_sell_usdt_proxy
0,1.375823e+06,2146.0972,2974.56,0.689,462.5299,3114.8,0.086142,0.000134,1,1,...,8.181180e+05,5.568502e+05,1,1,2145.8058,0.002903,6.773625e-07,29.0,1974.7433,171.0625
1,6.338665e+06,36112.2814,2978.08,0.689,2128.4402,52412.6,0.152093,0.000866,1,1,...,4.927107e+06,1.411279e+06,1,1,36174.8459,0.002903,0.000000e+00,170.0,20134.7933,16040.0526
2,6.217955e+05,10806.6912,2976.22,0.688,208.9212,15707.4,0.030087,0.000523,1,1,...,4.084605e+05,2.135664e+05,1,1,10812.1127,0.002907,2.680837e-07,62.0,593.8572,10218.2555
3,3.851632e+05,5369.3081,2977.62,0.689,129.3527,7792.9,0.028027,0.000391,1,1,...,2.217801e+05,1.633488e+05,1,1,5368.8536,0.001451,2.707260e-07,50.0,3900.8013,1468.0523
4,4.917511e+05,1850.7180,2978.42,0.690,165.1047,2682.2,0.057917,0.000218,1,1,...,2.561848e+05,2.356216e+05,1,1,1848.5967,0.001449,0.000000e+00,15.0,337.0650,1511.5317
5,4.618046e+05,10702.0683,2979.75,0.693,154.9810,15443.1,0.055463,0.001285,1,1,...,2.741129e+05,1.876543e+05,1,1,10693.8648,0.002886,2.706558e-07,53.0,6659.4385,4034.4263
6,7.350082e+05,685.3568,2980.12,0.692,246.6371,990.4,0.066139,0.000062,1,1,...,2.770859e+05,4.578137e+05,1,1,685.3568,0.000000,0.000000e+00,17.0,234.1036,451.2532
7,7.891052e+05,8343.7208,2979.56,0.692,264.8395,12057.4,0.091433,0.000967,1,1,...,5.430179e+05,2.461026e+05,1,1,8343.5552,0.002890,0.000000e+00,105.0,2933.7519,5409.8033
8,2.273687e+05,6800.6147,2979.63,0.691,76.3077,9841.7,0.034425,0.001030,1,1,...,1.007475e+05,1.266227e+05,1,1,6810.2683,0.001447,2.121923e-07,86.0,382.3992,6427.8691
9,6.389645e+05,3164.1700,2981.84,0.692,214.2853,4572.5,0.071650,0.000355,1,1,...,4.923904e+05,1.462816e+05,1,1,3160.0175,0.002890,4.579652e-07,34.0,2571.7560,588.2615

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 6123 entries, bar_start to UNFI_taker_sell_usdt_proxy
dtypes: datetime64[ns, UTC](2), float64(5101), int8(1020)
memory usage: 5.1 GB

##3 checkpoint

In [ ]:
ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

archivo_salida = ruta + "112024-122025_clean.parquet"

df.to_parquet(archivo_salida, index=False)

print(f"Guardado en: {archivo_salida}")

Guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025_clean.parquet

***APERTURA***

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Mounted at /content/drive

In [ ]:
df = pd.read_parquet('/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025_clean.parquet')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 7143 entries, bar_start to UNFI_taker_sell_usdt_proxy
dtypes: bool(329), boolean(1020), datetime64[ns, UTC](2), float64(5101), object(181), string(510)
memory usage: 6.0+ GB

In [ ]:
columnas_btc = [columna for columna in df.columns if columna.startswith("BTC")]

resumen_btc = pd.DataFrame({
    "columna": columnas_btc,
    "tipo_dato": [str(df[columna].dtype) for columna in columnas_btc],
    "cantidad_nan": [df[columna].isna().sum() for columna in columnas_btc]
})

resumen_btc

                      columna tipo_dato  cantidad_nan
0                       BTC_y   float64             0
1                     BTCUSDT   float64             0
2                       BTC_v   float64             0
3                      BTC_yp   float64             0
4             BTC_source_pair    string             0
5          BTC_price_is_proxy   boolean             0
6                BTC_observed      bool             0
7          BTC_active_trading   boolean             0
8     BTC_turnover_usdt_proxy   float64             0
9         BTC_range_rel_proxy   float64             0
10      BTC_illiquidity_proxy   float64             0
11  BTC_activity_trades_proxy   float64             0
12   BTC_taker_buy_usdt_proxy   float64             0
13  BTC_taker_sell_usdt_proxy   float64             0

In [ ]:
df.drop(columns=["bar_start"], inplace=True)

In [ ]:
df["bar_end"] = pd.to_datetime(df["bar_end"], utc=True, errors="coerce")

df = (
    df.sort_values("bar_end", ascending=True, na_position="last")
      .reset_index(drop=True)
)

print("Primera fecha:", df["bar_end"].iloc[0])
print("Última fecha:", df["bar_end"].dropna().iloc[-1])
print("Fechas inválidas:", df["bar_end"].isna().sum())

Primera fecha: 2024-11-01 00:05:00+00:00
Última fecha: 2026-02-01 00:00:00+00:00
Fechas inválidas: 0

In [ ]:
df.head(5)

,bar_end,0G_y,1000CAT_y,1000CHEEMS_y,1000SATS_y,1INCH_y,1MBABYDOGE_y,2Z_y,A_y,A2Z_y,...,UNFI_source_pair,UNFI_price_is_proxy,UNFI_observed,UNFI_active_trading,UNFI_turnover_usdt_proxy,UNFI_range_rel_proxy,UNFI_illiquidity_proxy,UNFI_activity_trades_proxy,UNFI_taker_buy_usdt_proxy,UNFI_taker_sell_usdt_proxy
0,2024-11-01 00:05:00+00:00,NaN,NaN,NaN,51731.435518,3991.89128,33958.220310,NaN,NaN,NaN,...,UNFIUSDT,False,True,True,54048.7484,0.030599,3.685621e-07,375.0,26784.0283,27264.7201
1,2024-11-01 00:10:00+00:00,NaN,NaN,NaN,47247.263729,3668.66241,45070.511015,NaN,NaN,NaN,...,UNFIUSDT,False,True,True,25047.4190,0.015082,2.859160e-07,222.0,17023.4293,8023.9897
2,2024-11-01 00:15:00+00:00,NaN,NaN,NaN,36383.858073,2242.51300,41139.876284,NaN,NaN,NaN,...,UNFIUSDT,False,True,True,7368.3872,0.006549,0.000000e+00,74.0,3003.0346,4365.3526
3,2024-11-01 00:20:00+00:00,NaN,NaN,NaN,13662.238318,1834.76328,14008.003500,NaN,NaN,NaN,...,UNFIUSDT,False,True,True,7220.5648,0.006566,3.627854e-07,99.0,5095.2308,2125.3340
4,2024-11-01 00:25:00+00:00,NaN,NaN,NaN,26188.801262,155.05095,21522.747327,NaN,NaN,NaN,...,UNFIUSDT,False,True,True,14528.0374,0.007926,4.516563e-07,97.0,6366.9255,8161.1119

In [ ]:
df.tail(5)

,bar_end,0G_y,1000CAT_y,1000CHEEMS_y,1000SATS_y,1INCH_y,1MBABYDOGE_y,2Z_y,A_y,A2Z_y,...,UNFI_source_pair,UNFI_price_is_proxy,UNFI_observed,UNFI_active_trading,UNFI_turnover_usdt_proxy,UNFI_range_rel_proxy,UNFI_illiquidity_proxy,UNFI_activity_trades_proxy,UNFI_taker_buy_usdt_proxy,UNFI_taker_sell_usdt_proxy
131611,2026-01-31 23:40:00+00:00,4501.20538,2694.690713,2785.345755,4148.318339,4805.38508,5038.179525,4374.56188,1119.72168,80.355522,...,<NA>,<NA>,None,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
131612,2026-01-31 23:45:00+00:00,16786.99748,77.795025,4010.823168,475.634719,1481.78816,3299.388171,6768.82018,5444.95200,431.580800,...,<NA>,<NA>,None,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
131613,2026-01-31 23:50:00+00:00,21546.03410,542.659304,6637.042764,5179.110708,4447.19605,2309.454372,2148.11915,1162.17306,1650.706876,...,<NA>,<NA>,None,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
131614,2026-01-31 23:55:00+00:00,20222.55243,1975.399030,2474.380032,12387.896939,2613.94020,2793.118967,968.53663,4152.78929,358.006880,...,<NA>,<NA>,None,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
131615,2026-02-01 00:00:00+00:00,20868.00320,0.000000,5051.682779,2338.733172,11289.16950,1091.253750,10849.18050,7910.28084,326.428025,...,<NA>,<NA>,None,<NA>,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
terminaciones = ("_observed", "_active_trading")

columnas_binarias = [
    columna for columna in df.columns
    if columna.strip().endswith(terminaciones)
]

for columna in columnas_binarias:
    df[columna] = (
        df[columna]
        .astype(str)
        .str.strip()
        .str.lower()
        .isin(["true", "verdadero", "1"])
        .astype("int8")
    )

print(f"Columnas transformadas: {len(columnas_binarias)}")

Columnas transformadas: 1020

In [ ]:
terminaciones = (
    "_price_is_proxy",
    "_source_pair",
)

columnas_eliminar = [
    columna for columna in df.columns
    if columna.strip().endswith(terminaciones)
]

df.drop(columns=columnas_eliminar, inplace=True)

print(f"Columnas eliminadas: {len(columnas_eliminar)}")
print(f"Columnas restantes: {df.shape[1]}")

Columnas eliminadas: 1020
Columnas restantes: 6122

In [ ]:
df.fillna(0, inplace=True)

print("NaN restantes:", df.isna().sum().sum())

NaN restantes: 0

In [ ]:
df.head(5)

,bar_end,0G_y,1000CAT_y,1000CHEEMS_y,1000SATS_y,1INCH_y,1MBABYDOGE_y,2Z_y,A_y,A2Z_y,...,OOKI_taker_buy_usdt_proxy,OOKI_taker_sell_usdt_proxy,UNFI_observed,UNFI_active_trading,UNFI_turnover_usdt_proxy,UNFI_range_rel_proxy,UNFI_illiquidity_proxy,UNFI_activity_trades_proxy,UNFI_taker_buy_usdt_proxy,UNFI_taker_sell_usdt_proxy
0,2024-11-01 00:05:00+00:00,0.0,0.0,0.0,51731.435518,3991.89128,33958.220310,0.0,0.0,0.0,...,25167.963204,5173.475924,1,1,54048.7484,0.030599,3.685621e-07,375.0,26784.0283,27264.7201
1,2024-11-01 00:10:00+00:00,0.0,0.0,0.0,47247.263729,3668.66241,45070.511015,0.0,0.0,0.0,...,8790.924539,8654.402264,1,1,25047.4190,0.015082,2.859160e-07,222.0,17023.4293,8023.9897
2,2024-11-01 00:15:00+00:00,0.0,0.0,0.0,36383.858073,2242.51300,41139.876284,0.0,0.0,0.0,...,18052.892274,87082.499553,1,1,7368.3872,0.006549,0.000000e+00,74.0,3003.0346,4365.3526
3,2024-11-01 00:20:00+00:00,0.0,0.0,0.0,13662.238318,1834.76328,14008.003500,0.0,0.0,0.0,...,24831.481498,23721.195997,1,1,7220.5648,0.006566,3.627854e-07,99.0,5095.2308,2125.3340
4,2024-11-01 00:25:00+00:00,0.0,0.0,0.0,26188.801262,155.05095,21522.747327,0.0,0.0,0.0,...,14601.340607,12364.019859,1,1,14528.0374,0.007926,4.516563e-07,97.0,6366.9255,8161.1119

##4 checkpoint

In [ ]:
ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

archivo_salida = ruta + "112024-122025_clean.parquet"

df.to_parquet(archivo_salida, index=False)

print(f"Guardado en: {archivo_salida}")

Guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025_clean.parquet

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

***APERTURA***

In [ ]:
df = pd.read_parquet('/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025_clean.parquet')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 6122 entries, bar_end to UNFI_taker_sell_usdt_proxy
dtypes: datetime64[ns, UTC](1), float64(5101), int8(1020)
memory usage: 5.1 GB

In [ ]:
df.head(5)

,bar_end,0G_y,1000CAT_y,1000CHEEMS_y,1000SATS_y,1INCH_y,1MBABYDOGE_y,2Z_y,A_y,A2Z_y,...,OOKI_taker_buy_usdt_proxy,OOKI_taker_sell_usdt_proxy,UNFI_observed,UNFI_active_trading,UNFI_turnover_usdt_proxy,UNFI_range_rel_proxy,UNFI_illiquidity_proxy,UNFI_activity_trades_proxy,UNFI_taker_buy_usdt_proxy,UNFI_taker_sell_usdt_proxy
0,2024-11-01 00:05:00+00:00,0.0,0.0,0.0,51731.435518,3991.89128,33958.220310,0.0,0.0,0.0,...,25167.963204,5173.475924,1,1,54048.7484,0.030599,3.685621e-07,375.0,26784.0283,27264.7201
1,2024-11-01 00:10:00+00:00,0.0,0.0,0.0,47247.263729,3668.66241,45070.511015,0.0,0.0,0.0,...,8790.924539,8654.402264,1,1,25047.4190,0.015082,2.859160e-07,222.0,17023.4293,8023.9897
2,2024-11-01 00:15:00+00:00,0.0,0.0,0.0,36383.858073,2242.51300,41139.876284,0.0,0.0,0.0,...,18052.892274,87082.499553,1,1,7368.3872,0.006549,0.000000e+00,74.0,3003.0346,4365.3526
3,2024-11-01 00:20:00+00:00,0.0,0.0,0.0,13662.238318,1834.76328,14008.003500,0.0,0.0,0.0,...,24831.481498,23721.195997,1,1,7220.5648,0.006566,3.627854e-07,99.0,5095.2308,2125.3340
4,2024-11-01 00:25:00+00:00,0.0,0.0,0.0,26188.801262,155.05095,21522.747327,0.0,0.0,0.0,...,14601.340607,12364.019859,1,1,14528.0374,0.007926,4.516563e-07,97.0,6366.9255,8161.1119

#Variables de Segundo Orden, 1ra generacion

In [ ]:
# CELDA 1   → sistema
# CELDA 2   → precio + volumen
# CELDA 3   → actividad
# CELDA 4   → buy/sell
# CELDA 5   → absorción + liquidez
# CELDA 6   → impacto + stress
# CELDA 7   → gp
# CELDA 8   → gp multiescala
# CELDA 9   → N temporal
# CELDA 10  → N competitivo/anidado
# CELDA 11  → N_context + N_theory + E + target
# CELDA 12  → dinámica E_context
# CELDA 13  → dinámica E_theory

In [ ]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    # 5 minutos por barra
    primary_window: int = 288      # 24 h
    min_periods: int = 72          # 6 h
    ewm_span: int = 72             # 6 h

    multiscale_windows: tuple[int, ...] = (
        3,      # 15 min
        12,     # 1 h
        72,     # 6 h
        288,    # 24 h
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    # Reduce RAM al trabajar con 510 activos
    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):
    """
    Añade todas las features de una celda en un único concat.
    Permite volver a ejecutar una celda sin duplicar columnas.
    """

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):
    """
    Compara x_t exclusivamente contra historia t-1,...,t-W.
    """

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):
    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    # Impacto negativo no tiene interpretación
    # como "más resistencia".
    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):

    g = gp0.to_numpy(
        dtype=np.float64,
        copy=False
    )

    s = stress.to_numpy(
        dtype=np.float64,
        copy=False
    )

    q = stress_threshold.to_numpy(
        dtype=np.float64,
        copy=False
    )

    b = baseline.to_numpy(
        dtype=np.float64,
        copy=False
    )

    T, N = g.shape

    output = np.full(
        (T, N),
        np.nan
    )

    for j in range(N):

        in_event = False

        event_start = -1
        event_baseline = np.nan

        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):

            if not in_event:

                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):

                    in_event = True

                    event_start = t
                    event_baseline = b[t, j]

                    consecutive = 0

            else:

                if np.isfinite(g[t, j]):

                    distance = (
                        abs(
                            g[t, j]
                            - event_baseline
                        )
                        /
                        (
                            abs(event_baseline)
                            + eps
                        )
                    )

                    if distance <= tolerance:
                        consecutive += 1
                    else:
                        consecutive = 0

                    if consecutive >= hold_bars:

                        recovery_start = (
                            t
                            - hold_bars
                            + 1
                        )

                        duration = max(
                            1,
                            recovery_start
                            - event_start
                        )

                        if np.isnan(duration_ewma):

                            duration_ewma = float(
                                duration
                            )

                        else:

                            duration_ewma = (
                                alpha * duration
                                + (1-alpha)
                                * duration_ewma
                            )

                        in_event = False

                        event_start = -1
                        event_baseline = np.nan
                        consecutive = 0

            if np.isfinite(duration_ewma):

                output[t, j] = (
                    1.0
                    / (1.0 + duration_ewma)
                )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns
    )


# ============================================================
# INICIALIZACIÓN
# ============================================================

df = validate_time(df, cfg)

assets = discover_assets(
    df,
    cfg
)

print("Activos detectados:", len(assets))

Activos detectados: 510

##1. Variables Sistemicas
SYS_active_nodes
SYS_trades
SYS_imbalance
YS_log
YS_growth
YS_volatility

In [ ]:
n = len(df)

sys_active = np.zeros(n)
sys_trades = np.zeros(n)
sys_buy = np.zeros(n)
sys_sell = np.zeros(n)


for chunk in chunks(
    assets,
    cfg.asset_block_size
):

    O = load_base(
        df, chunk, "O", cfg
    )

    observed = O > 0

    A = load_base(
        df, chunk, "A", cfg
    )

    C = load_base(
        df, chunk, "C", cfg
    ).where(observed)

    B = load_base(
        df, chunk, "B", cfg
    ).where(observed)

    S = load_base(
        df, chunk, "S", cfg
    ).where(observed)

    sys_active += (
        A.sum(axis=1)
        .to_numpy()
    )

    sys_trades += (
        C.sum(axis=1)
        .to_numpy()
    )

    sys_buy += (
        B.sum(axis=1)
        .to_numpy()
    )

    sys_sell += (
        S.sum(axis=1)
        .to_numpy()
    )


sys_flow = (
    sys_buy
    + sys_sell
)

SYS_imbalance = (
    (sys_buy - sys_sell)
    /
    (sys_flow + cfg.eps)
)


YS = (
    df[cfg.ys_col]
    .astype("float64")
)

YS_log = np.log(
    YS.clip(lower=cfg.eps)
)

YS_growth = YS_log.diff()

YS_volatility = (
    YS_growth
    .rolling(
        cfg.primary_window,
        min_periods=cfg.min_periods
    )
    .std()
)


system_features = pd.DataFrame(
    {
        "SYS_active_nodes": sys_active,
        "SYS_trades": sys_trades,
        "SYS_imbalance": SYS_imbalance,
        "YS_log": YS_log,
        "YS_growth": YS_growth,
        "YS_volatility": YS_volatility,
    },
    index=df.index
).astype(cfg.dtype)


df = merge_blocks(
    df,
    [system_features]
)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 6128 entries, bar_end to YS_volatility
dtypes: datetime64[ns, UTC](1), float32(6), float64(5101), int8(1020)
memory usage: 5.1 GB

##2. Precio y Volumen fisico
- Retorno logarimitco del precio:

r(K)i,t = ln(Pi,t) - ln(Pi,t-k) = ln(Pi,t/Pi,t-k)

Mide la respuesta del precio a sus propias perturbaciones por ventanas k


- Desvio estandar rolling:
var_w_(p)_i,t = SD_W(r_i)



rolling_volatility
dlogV
VSTAB

In [ ]:
blocks = []


for chunk in chunks(
    assets,
    cfg.asset_block_size
):

    O = load_base(
        df, chunk, "O", cfg
    )

    A = load_base(
        df, chunk, "A", cfg
    )

    observed = O > 0

    P = load_base(
        df, chunk, "P", cfg
    ).where(observed)

    V = load_base(
        df, chunk, "V", cfg
    ).where(observed)


    # --------------------------------------------
    # Retorno
    # --------------------------------------------

    logP = np.log(
        P.where(P > 0)
    )

    ret = logP.diff(
        cfg.return_lag
    )


    # --------------------------------------------
    # Volatilidad rolling
    # --------------------------------------------

    volatility = (
        ret
        .rolling(
            cfg.primary_window,
            min_periods=cfg.min_periods
        )
        .std()
    )


    # --------------------------------------------
    # Crecimiento de volumen físico
    # --------------------------------------------

    V_valid = V.where(
        (V > 0)
        & (A > 0)
    )

    dlogV = (
        np.log(V_valid)
        .diff()
    )


    # --------------------------------------------
    # Estabilidad del volumen
    # --------------------------------------------

    volume_dispersion = (
        rolling_robust_dispersion(
            dlogV,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )
    )

    VSTAB = np.exp(
        -volume_dispersion
    )


    blocks.extend([
        name_block(
            ret,
            "return_k1",
            cfg
        ),

        name_block(
            volatility,
            "rolling_volatility",
            cfg
        ),

        name_block(
            dlogV,
            "dlogV",
            cfg
        ),

        name_block(
            VSTAB,
            "VSTAB",
            cfg
        ),
    ])


df = merge_blocks(
    df,
    blocks
)

##3. Actividad y Continuidad
TI
PERS_C
Arel
CA
CO

In [ ]:
blocks = []

SYS_trades = (
    df["SYS_trades"]
    .replace(0, np.nan)
)


for chunk in chunks(
    assets,
    cfg.asset_block_size
):

    O = load_base(
        df, chunk, "O", cfg
    )

    A = load_base(
        df, chunk, "A", cfg
    )

    C = load_base(
        df, chunk, "C", cfg
    )

    observed = O > 0

    C = C.where(observed)
    A_masked = A.where(observed)


    # --------------------------------------------
    # Intensidad
    # --------------------------------------------

    logC = np.log1p(
        C.clip(lower=0)
    )

    TI = robust_z_causal(
        logC,
        cfg.primary_window,
        cfg.min_periods,
        cfg.eps
    )


    # --------------------------------------------
    # Persistencia
    # --------------------------------------------

    PERS_C = rolling_autocorr_lag1(
        logC,
        cfg.primary_window,
        cfg.min_periods
    )


    # --------------------------------------------
    # Actividad relativa
    # --------------------------------------------

    Arel = C.div(
        SYS_trades,
        axis=0
    )


    # --------------------------------------------
    # Continuidad activa
    # --------------------------------------------

    CA = (
        A_masked
        .ewm(
            span=cfg.ewm_span,
            adjust=False,
            min_periods=cfg.min_periods
        )
        .mean()
    )


    # --------------------------------------------
    # Continuidad observada
    # --------------------------------------------

    CO = (
        O
        .ewm(
            span=cfg.ewm_span,
            adjust=False,
            min_periods=cfg.min_periods
        )
        .mean()
    )


    blocks.extend([
        name_block(TI, "TI", cfg),
        name_block(PERS_C, "PERS_C", cfg),
        name_block(Arel, "Arel", cfg),
        name_block(CA, "CA", cfg),
        name_block(CO, "CO", cfg),
    ])


df = merge_blocks(
    df,
    blocks
)

##4. Estructura Buy/Sell

SI
SG
SP
imbalance
sell_share
LR_BS
BIL

In [ ]:
blocks = []


for chunk in chunks(
    assets,
    cfg.asset_block_size
):

    O = load_base(
        df, chunk, "O", cfg
    )

    observed = O > 0

    B = load_base(
        df, chunk, "B", cfg
    ).where(observed)

    S = load_base(
        df, chunk, "S", cfg
    ).where(observed)


    # --------------------------------------------
    # Sell intensity
    # --------------------------------------------

    logS1 = np.log1p(
        S.clip(lower=0)
    )

    SI = robust_z_causal(
        logS1,
        cfg.primary_window,
        cfg.min_periods,
        cfg.eps
    )


    # --------------------------------------------
    # Sell growth
    # --------------------------------------------

    SG = (
        np.log(
            S.clip(lower=0)
            + cfg.eps
        )
        .diff()
    )


    # --------------------------------------------
    # Sell persistence
    # --------------------------------------------

    SP = (
        SI
        .ewm(
            span=cfg.ewm_span,
            adjust=False,
            min_periods=cfg.min_periods
        )
        .mean()
    )


    # --------------------------------------------
    # Buy/Sell
    # --------------------------------------------

    total = B + S

    imbalance = (
        (B - S)
        /
        (total + cfg.eps)
    )

    sell_share = (
        S
        /
        (total + cfg.eps)
    )

    LR_BS = np.log(
        (B + cfg.eps)
        /
        (S + cfg.eps)
    )

    BIL = (
        2.0
        * np.minimum(B, S)
        /
        (total + cfg.eps)
    )


    blocks.extend([
        name_block(SI, "SI", cfg),
        name_block(SG, "SG", cfg),
        name_block(SP, "SP", cfg),
        name_block(imbalance, "imbalance", cfg),
        name_block(sell_share, "sell_share", cfg),
        name_block(LR_BS, "LR_BS", cfg),
        name_block(BIL, "BIL", cfg),
    ])


df = merge_blocks(
    df,
    blocks
)

##5. Bilaterailidad, absorcion y liquidez

- Estabilidad Bilateralidad

BILST = EWMA(BIL)*exp(MADw(delta(Bil)))

Persistencia de un mercado bilateral


ABS
ABS_S
RLIQ
RLIQ_S
LIQ

In [ ]:
blocks = []


for chunk in chunks(
    assets,
    cfg.asset_block_size
):

    O = load_base(
        df, chunk, "O", cfg
    )

    observed = O > 0

    C = load_base(
        df, chunk, "C", cfg
    ).where(observed)

    S = load_base(
        df, chunk, "S", cfg
    ).where(observed)

    R = load_base(
        df, chunk, "R", cfg
    ).where(observed)

    L = load_base(
        df, chunk, "L", cfg
    ).where(observed)

    BIL = load_feature(
        df, chunk, "BIL"
    )


    # --------------------------------------------
    # Bilaterality stability
    # --------------------------------------------

    BIL_disp = rolling_robust_dispersion(
        BIL.diff(),
        cfg.primary_window,
        cfg.min_periods,
        cfg.eps
    )

    BILST = (
        BIL
        .ewm(
            span=cfg.ewm_span,
            adjust=False,
            min_periods=cfg.min_periods
        )
        .mean()
        *
        np.exp(-BIL_disp)
    )


    logC = np.log1p(
        C.clip(lower=0)
    )

    logS = np.log1p(
        S.clip(lower=0)
    )

    logL = np.log1p(
        L.clip(lower=0)
    )


    ABS = (
        logC
        /
        (R + cfg.eps)
    )

    ABS_S = (
        logS
        /
        (R + cfg.eps)
    )

    RLIQ = (
        logC
        /
        (1.0 + logL)
    )

    RLIQ_S = (
        logS
        /
        (1.0 + logL)
    )

    LIQ = -logL


    blocks.extend([
        name_block(BILST, "BILST", cfg),
        name_block(ABS, "ABS", cfg),
        name_block(ABS_S, "ABS_S", cfg),
        name_block(RLIQ, "RLIQ", cfg),
        name_block(RLIQ_S, "RLIQ_S", cfg),
        name_block(LIQ, "LIQ", cfg),
    ])


df = merge_blocks(
    df,
    blocks
)

##6. Impacto, stress y supervivencia
- Impact resistence

IR

- Shock Externo:

STRESS = Z_W(R)+Z_W(L)+Z_W(r)

Medir pertubacion, no resistencia

- Survival under stress:

SSR = Median(C|STRESS>q)/ Median(C) +epsilon

cuanta actividad conserva bajo stress

- Ventas sobrevientes bajo schock:

SSR_S = Median(S|STRESS>q)/ Median(S) +epsilon

Cuánta presión vendedora puede absorber en stress

- Venta media por transaccion

AST_S = S/ C + epsilon

Tamaño monetario vendedor por transacción observada


a exluir:
""
FLOW_TOTAL_AUDIT: B+S
TURNOVER_PER_TRADE_AUDIT
""

In [ ]:
blocks = []


for chunk in chunks(
    assets,
    cfg.asset_block_size
):

    O = load_base(
        df, chunk, "O", cfg
    )

    observed = O > 0

    C = load_base(
        df, chunk, "C", cfg
    ).where(observed)

    R = load_base(
        df, chunk, "R", cfg
    ).where(observed)

    L = load_base(
        df, chunk, "L", cfg
    ).where(observed)

    B = load_base(
        df, chunk, "B", cfg
    ).where(observed)

    S = load_base(
        df, chunk, "S", cfg
    ).where(observed)


    ret = load_feature(
        df, chunk, "return_k1"
    )

    imbalance = load_feature(
        df, chunk, "imbalance"
    )


    # --------------------------------------------
    # Impact resistance
    # --------------------------------------------

    logC = np.log1p(
        C.clip(lower=0)
    )

    pressure = (
        imbalance.abs()
        * logC
    )

    beta = rolling_beta_with_intercept(
        pressure,
        ret.abs(),
        cfg.primary_window,
        cfg.min_periods,
        cfg.eps
    )

    IR = (
        1.0
        /
        (beta + cfg.eps)
    )


    # --------------------------------------------
    # Stress
    # --------------------------------------------

    zR = robust_z_causal(
        R,
        cfg.primary_window,
        cfg.min_periods,
        cfg.eps
    )

    zL = robust_z_causal(
        L,
        cfg.primary_window,
        cfg.min_periods,
        cfg.eps
    )

    zRet = robust_z_causal(
        ret.abs(),
        cfg.primary_window,
        cfg.min_periods,
        cfg.eps
    )

    STRESS = (
        zR
        + zL
        + zRet
    )


    threshold = rolling_stress_threshold(
        STRESS,
        cfg.primary_window,
        cfg.min_periods,
        cfg.stress_quantile
    )


    # --------------------------------------------
    # Survival
    # --------------------------------------------

    SSR = conditional_rolling_median_ratio(
        C,
        STRESS,
        threshold,
        cfg.primary_window,
        cfg.min_periods,
        cfg.eps
    )

    SSR_S = conditional_rolling_median_ratio(
        S,
        STRESS,
        threshold,
        cfg.primary_window,
        cfg.min_periods,
        cfg.eps
    )


    # --------------------------------------------
    # Average sell per trade
    # --------------------------------------------

    AST_S = (
        S
        /
        (C + cfg.eps)
    )


    # --------------------------------------------
    # Auditoría
    # --------------------------------------------

    # FLOW_TOTAL = B + S

    # TURNOVER_PER_TRADE = (
    #     FLOW_TOTAL
    #     /
    #     (C + cfg.eps)
    # )


    blocks.extend([
        name_block(IR, "IR", cfg),
        name_block(STRESS, "STRESS", cfg),
        name_block(SSR, "SSR", cfg),
        name_block(SSR_S, "SSR_S", cfg),
        name_block(AST_S, "AST_S", cfg),

        # name_block(
        #     FLOW_TOTAL,
        #     "FLOW_TOTAL_AUDIT",
        #     cfg
        # ),

        # name_block(
        #     TURNOVER_PER_TRADE,
        #     "TURNOVER_PER_TRADE_AUDIT",
        #     cfg
        # ),
    ])


df = merge_blocks(
    df,
    blocks
)

### 5 checkpoint: Economia Computacional

In [ ]:
ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

archivo_salida = ruta + "112024-122025_clean_add.parquet"

df.to_parquet(archivo_salida, index=False)

print(f"Guardado en: {archivo_salida}")

Guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025_clean_add.parquet

***APERTURA***

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
df = pd.read_parquet('/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025_clean_add.parquet')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 20918 entries, bar_end to 币安人生__TURNOVER_PER_TRADE_AUDIT
dtypes: datetime64[ns, UTC](1), float32(19897), int8(1020)
memory usage: 9.9 GB

In [4]:
conteo_tipos = df.dtypes.astype(str).value_counts().rename_axis("dtype").reset_index(name="cantidad")
display(conteo_tipos)

                 dtype  cantidad
0              float32     19897
1                 int8      1020
2  datetime64[ns, UTC]         1

In [5]:
df[df.select_dtypes(include="float64").columns] = df.select_dtypes(include="float64").astype("float32")

In [6]:
df.dtypes.value_counts()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 20918 entries, bar_end to 币安人生__TURNOVER_PER_TRADE_AUDIT
dtypes: datetime64[ns, UTC](1), float32(19897), int8(1020)
memory usage: 9.9 GB

### Corte Vertical df

Despues de un breve analisis visual se cree conveniente hacer un primer intento con 3 cortes cuasi simetricos en el df por razones de limitacion en el software. Los cortes seran:

- Dataset completo: df: 01/11/2024 - 2026/02/01; 131.616 Datos
- Dataset c1: df_c1: 01/11/2024 - 2025/04/02; 43.824 Datos.
- Dataset c2: df_c2: 2025/04/02 - 2025/09/01; 43.824 Datos.
- Dataset c3: df_c3: 2025/09/01 - 2026/02/01; 43.825 Datos.

In [7]:
df["bar_end"] = pd.to_datetime(df["bar_end"])

df_c1 = df[(df["bar_end"] >= "2024-11-01") & (df["bar_end"] < "2025-04-02")].copy()
df_c2 = df[(df["bar_end"] >= "2025-04-02") & (df["bar_end"] < "2025-09-01")].copy()
df_c3 = df[(df["bar_end"] >= "2025-09-01") & (df["bar_end"] < "2026-02-01")].copy()

for name, x in {"df": df, "df_c1": df_c1, "df_c2": df_c2, "df_c3": df_c3}.items():
    print(
        f"{name}: {len(x):,} filas | "
        f"{x['bar_end'].min()} → {x['bar_end'].max()}"
    )

df: 131,616 filas | 2024-11-01 00:05:00+00:00 → 2026-02-01 00:00:00+00:00
df_c1: 43,775 filas | 2024-11-01 00:05:00+00:00 → 2025-04-01 23:55:00+00:00
df_c2: 43,776 filas | 2025-04-02 00:00:00+00:00 → 2025-08-31 23:55:00+00:00
df_c3: 44,064 filas | 2025-09-01 00:00:00+00:00 → 2026-01-31 23:55:00+00:00

In [43]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43775 entries, 0 to 43774
Columns: 27038 entries, bar_end to 币安人生__NRET
dtypes: datetime64[ns, UTC](1), float32(26017), int8(1020)
memory usage: 4.3 GB
<class 'pandas.core.frame.DataFrame'>
Index: 43776 entries, 43775 to 87550
Columns: 27038 entries, bar_end to 币安人生__NRET
dtypes: datetime64[ns, UTC](1), float32(26017), int8(1020)
memory usage: 4.3 GB
<class 'pandas.core.frame.DataFrame'>
Index: 44064 entries, 87551 to 131614
Columns: 27038 entries, bar_end to 币安人生__NRET
dtypes: datetime64[ns, UTC](1), float32(26017), int8(1020)
memory usage: 4.3 GB

###### 6 checkpoint

In [9]:
ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

archivos = {
    "df":    "112024-012026_clean_add.parquet",
    "df_c1": "112024-042025_clean_add.parquet",
    "df_c2": "042025-092025_clean_add.parquet",
    "df_c3": "092025-022026_clean_add.parquet",
}

for nombre, archivo in archivos.items():
    archivo_salida = ruta + archivo
    globals()[nombre].to_parquet(archivo_salida, index=False)
    print(f"{nombre} guardado en: {archivo_salida}")

df guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-012026_clean_add.parquet
df_c1 guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add.parquet
df_c2 guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add.parquet
df_c3 guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add.parquet

***APERTURA***

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

In [ ]:
ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

df_c1 = pd.read_parquet(ruta + "112024-042025_clean_add.parquet")
df_c2 = pd.read_parquet(ruta + "042025-092025_clean_add.parquet")
df_c3 = pd.read_parquet(ruta + "092025-022026_clean_add.parquet")

In [10]:
df_c1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43775 entries, 0 to 43774
Columns: 20918 entries, bar_end to 币安人生__TURNOVER_PER_TRADE_AUDIT
dtypes: datetime64[ns, UTC](1), float32(19897), int8(1020)
memory usage: 3.3 GB

In [11]:
from numba import njit, prange

In [12]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# DATASET DE TRABAJO
# ============================================================

DATASET = df_c1


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    primary_window: int = 288
    min_periods: int = 72
    ewm_span: int = 72

    multiscale_windows: tuple[int, ...] = (
        3,
        12,
        72,
        288,
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):

    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

@njit(parallel=True)
def _recovery_speed_numba(
    g,
    s,
    q,
    b,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    T, N = g.shape
    output = np.full((T, N), np.nan, dtype=np.float64)

    for j in prange(N):
        in_event = False
        event_start = -1
        event_baseline = np.nan
        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):
            if not in_event:
                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):
                    in_event = True
                    event_start = t
                    event_baseline = b[t, j]
                    consecutive = 0

            elif np.isfinite(g[t, j]):
                distance = abs(g[t, j] - event_baseline) / (
                    abs(event_baseline) + eps
                )

                if distance <= tolerance:
                    consecutive += 1
                else:
                    consecutive = 0

                if consecutive >= hold_bars:
                    recovery_start = t - hold_bars + 1
                    duration = max(1, recovery_start - event_start)

                    if np.isnan(duration_ewma):
                        duration_ewma = float(duration)
                    else:
                        duration_ewma = (
                            alpha * duration
                            + (1.0 - alpha) * duration_ewma
                        )

                    in_event = False
                    event_start = -1
                    event_baseline = np.nan
                    consecutive = 0

            if np.isfinite(duration_ewma):
                output[t, j] = 1.0 / (1.0 + duration_ewma)

    return output


def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    frames = (stress, stress_threshold, baseline)

    if any(
        not gp0.index.equals(x.index)
        or not gp0.columns.equals(x.columns)
        for x in frames
    ):
        raise ValueError(
            "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
        )

    output = _recovery_speed_numba(
        gp0.to_numpy(dtype=np.float64, copy=False),
        stress.to_numpy(dtype=np.float64, copy=False),
        stress_threshold.to_numpy(dtype=np.float64, copy=False),
        baseline.to_numpy(dtype=np.float64, copy=False),
        tolerance,
        hold_bars,
        alpha,
        eps,
    )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns,
    )

# ============================================================
# INICIALIZACIÓN
# ============================================================

DATASET = validate_time(DATASET, cfg)

assets = discover_assets(
    DATASET,
    cfg
)

print("Dataset:", DATASET.shape)
print("Activos detectados:", len(assets))

Dataset: (43775, 20918)
Activos detectados: 510

In [13]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# DATASET DE TRABAJO
# ============================================================

DATASET = df_c2


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    primary_window: int = 288
    min_periods: int = 72
    ewm_span: int = 72

    multiscale_windows: tuple[int, ...] = (
        3,
        12,
        72,
        288,
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):

    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

@njit(parallel=True)
def _recovery_speed_numba(
    g,
    s,
    q,
    b,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    T, N = g.shape
    output = np.full((T, N), np.nan, dtype=np.float64)

    for j in prange(N):
        in_event = False
        event_start = -1
        event_baseline = np.nan
        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):
            if not in_event:
                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):
                    in_event = True
                    event_start = t
                    event_baseline = b[t, j]
                    consecutive = 0

            elif np.isfinite(g[t, j]):
                distance = abs(g[t, j] - event_baseline) / (
                    abs(event_baseline) + eps
                )

                if distance <= tolerance:
                    consecutive += 1
                else:
                    consecutive = 0

                if consecutive >= hold_bars:
                    recovery_start = t - hold_bars + 1
                    duration = max(1, recovery_start - event_start)

                    if np.isnan(duration_ewma):
                        duration_ewma = float(duration)
                    else:
                        duration_ewma = (
                            alpha * duration
                            + (1.0 - alpha) * duration_ewma
                        )

                    in_event = False
                    event_start = -1
                    event_baseline = np.nan
                    consecutive = 0

            if np.isfinite(duration_ewma):
                output[t, j] = 1.0 / (1.0 + duration_ewma)

    return output


def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    frames = (stress, stress_threshold, baseline)

    if any(
        not gp0.index.equals(x.index)
        or not gp0.columns.equals(x.columns)
        for x in frames
    ):
        raise ValueError(
            "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
        )

    output = _recovery_speed_numba(
        gp0.to_numpy(dtype=np.float64, copy=False),
        stress.to_numpy(dtype=np.float64, copy=False),
        stress_threshold.to_numpy(dtype=np.float64, copy=False),
        baseline.to_numpy(dtype=np.float64, copy=False),
        tolerance,
        hold_bars,
        alpha,
        eps,
    )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns,
    )

# ============================================================
# INICIALIZACIÓN
# ============================================================

DATASET = validate_time(DATASET, cfg)

assets = discover_assets(
    DATASET,
    cfg
)

print("Dataset:", DATASET.shape)
print("Activos detectados:", len(assets))

Dataset: (43776, 20918)
Activos detectados: 510

In [14]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# DATASET DE TRABAJO
# ============================================================

DATASET = df_c3


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    primary_window: int = 288
    min_periods: int = 72
    ewm_span: int = 72

    multiscale_windows: tuple[int, ...] = (
        3,
        12,
        72,
        288,
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):

    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

@njit(parallel=True)
def _recovery_speed_numba(
    g,
    s,
    q,
    b,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    T, N = g.shape
    output = np.full((T, N), np.nan, dtype=np.float64)

    for j in prange(N):
        in_event = False
        event_start = -1
        event_baseline = np.nan
        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):
            if not in_event:
                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):
                    in_event = True
                    event_start = t
                    event_baseline = b[t, j]
                    consecutive = 0

            elif np.isfinite(g[t, j]):
                distance = abs(g[t, j] - event_baseline) / (
                    abs(event_baseline) + eps
                )

                if distance <= tolerance:
                    consecutive += 1
                else:
                    consecutive = 0

                if consecutive >= hold_bars:
                    recovery_start = t - hold_bars + 1
                    duration = max(1, recovery_start - event_start)

                    if np.isnan(duration_ewma):
                        duration_ewma = float(duration)
                    else:
                        duration_ewma = (
                            alpha * duration
                            + (1.0 - alpha) * duration_ewma
                        )

                    in_event = False
                    event_start = -1
                    event_baseline = np.nan
                    consecutive = 0

            if np.isfinite(duration_ewma):
                output[t, j] = 1.0 / (1.0 + duration_ewma)

    return output


def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    frames = (stress, stress_threshold, baseline)

    if any(
        not gp0.index.equals(x.index)
        or not gp0.columns.equals(x.columns)
        for x in frames
    ):
        raise ValueError(
            "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
        )

    output = _recovery_speed_numba(
        gp0.to_numpy(dtype=np.float64, copy=False),
        stress.to_numpy(dtype=np.float64, copy=False),
        stress_threshold.to_numpy(dtype=np.float64, copy=False),
        baseline.to_numpy(dtype=np.float64, copy=False),
        tolerance,
        hold_bars,
        alpha,
        eps,
    )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns,
    )

# ============================================================
# INICIALIZACIÓN
# ============================================================

DATASET = validate_time(DATASET, cfg)

assets = discover_assets(
    DATASET,
    cfg
)

print("Dataset:", DATASET.shape)
print("Activos detectados:", len(assets))

Dataset: (44064, 20918)
Activos detectados: 510

##7. gp(0), Recovery y gp

- gp(0)

gp(0) = softplus[fg((
    "TI",
    "CA",
    "VSTAB",
    "PERS_C",
    "BIL",
    "ABS",
    "RLIQ",
    "IR",
    "SSR",
))]

Resumir resistenica intrisica

- REC es calculada a partir del STRESS

- gp es gp(0) y como se reconfigura despues del estres

In [36]:
from pathlib import Path
import os
import gc


# ============================================================
# DATASETS DE TRABAJO
# ============================================================

DATASETS = {
    "df_c1": df_c1,
    "df_c2": df_c2,
    "df_c3": df_c3,
}


# ============================================================
# ARCHIVOS DE SALIDA
# ============================================================

ruta = Path(
    "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"
)

OUTPUTS = {
    "df_c1": ruta / "112024-042025_clean_add_gp.parquet",
    "df_c2": ruta / "042025-092025_clean_add_gp.parquet",
    "df_c3": ruta / "092025-022026_clean_add_gp.parquet",
}


# ============================================================
# INPUTS gp0
# ============================================================

gp0_inputs = (
    "TI",
    "CA",
    "VSTAB",
    "PERS_C",
    "BIL",
    "ABS",
    "RLIQ",
    "IR",
    "SSR",
)


# ============================================================
# CONTROL DE PROCESO
# ============================================================

saved_files = []
completed_datasets = []
current_dataset = None
current_chunk = 0
total_chunks = 0


try:

    for dataset_name in DATASETS:

        current_dataset = dataset_name
        DATASET = DATASETS[dataset_name]

        asset_chunks = list(
            chunks(
                assets,
                cfg.asset_block_size
            )
        )

        total_chunks = len(asset_chunks)
        current_chunk = 0

        print("\n" + "=" * 70)
        print(
            f"{dataset_name} | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas | "
            f"{total_chunks} chunks"
        )
        print("=" * 70)


        for i, chunk in enumerate(
            asset_chunks,
            start=1
        ):

            # ====================================================
            # CÁLCULO DEL CHUNK
            # ====================================================

            components = [
                load_feature(
                    DATASET,
                    chunk,
                    feature
                )
                for feature in gp0_inputs
            ]


            # --------------------------------------------
            # gp inicial
            # --------------------------------------------

            gp0 = composite_positive_proxy(
                components,
                cfg
            )


            # --------------------------------------------
            # Recovery
            # --------------------------------------------

            STRESS = load_feature(
                DATASET,
                chunk,
                "STRESS"
            )

            threshold = rolling_stress_threshold(
                STRESS,
                cfg.primary_window,
                cfg.min_periods,
                cfg.stress_quantile
            )

            baseline = (
                gp0
                .shift(1)
                .rolling(
                    cfg.primary_window,
                    min_periods=cfg.min_periods
                )
                .median()
            )

            REC = recovery_speed_causal(
                gp0=gp0,
                stress=STRESS,
                stress_threshold=threshold,
                baseline=baseline,
                tolerance=cfg.recovery_tolerance,
                hold_bars=cfg.recovery_hold_bars,
                alpha=cfg.recovery_event_ewm_alpha,
                eps=cfg.eps
            )


            # --------------------------------------------
            # gp refinado
            # --------------------------------------------

            gp = composite_positive_proxy(
                components + [REC],
                cfg
            )


            # ====================================================
            # COMMIT DEL CHUNK
            # Solo se ejecuta si TODO el chunk terminó correctamente
            # ====================================================

            chunk_blocks = [
                name_block(gp0, "gp0", cfg),
                name_block(REC, "REC", cfg),
                name_block(gp, "gp", cfg),
            ]

            DATASET = merge_blocks(
                DATASET,
                chunk_blocks
            )

            DATASETS[dataset_name] = DATASET
            globals()[dataset_name] = DATASET

            current_chunk = i

            print(
                f"{dataset_name} | "
                f"chunk {i:02d}/{total_chunks} OK | "
                f"{len(chunk):02d} activos | "
                f"{DATASET.shape[1]:,} columnas"
            )

            del (
                components,
                gp0,
                STRESS,
                threshold,
                baseline,
                REC,
                gp,
                chunk_blocks,
            )

            gc.collect()


        # ========================================================
        # GUARDADO DEL DATASET COMPLETO
        # ========================================================

        output_file = OUTPUTS[dataset_name]
        temp_file = output_file.with_suffix(".tmp.parquet")

        DATASET.to_parquet(
            temp_file,
            index=False
        )

        os.replace(
            temp_file,
            output_file
        )

        saved_files.append(str(output_file))
        completed_datasets.append(dataset_name)

        print(
            f"\n{dataset_name} COMPLETO | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas"
        )

        print(
            f"Guardado: {output_file}"
        )


except KeyboardInterrupt:

    print("\nPROCESO INTERRUMPIDO MANUALMENTE")

except Exception as e:

    print(
        f"\nERROR: {type(e).__name__}: {e}"
    )

finally:

    # ============================================================
    # ESTADO FINAL
    # ============================================================

    print("\n" + "=" * 70)
    print("ESTADO FINAL")
    print("=" * 70)

    if current_dataset is not None:
        print(
            f"Último proceso: {current_dataset} | "
            f"chunks confirmados: {current_chunk}/{total_chunks}"
        )

    if completed_datasets:
        print(
            "\nDatasets completados:",
            ", ".join(completed_datasets)
        )
    else:
        print("\nDatasets completados: ninguno")

    if saved_files:
        print("\nArchivos guardados exitosamente:")
        for file in saved_files:
            print(f"  ✓ {file}")
    else:
        print("\nArchivos completos guardados: ninguno")

======================================================================
df_c1 | 43,775 filas × 20,918 columnas | 16 chunks
======================================================================

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 01/16 OK | 32 activos | 21,014 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 02/16 OK | 32 activos | 21,110 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 03/16 OK | 32 activos | 21,206 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 04/16 OK | 32 activos | 21,302 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 05/16 OK | 32 activos | 21,398 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 06/16 OK | 32 activos | 21,494 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 07/16 OK | 32 activos | 21,590 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 08/16 OK | 32 activos | 21,686 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 09/16 OK | 32 activos | 21,782 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 10/16 OK | 32 activos | 21,878 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 11/16 OK | 32 activos | 21,974 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 12/16 OK | 32 activos | 22,070 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 13/16 OK | 32 activos | 22,166 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 14/16 OK | 32 activos | 22,262 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 15/16 OK | 32 activos | 22,358 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 16/16 OK | 30 activos | 22,448 columnas

df_c1 COMPLETO | 43,775 filas × 22,448 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_gp.parquet

======================================================================
df_c2 | 43,776 filas × 20,918 columnas | 16 chunks
======================================================================

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 01/16 OK | 32 activos | 21,014 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 02/16 OK | 32 activos | 21,110 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 03/16 OK | 32 activos | 21,206 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 04/16 OK | 32 activos | 21,302 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 05/16 OK | 32 activos | 21,398 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 06/16 OK | 32 activos | 21,494 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 07/16 OK | 32 activos | 21,590 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 08/16 OK | 32 activos | 21,686 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 09/16 OK | 32 activos | 21,782 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 10/16 OK | 32 activos | 21,878 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 11/16 OK | 32 activos | 21,974 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 12/16 OK | 32 activos | 22,070 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 13/16 OK | 32 activos | 22,166 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 14/16 OK | 32 activos | 22,262 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 15/16 OK | 32 activos | 22,358 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 16/16 OK | 30 activos | 22,448 columnas

df_c2 COMPLETO | 43,776 filas × 22,448 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_gp.parquet

======================================================================
df_c3 | 44,064 filas × 20,918 columnas | 16 chunks
======================================================================

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 01/16 OK | 32 activos | 21,014 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 02/16 OK | 32 activos | 21,110 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 03/16 OK | 32 activos | 21,206 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 04/16 OK | 32 activos | 21,302 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 05/16 OK | 32 activos | 21,398 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 06/16 OK | 32 activos | 21,494 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 07/16 OK | 32 activos | 21,590 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 08/16 OK | 32 activos | 21,686 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 09/16 OK | 32 activos | 21,782 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 10/16 OK | 32 activos | 21,878 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 11/16 OK | 32 activos | 21,974 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 12/16 OK | 32 activos | 22,070 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 13/16 OK | 32 activos | 22,166 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 14/16 OK | 32 activos | 22,262 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 15/16 OK | 32 activos | 22,358 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(
/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 16/16 OK | 30 activos | 22,448 columnas

df_c3 COMPLETO | 44,064 filas × 22,448 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_gp.parquet

======================================================================
ESTADO FINAL
======================================================================
Último proceso: df_c3 | chunks confirmados: 16/16

Datasets completados: df_c1, df_c2, df_c3

Archivos guardados exitosamente:
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_gp.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_gp.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_gp.parquet

In [38]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43775 entries, 0 to 43774
Columns: 22448 entries, bar_end to 币安人生__gp
dtypes: datetime64[ns, UTC](1), float32(21427), int8(1020)
memory usage: 3.5 GB
<class 'pandas.core.frame.DataFrame'>
Index: 43776 entries, 43775 to 87550
Columns: 22448 entries, bar_end to 币安人生__gp
dtypes: datetime64[ns, UTC](1), float32(21427), int8(1020)
memory usage: 3.5 GB
<class 'pandas.core.frame.DataFrame'>
Index: 44064 entries, 87551 to 131614
Columns: 22448 entries, bar_end to 币安人生__gp
dtypes: datetime64[ns, UTC](1), float32(21427), int8(1020)
memory usage: 3.6 GB

##8. gp multiescala y f(gp)
- familia gp_W: 3,12,72,288

GW= EWMAw(gp)

resistencia persistente a distintas escalas, Media movil con pesos

- fgp_nested

f(gp) = exp[SUMm(Wm*ln(GWm + epsilon))]
y SUM(Wm)=1

Resistencia estructural anidadad

In [39]:
from pathlib import Path
import os
import gc


# ============================================================
# DATASETS DE TRABAJO
# ============================================================

DATASETS = {
    "df_c1": df_c1,
    "df_c2": df_c2,
    "df_c3": df_c3,
}


# ============================================================
# ARCHIVOS DE SALIDA
# ============================================================

ruta = Path(
    "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"
)

OUTPUTS = {
    "df_c1": ruta / "112024-042025_clean_add_gp_fgp.parquet",
    "df_c2": ruta / "042025-092025_clean_add_gp_fgp.parquet",
    "df_c3": ruta / "092025-022026_clean_add_gp_fgp.parquet",
}


# ============================================================
# CONTROL DE PROCESO
# ============================================================

saved_files = []
completed_datasets = []

current_dataset = None
current_chunk = 0
total_chunks = 0


try:

    for dataset_name, DATASET in DATASETS.items():

        current_dataset = dataset_name

        asset_chunks = list(
            chunks(
                assets,
                cfg.asset_block_size
            )
        )

        total_chunks = len(asset_chunks)
        current_chunk = 0

        print("\n" + "=" * 70)
        print(
            f"{dataset_name} | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas | "
            f"{total_chunks} chunks"
        )
        print("=" * 70)


        for i, chunk in enumerate(
            asset_chunks,
            start=1
        ):

            # ====================================================
            # CÁLCULO DEL CHUNK
            # ====================================================

            gp = load_feature(
                DATASET,
                chunk,
                "gp"
            )

            G = {}

            chunk_blocks = []


            for w in cfg.multiscale_windows:

                G[w] = (
                    gp
                    .ewm(
                        span=w,
                        adjust=False,
                        min_periods=max(
                            2,
                            min(
                                w,
                                cfg.min_periods
                            )
                        )
                    )
                    .mean()
                )

                chunk_blocks.append(
                    name_block(
                        G[w],
                        f"gp_W{w}",
                        cfg
                    )
                )


            # --------------------------------------------
            # f(gp) anidado
            # media geométrica
            # --------------------------------------------

            sum_log = None

            for w in cfg.multiscale_windows:

                lg = np.log(
                    G[w].clip(
                        lower=cfg.eps
                    )
                )

                sum_log = (
                    lg
                    if sum_log is None
                    else sum_log + lg
                )


            fgp_nested = np.exp(
                sum_log
                / len(cfg.multiscale_windows)
            )


            chunk_blocks.append(
                name_block(
                    fgp_nested,
                    "fgp_nested",
                    cfg
                )
            )


            # ====================================================
            # COMMIT DEL CHUNK
            # Solo se ejecuta si TODO el chunk terminó correctamente
            # ====================================================

            DATASET = merge_blocks(
                DATASET,
                chunk_blocks
            )

            DATASETS[dataset_name] = DATASET
            globals()[dataset_name] = DATASET

            current_chunk = i

            print(
                f"{dataset_name} | "
                f"chunk {i:02d}/{total_chunks} OK | "
                f"{len(chunk):02d} activos | "
                f"{DATASET.shape[1]:,} columnas"
            )


            del (
                gp,
                G,
                sum_log,
                lg,
                fgp_nested,
                chunk_blocks,
            )

            gc.collect()


        # ========================================================
        # GUARDADO DEL DATASET COMPLETO
        # ========================================================

        output_file = OUTPUTS[dataset_name]
        temp_file = output_file.with_suffix(".tmp.parquet")

        DATASET.to_parquet(
            temp_file,
            index=False
        )

        os.replace(
            temp_file,
            output_file
        )

        saved_files.append(str(output_file))
        completed_datasets.append(dataset_name)

        print(
            f"\n{dataset_name} COMPLETO | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas"
        )

        print(
            f"Guardado: {output_file}"
        )


except KeyboardInterrupt:

    print("\nPROCESO INTERRUMPIDO MANUALMENTE")


except Exception as e:

    print(
        f"\nERROR: {type(e).__name__}: {e}"
    )


finally:

    # ============================================================
    # ESTADO FINAL
    # ============================================================

    print("\n" + "=" * 70)
    print("ESTADO FINAL")
    print("=" * 70)

    if current_dataset is not None:

        print(
            f"Último proceso: {current_dataset} | "
            f"chunks confirmados: "
            f"{current_chunk}/{total_chunks}"
        )

    if completed_datasets:

        print(
            "\nDatasets completados:",
            ", ".join(completed_datasets)
        )

    else:

        print(
            "\nDatasets completados: ninguno"
        )


    if saved_files:

        print(
            "\nArchivos guardados exitosamente:"
        )

        for file in saved_files:

            print(
                f"  ✓ {file}"
            )

    else:

        print(
            "\nArchivos completos guardados: ninguno"
        )

======================================================================
df_c1 | 43,775 filas × 22,448 columnas | 16 chunks
======================================================================
df_c1 | chunk 01/16 OK | 32 activos | 22,608 columnas
df_c1 | chunk 02/16 OK | 32 activos | 22,768 columnas
df_c1 | chunk 03/16 OK | 32 activos | 22,928 columnas
df_c1 | chunk 04/16 OK | 32 activos | 23,088 columnas
df_c1 | chunk 05/16 OK | 32 activos | 23,248 columnas
df_c1 | chunk 06/16 OK | 32 activos | 23,408 columnas
df_c1 | chunk 07/16 OK | 32 activos | 23,568 columnas
df_c1 | chunk 08/16 OK | 32 activos | 23,728 columnas
df_c1 | chunk 09/16 OK | 32 activos | 23,888 columnas
df_c1 | chunk 10/16 OK | 32 activos | 24,048 columnas
df_c1 | chunk 11/16 OK | 32 activos | 24,208 columnas
df_c1 | chunk 12/16 OK | 32 activos | 24,368 columnas
df_c1 | chunk 13/16 OK | 32 activos | 24,528 columnas
df_c1 | chunk 14/16 OK | 32 activos | 24,688 columnas
df_c1 | chunk 15/16 OK | 32 activos | 24,848 columnas
df_c1 | chunk 16/16 OK | 30 activos | 24,998 columnas

df_c1 COMPLETO | 43,775 filas × 24,998 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_gp_fgp.parquet

======================================================================
df_c2 | 43,776 filas × 22,448 columnas | 16 chunks
======================================================================
df_c2 | chunk 01/16 OK | 32 activos | 22,608 columnas
df_c2 | chunk 02/16 OK | 32 activos | 22,768 columnas
df_c2 | chunk 03/16 OK | 32 activos | 22,928 columnas
df_c2 | chunk 04/16 OK | 32 activos | 23,088 columnas
df_c2 | chunk 05/16 OK | 32 activos | 23,248 columnas
df_c2 | chunk 06/16 OK | 32 activos | 23,408 columnas
df_c2 | chunk 07/16 OK | 32 activos | 23,568 columnas
df_c2 | chunk 08/16 OK | 32 activos | 23,728 columnas
df_c2 | chunk 09/16 OK | 32 activos | 23,888 columnas
df_c2 | chunk 10/16 OK | 32 activos | 24,048 columnas
df_c2 | chunk 11/16 OK | 32 activos | 24,208 columnas
df_c2 | chunk 12/16 OK | 32 activos | 24,368 columnas
df_c2 | chunk 13/16 OK | 32 activos | 24,528 columnas
df_c2 | chunk 14/16 OK | 32 activos | 24,688 columnas
df_c2 | chunk 15/16 OK | 32 activos | 24,848 columnas
df_c2 | chunk 16/16 OK | 30 activos | 24,998 columnas

df_c2 COMPLETO | 43,776 filas × 24,998 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_gp_fgp.parquet

======================================================================
df_c3 | 44,064 filas × 22,448 columnas | 16 chunks
======================================================================
df_c3 | chunk 01/16 OK | 32 activos | 22,608 columnas
df_c3 | chunk 02/16 OK | 32 activos | 22,768 columnas
df_c3 | chunk 03/16 OK | 32 activos | 22,928 columnas
df_c3 | chunk 04/16 OK | 32 activos | 23,088 columnas
df_c3 | chunk 05/16 OK | 32 activos | 23,248 columnas
df_c3 | chunk 06/16 OK | 32 activos | 23,408 columnas
df_c3 | chunk 07/16 OK | 32 activos | 23,568 columnas
df_c3 | chunk 08/16 OK | 32 activos | 23,728 columnas
df_c3 | chunk 09/16 OK | 32 activos | 23,888 columnas
df_c3 | chunk 10/16 OK | 32 activos | 24,048 columnas
df_c3 | chunk 11/16 OK | 32 activos | 24,208 columnas
df_c3 | chunk 12/16 OK | 32 activos | 24,368 columnas
df_c3 | chunk 13/16 OK | 32 activos | 24,528 columnas
df_c3 | chunk 14/16 OK | 32 activos | 24,688 columnas
df_c3 | chunk 15/16 OK | 32 activos | 24,848 columnas
df_c3 | chunk 16/16 OK | 30 activos | 24,998 columnas

df_c3 COMPLETO | 44,064 filas × 24,998 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_gp_fgp.parquet

======================================================================
ESTADO FINAL
======================================================================
Último proceso: df_c3 | chunks confirmados: 16/16

Datasets completados: df_c1, df_c2, df_c3

Archivos guardados exitosamente:
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_gp_fgp.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_gp_fgp.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_gp_fgp.parquet

In [40]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43775 entries, 0 to 43774
Columns: 24998 entries, bar_end to 币安人生__fgp_nested
dtypes: datetime64[ns, UTC](1), float32(23977), int8(1020)
memory usage: 4.0 GB
<class 'pandas.core.frame.DataFrame'>
Index: 43776 entries, 43775 to 87550
Columns: 24998 entries, bar_end to 币安人生__fgp_nested
dtypes: datetime64[ns, UTC](1), float32(23977), int8(1020)
memory usage: 4.0 GB
<class 'pandas.core.frame.DataFrame'>
Index: 44064 entries, 87551 to 131614
Columns: 24998 entries, bar_end to 币安人生__fgp_nested
dtypes: datetime64[ns, UTC](1), float32(23977), int8(1020)
memory usage: 4.0 GB

##9. Estructura temporal de N

- Estabilidad de gp

NSTAB = exp(-MADw(df_ln(gp))

Persistencia de la resistencia

- Autocorrelacion gp

NPERS = AR(gp)


- Coherencia multiescala

NCOH = exp[-Var_W*(ln(GW))]

Consistencia de resistencia entre escalas

- Retencion de resistencia bajo shock

NRET = median(gp|stress)/median(gp)

Cuanto gp sobrevive dado un shock

In [41]:
from pathlib import Path
import os
import gc


# ============================================================
# DATASETS DE TRABAJO
# ============================================================

DATASETS = {
    "df_c1": df_c1,
    "df_c2": df_c2,
    "df_c3": df_c3,
}


# ============================================================
# ARCHIVOS DE SALIDA
# ============================================================

ruta = Path(
    "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"
)

OUTPUTS = {
    "df_c1": ruta / "112024-042025_clean_add_gp_fgp_nmetrics.parquet",
    "df_c2": ruta / "042025-092025_clean_add_gp_fgp_nmetrics.parquet",
    "df_c3": ruta / "092025-022026_clean_add_gp_fgp_nmetrics.parquet",
}


# ============================================================
# CONTROL DE PROCESO
# ============================================================

saved_files = []
completed_datasets = []

current_dataset = None
current_chunk = 0
total_chunks = 0


try:

    for dataset_name, DATASET in DATASETS.items():

        current_dataset = dataset_name

        asset_chunks = list(
            chunks(
                assets,
                cfg.asset_block_size
            )
        )

        total_chunks = len(asset_chunks)
        current_chunk = 0

        print("\n" + "=" * 70)
        print(
            f"{dataset_name} | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas | "
            f"{total_chunks} chunks"
        )
        print("=" * 70)


        for i, chunk in enumerate(
            asset_chunks,
            start=1
        ):

            # ====================================================
            # CÁLCULO DEL CHUNK
            # ====================================================

            gp = load_feature(
                DATASET,
                chunk,
                "gp"
            )


            # --------------------------------------------
            # Estabilidad gp
            # --------------------------------------------

            dlog_gp = (
                np.log(
                    gp.clip(
                        lower=cfg.eps
                    )
                )
                .diff()
            )

            gp_dispersion = (
                rolling_robust_dispersion(
                    dlog_gp,
                    cfg.primary_window,
                    cfg.min_periods,
                    cfg.eps
                )
            )

            NSTAB = np.exp(
                -gp_dispersion
            )


            # --------------------------------------------
            # Persistencia gp
            # --------------------------------------------

            NPERS = rolling_autocorr_lag1(
                gp,
                cfg.primary_window,
                cfg.min_periods
            )


            # --------------------------------------------
            # Coherencia multiescala
            # --------------------------------------------

            logs = []

            for w in cfg.multiscale_windows:

                G = load_feature(
                    DATASET,
                    chunk,
                    f"gp_W{w}"
                )

                logs.append(
                    np.log(
                        G.clip(
                            lower=cfg.eps
                        )
                    )
                )


            stack = np.stack(
                [
                    x.to_numpy()
                    for x in logs
                ],
                axis=2
            )

            variance = np.nanvar(
                stack,
                axis=2
            )

            NCOH = pd.DataFrame(
                np.exp(-variance),
                index=DATASET.index,
                columns=chunk
            )


            # --------------------------------------------
            # Retención bajo stress
            # --------------------------------------------

            STRESS = load_feature(
                DATASET,
                chunk,
                "STRESS"
            )

            threshold = rolling_stress_threshold(
                STRESS,
                cfg.primary_window,
                cfg.min_periods,
                cfg.stress_quantile
            )

            NRET = conditional_rolling_median_ratio(
                gp,
                STRESS,
                threshold,
                cfg.primary_window,
                cfg.min_periods,
                cfg.eps
            )


            # ====================================================
            # PREPARACIÓN DEL CHUNK
            # ====================================================

            chunk_blocks = [
                name_block(NSTAB, "NSTAB", cfg),
                name_block(NPERS, "NPERS", cfg),
                name_block(NCOH, "NCOH", cfg),
                name_block(NRET, "NRET", cfg),
            ]


            # ====================================================
            # COMMIT DEL CHUNK
            # Solo se ejecuta si TODO el chunk terminó correctamente
            # ====================================================

            DATASET = merge_blocks(
                DATASET,
                chunk_blocks
            )

            DATASETS[dataset_name] = DATASET
            globals()[dataset_name] = DATASET

            current_chunk = i

            print(
                f"{dataset_name} | "
                f"chunk {i:02d}/{total_chunks} OK | "
                f"{len(chunk):02d} activos | "
                f"{DATASET.shape[1]:,} columnas"
            )


            del (
                gp,
                dlog_gp,
                gp_dispersion,
                NSTAB,
                NPERS,
                logs,
                G,
                stack,
                variance,
                NCOH,
                STRESS,
                threshold,
                NRET,
                chunk_blocks,
            )

            gc.collect()


        # ========================================================
        # GUARDADO DEL DATASET COMPLETO
        # ========================================================

        output_file = OUTPUTS[dataset_name]
        temp_file = output_file.with_suffix(".tmp.parquet")

        DATASET.to_parquet(
            temp_file,
            index=False
        )

        os.replace(
            temp_file,
            output_file
        )

        saved_files.append(str(output_file))
        completed_datasets.append(dataset_name)

        print(
            f"\n{dataset_name} COMPLETO | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas"
        )

        print(
            f"Guardado: {output_file}"
        )


except KeyboardInterrupt:

    print("\nPROCESO INTERRUMPIDO MANUALMENTE")


except Exception as e:

    print(
        f"\nERROR: {type(e).__name__}: {e}"
    )


finally:

    # ============================================================
    # ESTADO FINAL
    # ============================================================

    print("\n" + "=" * 70)
    print("ESTADO FINAL")
    print("=" * 70)

    if current_dataset is not None:

        print(
            f"Último proceso: {current_dataset} | "
            f"chunks confirmados: "
            f"{current_chunk}/{total_chunks}"
        )


    if completed_datasets:

        print(
            "\nDatasets completados:",
            ", ".join(completed_datasets)
        )

    else:

        print(
            "\nDatasets completados: ninguno"
        )


    if saved_files:

        print(
            "\nArchivos guardados exitosamente:"
        )

        for file in saved_files:

            print(
                f"  ✓ {file}"
            )

    else:

        print(
            "\nArchivos completos guardados: ninguno"
        )

======================================================================
df_c1 | 43,775 filas × 24,998 columnas | 16 chunks
======================================================================

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 01/16 OK | 32 activos | 25,126 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 02/16 OK | 32 activos | 25,254 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 03/16 OK | 32 activos | 25,382 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 04/16 OK | 32 activos | 25,510 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 05/16 OK | 32 activos | 25,638 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 06/16 OK | 32 activos | 25,766 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 07/16 OK | 32 activos | 25,894 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 08/16 OK | 32 activos | 26,022 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 09/16 OK | 32 activos | 26,150 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 10/16 OK | 32 activos | 26,278 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 11/16 OK | 32 activos | 26,406 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 12/16 OK | 32 activos | 26,534 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 13/16 OK | 32 activos | 26,662 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 14/16 OK | 32 activos | 26,790 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 15/16 OK | 32 activos | 26,918 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | chunk 16/16 OK | 30 activos | 27,038 columnas

df_c1 COMPLETO | 43,775 filas × 27,038 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_gp_fgp_nmetrics.parquet

======================================================================
df_c2 | 43,776 filas × 24,998 columnas | 16 chunks
======================================================================

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 01/16 OK | 32 activos | 25,126 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 02/16 OK | 32 activos | 25,254 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 03/16 OK | 32 activos | 25,382 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 04/16 OK | 32 activos | 25,510 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 05/16 OK | 32 activos | 25,638 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 06/16 OK | 32 activos | 25,766 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 07/16 OK | 32 activos | 25,894 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 08/16 OK | 32 activos | 26,022 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 09/16 OK | 32 activos | 26,150 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 10/16 OK | 32 activos | 26,278 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 11/16 OK | 32 activos | 26,406 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 12/16 OK | 32 activos | 26,534 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 13/16 OK | 32 activos | 26,662 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 14/16 OK | 32 activos | 26,790 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 15/16 OK | 32 activos | 26,918 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | chunk 16/16 OK | 30 activos | 27,038 columnas

df_c2 COMPLETO | 43,776 filas × 27,038 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_gp_fgp_nmetrics.parquet

======================================================================
df_c3 | 44,064 filas × 24,998 columnas | 16 chunks
======================================================================

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 01/16 OK | 32 activos | 25,126 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 02/16 OK | 32 activos | 25,254 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 03/16 OK | 32 activos | 25,382 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 04/16 OK | 32 activos | 25,510 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 05/16 OK | 32 activos | 25,638 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 06/16 OK | 32 activos | 25,766 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 07/16 OK | 32 activos | 25,894 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 08/16 OK | 32 activos | 26,022 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 09/16 OK | 32 activos | 26,150 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 10/16 OK | 32 activos | 26,278 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 11/16 OK | 32 activos | 26,406 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 12/16 OK | 32 activos | 26,534 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 13/16 OK | 32 activos | 26,662 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 14/16 OK | 32 activos | 26,790 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 15/16 OK | 32 activos | 26,918 columnas

/tmp/ipykernel_13441/4210930640.py:155: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | chunk 16/16 OK | 30 activos | 27,038 columnas

df_c3 COMPLETO | 44,064 filas × 27,038 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_gp_fgp_nmetrics.parquet

======================================================================
ESTADO FINAL
======================================================================
Último proceso: df_c3 | chunks confirmados: 16/16

Datasets completados: df_c1, df_c2, df_c3

Archivos guardados exitosamente:
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_gp_fgp_nmetrics.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_gp_fgp_nmetrics.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_gp_fgp_nmetrics.parquet

In [44]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43775 entries, 0 to 43774
Columns: 27038 entries, bar_end to 币安人生__NRET
dtypes: datetime64[ns, UTC](1), float32(26017), int8(1020)
memory usage: 4.3 GB
<class 'pandas.core.frame.DataFrame'>
Index: 43776 entries, 43775 to 87550
Columns: 27038 entries, bar_end to 币安人生__NRET
dtypes: datetime64[ns, UTC](1), float32(26017), int8(1020)
memory usage: 4.3 GB
<class 'pandas.core.frame.DataFrame'>
Index: 44064 entries, 87551 to 131614
Columns: 27038 entries, bar_end to 币安人生__NRET
dtypes: datetime64[ns, UTC](1), float32(26017), int8(1020)
memory usage: 4.3 GB

#### 7 checkpoint

In [46]:
ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

archivos = {
    "df":    "112024-012026_clean_add.parquet",
    "df_c1": "112024-042025_clean_add.parquet",
    "df_c2": "042025-092025_clean_add.parquet",
    "df_c3": "092025-022026_clean_add.parquet",
}

for nombre, archivo in archivos.items():
    archivo_salida = ruta + archivo
    globals()[nombre].to_parquet(archivo_salida, index=False)
    print(f"{nombre} guardado en: {archivo_salida}")

df guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-012026_clean_add.parquet
df_c1 guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add.parquet
df_c2 guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add.parquet
df_c3 guardado en: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add.parquet

***APERTURA***

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')
# import pandas as pd

In [ ]:
# ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

# df_c1 = pd.read_parquet(ruta + "112024-042025_clean_add.parquet")
# df_c2 = pd.read_parquet(ruta + "042025-092025_clean_add.parquet")
# df_c3 = pd.read_parquet(ruta + "092025-022026_clean_add.parquet")

In [47]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43775 entries, 0 to 43774
Columns: 27038 entries, bar_end to 币安人生__NRET
dtypes: datetime64[ns, UTC](1), float32(26017), int8(1020)
memory usage: 4.3 GB
<class 'pandas.core.frame.DataFrame'>
Index: 43776 entries, 43775 to 87550
Columns: 27038 entries, bar_end to 币安人生__NRET
dtypes: datetime64[ns, UTC](1), float32(26017), int8(1020)
memory usage: 4.3 GB
<class 'pandas.core.frame.DataFrame'>
Index: 44064 entries, 87551 to 131614
Columns: 27038 entries, bar_end to 币安人生__NRET
dtypes: datetime64[ns, UTC](1), float32(26017), int8(1020)
memory usage: 4.3 GB

In [ ]:
# from numba import njit, prange

In [ ]:
# from __future__ import annotations

# from dataclasses import dataclass
# from typing import Sequence
# import warnings

# import numpy as np
# import pandas as pd


# # ============================================================
# # DATASET DE TRABAJO
# # ============================================================

# DATASET = df_c1


# # ============================================================
# # CONFIGURACIÓN
# # ============================================================

# @dataclass(frozen=True)
# class FeatureConfig:
#     time_col: str = "bar_end"
#     ys_col: str = "YS"

#     price_suffix: str = "USDT"
#     volume_suffix: str = "_v"
#     trades_suffix: str = "_activity_trades_proxy"
#     range_suffix: str = "_range_rel_proxy"
#     illiq_suffix: str = "_illiquidity_proxy"
#     active_suffix: str = "_active_trading"
#     observed_suffix: str = "_observed"
#     buy_suffix: str = "_taker_buy_usdt_proxy"
#     sell_suffix: str = "_taker_sell_usdt_proxy"
#     yp_suffix: str = "_yp"

#     primary_window: int = 288
#     min_periods: int = 72
#     ewm_span: int = 72

#     multiscale_windows: tuple[int, ...] = (
#         3,
#         12,
#         72,
#         288,
#     )

#     return_lag: int = 1

#     stress_quantile: float = 0.90

#     recovery_tolerance: float = 0.15
#     recovery_hold_bars: int = 3
#     recovery_event_ewm_alpha: float = 0.20

#     eps: float = 1e-12
#     dtype: str = "float32"

#     asset_block_size: int = 32


# cfg = FeatureConfig()


# # ============================================================
# # TIEMPO
# # ============================================================

# def validate_time(df, cfg):
#     df = df.copy()

#     df[cfg.time_col] = pd.to_datetime(
#         df[cfg.time_col],
#         utc=True,
#         errors="raise"
#     )

#     df = (
#         df.sort_values(cfg.time_col)
#           .reset_index(drop=True)
#     )

#     if df[cfg.time_col].duplicated().any():
#         raise ValueError("Existen timestamps duplicados.")

#     delta = df[cfg.time_col].diff().dropna()

#     expected = pd.Timedelta(minutes=5)

#     if not delta.eq(expected).all():
#         raise ValueError(
#             "La serie no posee una grilla estricta de 5 minutos."
#         )

#     return df


# # ============================================================
# # ACTIVOS
# # ============================================================

# def discover_assets(df, cfg):

#     price_cols = [
#         c for c in df.columns
#         if c.endswith(cfg.price_suffix)
#         and "_" not in c
#     ]

#     candidates = sorted(
#         c[:-len(cfg.price_suffix)]
#         for c in price_cols
#     )

#     required_suffixes = (
#         cfg.volume_suffix,
#         cfg.trades_suffix,
#         cfg.range_suffix,
#         cfg.illiq_suffix,
#         cfg.active_suffix,
#         cfg.observed_suffix,
#         cfg.buy_suffix,
#         cfg.sell_suffix,
#         cfg.yp_suffix,
#     )

#     assets = []

#     for asset in candidates:

#         if all(
#             f"{asset}{suffix}" in df.columns
#             for suffix in required_suffixes
#         ):
#             assets.append(asset)

#     if len(assets) != 510:
#         warnings.warn(
#             f"Se detectaron {len(assets)} activos completos."
#         )

#     return assets


# def chunks(seq, size):
#     for start in range(0, len(seq), size):
#         yield list(seq[start:start + size])


# # ============================================================
# # NOMBRES
# # ============================================================

# def base_col(asset, kind, cfg):

#     if kind == "P":
#         return f"{asset}{cfg.price_suffix}"

#     suffix = {
#         "V": cfg.volume_suffix,
#         "C": cfg.trades_suffix,
#         "R": cfg.range_suffix,
#         "L": cfg.illiq_suffix,
#         "A": cfg.active_suffix,
#         "O": cfg.observed_suffix,
#         "B": cfg.buy_suffix,
#         "S": cfg.sell_suffix,
#         "yp": cfg.yp_suffix,
#     }[kind]

#     return f"{asset}{suffix}"


# def feat_col(asset, feature):
#     return f"{asset}__{feature}"


# # ============================================================
# # CARGA POR BLOQUES
# # ============================================================

# def load_base(df, assets, kind, cfg):

#     cols = [
#         base_col(a, kind, cfg)
#         for a in assets
#     ]

#     out = df.loc[:, cols].astype(
#         "float64",
#         copy=False
#     )

#     out.columns = assets

#     return out


# def load_feature(df, assets, feature):

#     cols = [
#         feat_col(a, feature)
#         for a in assets
#     ]

#     out = df.loc[:, cols].astype(
#         "float64",
#         copy=False
#     )

#     out.columns = assets

#     return out


# def name_block(x, feature, cfg):

#     out = x.astype(
#         cfg.dtype,
#         copy=False
#     )

#     out.columns = [
#         feat_col(a, feature)
#         for a in out.columns
#     ]

#     return out


# def merge_blocks(df, blocks):

#     block = pd.concat(
#         blocks,
#         axis=1,
#         copy=False
#     )

#     overlap = df.columns.intersection(
#         block.columns
#     )

#     if len(overlap):
#         df = df.drop(columns=list(overlap))

#     return pd.concat(
#         [df, block],
#         axis=1,
#         copy=False
#     )


# # ============================================================
# # ROBUST Z CAUSAL
# # ============================================================

# def robust_z_causal(
#     x,
#     window,
#     min_periods,
#     eps
# ):

#     hist = x.shift(1)

#     roll = hist.rolling(
#         window=window,
#         min_periods=min_periods
#     )

#     median = roll.median()

#     q25 = roll.quantile(0.25)
#     q75 = roll.quantile(0.75)

#     scale = (
#         q75 - q25
#     ) / 1.349

#     return (
#         x - median
#     ) / (
#         scale + eps
#     )


# # ============================================================
# # DISPERSIÓN ROBUSTA
# # ============================================================

# def rolling_robust_dispersion(
#     x,
#     window,
#     min_periods,
#     eps
# ):

#     roll = x.rolling(
#         window=window,
#         min_periods=min_periods
#     )

#     q25 = roll.quantile(0.25)
#     q75 = roll.quantile(0.75)

#     return (
#         (q75 - q25) / 1.349
#         + eps
#     )


# # ============================================================
# # AUTOCORRELACIÓN ROLLING
# # ============================================================

# def rolling_autocorr_lag1(
#     x,
#     window,
#     min_periods
# ):

#     lag = x.shift(1)

#     result = {}

#     for col in x.columns:
#         result[col] = (
#             x[col]
#             .rolling(
#                 window=window,
#                 min_periods=min_periods
#             )
#             .corr(lag[col])
#         )

#     return pd.DataFrame(
#         result,
#         index=x.index
#     )


# # ============================================================
# # BETA ROLLING
# # ============================================================

# def rolling_beta_with_intercept(
#     x,
#     y,
#     window,
#     min_periods,
#     eps
# ):

#     rx = x.rolling(
#         window,
#         min_periods=min_periods
#     )

#     ry = y.rolling(
#         window,
#         min_periods=min_periods
#     )

#     ex = rx.mean()
#     ey = ry.mean()

#     exy = (
#         (x * y)
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .mean()
#     )

#     ex2 = (
#         (x * x)
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .mean()
#     )

#     cov_xy = exy - ex * ey
#     var_x = ex2 - ex * ex

#     beta = (
#         cov_xy
#         / (var_x + eps)
#     )

#     return beta.clip(lower=0.0)


# # ============================================================
# # STRESS
# # ============================================================

# def rolling_stress_threshold(
#     stress,
#     window,
#     min_periods,
#     q
# ):

#     return (
#         stress
#         .shift(1)
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .quantile(q)
#     )


# def conditional_rolling_median_ratio(
#     value,
#     stress,
#     threshold,
#     window,
#     min_periods,
#     eps
# ):

#     is_stress = (
#         stress > threshold
#     )

#     numerator = (
#         value
#         .where(is_stress)
#         .rolling(
#             window,
#             min_periods=max(
#                 5,
#                 min_periods // 10
#             )
#         )
#         .median()
#     )

#     denominator = (
#         value
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .median()
#     )

#     return (
#         numerator
#         / (denominator + eps)
#     )


# # ============================================================
# # PROXY POSITIVO LATENTE
# # ============================================================

# def softplus_df(x):

#     values = np.logaddexp(
#         0.0,
#         x.to_numpy(
#             dtype=np.float64,
#             copy=False
#         )
#     )

#     return pd.DataFrame(
#         values,
#         index=x.index,
#         columns=x.columns
#     )


# def composite_positive_proxy(
#     components,
#     cfg
# ):

#     total = None
#     count = None

#     for component in components:

#         z = robust_z_causal(
#             component,
#             cfg.primary_window,
#             cfg.min_periods,
#             cfg.eps
#         )

#         valid = z.notna()

#         if total is None:

#             total = z.fillna(0.0)

#             count = valid.astype(
#                 "float64"
#             )

#         else:

#             total += z.fillna(0.0)

#             count += valid.astype(
#                 "float64"
#             )

#     score = (
#         total
#         / count.replace(0.0, np.nan)
#     )

#     return softplus_df(score)


# # ============================================================
# # RECOVERY SPEED CAUSAL
# # ============================================================

# @njit(parallel=True)
# def _recovery_speed_numba(
#     g,
#     s,
#     q,
#     b,
#     tolerance,
#     hold_bars,
#     alpha,
#     eps
# ):
#     T, N = g.shape
#     output = np.full((T, N), np.nan, dtype=np.float64)

#     for j in prange(N):
#         in_event = False
#         event_start = -1
#         event_baseline = np.nan
#         consecutive = 0
#         duration_ewma = np.nan

#         for t in range(T):
#             if not in_event:
#                 if (
#                     np.isfinite(s[t, j])
#                     and np.isfinite(q[t, j])
#                     and np.isfinite(b[t, j])
#                     and s[t, j] > q[t, j]
#                     and abs(b[t, j]) > eps
#                 ):
#                     in_event = True
#                     event_start = t
#                     event_baseline = b[t, j]
#                     consecutive = 0

#             elif np.isfinite(g[t, j]):
#                 distance = abs(g[t, j] - event_baseline) / (
#                     abs(event_baseline) + eps
#                 )

#                 if distance <= tolerance:
#                     consecutive += 1
#                 else:
#                     consecutive = 0

#                 if consecutive >= hold_bars:
#                     recovery_start = t - hold_bars + 1
#                     duration = max(1, recovery_start - event_start)

#                     if np.isnan(duration_ewma):
#                         duration_ewma = float(duration)
#                     else:
#                         duration_ewma = (
#                             alpha * duration
#                             + (1.0 - alpha) * duration_ewma
#                         )

#                     in_event = False
#                     event_start = -1
#                     event_baseline = np.nan
#                     consecutive = 0

#             if np.isfinite(duration_ewma):
#                 output[t, j] = 1.0 / (1.0 + duration_ewma)

#     return output


# def recovery_speed_causal(
#     gp0,
#     stress,
#     stress_threshold,
#     baseline,
#     tolerance,
#     hold_bars,
#     alpha,
#     eps
# ):
#     frames = (stress, stress_threshold, baseline)

#     if any(
#         not gp0.index.equals(x.index)
#         or not gp0.columns.equals(x.columns)
#         for x in frames
#     ):
#         raise ValueError(
#             "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
#         )

#     output = _recovery_speed_numba(
#         gp0.to_numpy(dtype=np.float64, copy=False),
#         stress.to_numpy(dtype=np.float64, copy=False),
#         stress_threshold.to_numpy(dtype=np.float64, copy=False),
#         baseline.to_numpy(dtype=np.float64, copy=False),
#         tolerance,
#         hold_bars,
#         alpha,
#         eps,
#     )

#     return pd.DataFrame(
#         output,
#         index=gp0.index,
#         columns=gp0.columns,
#     )

# # ============================================================
# # INICIALIZACIÓN
# # ============================================================

# DATASET = validate_time(DATASET, cfg)

# assets = discover_assets(
#     DATASET,
#     cfg
# )

# print("Dataset:", DATASET.shape)
# print("Activos detectados:", len(assets))

Dataset: (43775, 20918)
Activos detectados: 510

In [ ]:
# from __future__ import annotations

# from dataclasses import dataclass
# from typing import Sequence
# import warnings

# import numpy as np
# import pandas as pd


# # ============================================================
# # DATASET DE TRABAJO
# # ============================================================

# DATASET = df_c2


# # ============================================================
# # CONFIGURACIÓN
# # ============================================================

# @dataclass(frozen=True)
# class FeatureConfig:
#     time_col: str = "bar_end"
#     ys_col: str = "YS"

#     price_suffix: str = "USDT"
#     volume_suffix: str = "_v"
#     trades_suffix: str = "_activity_trades_proxy"
#     range_suffix: str = "_range_rel_proxy"
#     illiq_suffix: str = "_illiquidity_proxy"
#     active_suffix: str = "_active_trading"
#     observed_suffix: str = "_observed"
#     buy_suffix: str = "_taker_buy_usdt_proxy"
#     sell_suffix: str = "_taker_sell_usdt_proxy"
#     yp_suffix: str = "_yp"

#     primary_window: int = 288
#     min_periods: int = 72
#     ewm_span: int = 72

#     multiscale_windows: tuple[int, ...] = (
#         3,
#         12,
#         72,
#         288,
#     )

#     return_lag: int = 1

#     stress_quantile: float = 0.90

#     recovery_tolerance: float = 0.15
#     recovery_hold_bars: int = 3
#     recovery_event_ewm_alpha: float = 0.20

#     eps: float = 1e-12
#     dtype: str = "float32"

#     asset_block_size: int = 32


# cfg = FeatureConfig()


# # ============================================================
# # TIEMPO
# # ============================================================

# def validate_time(df, cfg):
#     df = df.copy()

#     df[cfg.time_col] = pd.to_datetime(
#         df[cfg.time_col],
#         utc=True,
#         errors="raise"
#     )

#     df = (
#         df.sort_values(cfg.time_col)
#           .reset_index(drop=True)
#     )

#     if df[cfg.time_col].duplicated().any():
#         raise ValueError("Existen timestamps duplicados.")

#     delta = df[cfg.time_col].diff().dropna()

#     expected = pd.Timedelta(minutes=5)

#     if not delta.eq(expected).all():
#         raise ValueError(
#             "La serie no posee una grilla estricta de 5 minutos."
#         )

#     return df


# # ============================================================
# # ACTIVOS
# # ============================================================

# def discover_assets(df, cfg):

#     price_cols = [
#         c for c in df.columns
#         if c.endswith(cfg.price_suffix)
#         and "_" not in c
#     ]

#     candidates = sorted(
#         c[:-len(cfg.price_suffix)]
#         for c in price_cols
#     )

#     required_suffixes = (
#         cfg.volume_suffix,
#         cfg.trades_suffix,
#         cfg.range_suffix,
#         cfg.illiq_suffix,
#         cfg.active_suffix,
#         cfg.observed_suffix,
#         cfg.buy_suffix,
#         cfg.sell_suffix,
#         cfg.yp_suffix,
#     )

#     assets = []

#     for asset in candidates:

#         if all(
#             f"{asset}{suffix}" in df.columns
#             for suffix in required_suffixes
#         ):
#             assets.append(asset)

#     if len(assets) != 510:
#         warnings.warn(
#             f"Se detectaron {len(assets)} activos completos."
#         )

#     return assets


# def chunks(seq, size):
#     for start in range(0, len(seq), size):
#         yield list(seq[start:start + size])


# # ============================================================
# # NOMBRES
# # ============================================================

# def base_col(asset, kind, cfg):

#     if kind == "P":
#         return f"{asset}{cfg.price_suffix}"

#     suffix = {
#         "V": cfg.volume_suffix,
#         "C": cfg.trades_suffix,
#         "R": cfg.range_suffix,
#         "L": cfg.illiq_suffix,
#         "A": cfg.active_suffix,
#         "O": cfg.observed_suffix,
#         "B": cfg.buy_suffix,
#         "S": cfg.sell_suffix,
#         "yp": cfg.yp_suffix,
#     }[kind]

#     return f"{asset}{suffix}"


# def feat_col(asset, feature):
#     return f"{asset}__{feature}"


# # ============================================================
# # CARGA POR BLOQUES
# # ============================================================

# def load_base(df, assets, kind, cfg):

#     cols = [
#         base_col(a, kind, cfg)
#         for a in assets
#     ]

#     out = df.loc[:, cols].astype(
#         "float64",
#         copy=False
#     )

#     out.columns = assets

#     return out


# def load_feature(df, assets, feature):

#     cols = [
#         feat_col(a, feature)
#         for a in assets
#     ]

#     out = df.loc[:, cols].astype(
#         "float64",
#         copy=False
#     )

#     out.columns = assets

#     return out


# def name_block(x, feature, cfg):

#     out = x.astype(
#         cfg.dtype,
#         copy=False
#     )

#     out.columns = [
#         feat_col(a, feature)
#         for a in out.columns
#     ]

#     return out


# def merge_blocks(df, blocks):

#     block = pd.concat(
#         blocks,
#         axis=1,
#         copy=False
#     )

#     overlap = df.columns.intersection(
#         block.columns
#     )

#     if len(overlap):
#         df = df.drop(columns=list(overlap))

#     return pd.concat(
#         [df, block],
#         axis=1,
#         copy=False
#     )


# # ============================================================
# # ROBUST Z CAUSAL
# # ============================================================

# def robust_z_causal(
#     x,
#     window,
#     min_periods,
#     eps
# ):

#     hist = x.shift(1)

#     roll = hist.rolling(
#         window=window,
#         min_periods=min_periods
#     )

#     median = roll.median()

#     q25 = roll.quantile(0.25)
#     q75 = roll.quantile(0.75)

#     scale = (
#         q75 - q25
#     ) / 1.349

#     return (
#         x - median
#     ) / (
#         scale + eps
#     )


# # ============================================================
# # DISPERSIÓN ROBUSTA
# # ============================================================

# def rolling_robust_dispersion(
#     x,
#     window,
#     min_periods,
#     eps
# ):

#     roll = x.rolling(
#         window=window,
#         min_periods=min_periods
#     )

#     q25 = roll.quantile(0.25)
#     q75 = roll.quantile(0.75)

#     return (
#         (q75 - q25) / 1.349
#         + eps
#     )


# # ============================================================
# # AUTOCORRELACIÓN ROLLING
# # ============================================================

# def rolling_autocorr_lag1(
#     x,
#     window,
#     min_periods
# ):

#     lag = x.shift(1)

#     result = {}

#     for col in x.columns:
#         result[col] = (
#             x[col]
#             .rolling(
#                 window=window,
#                 min_periods=min_periods
#             )
#             .corr(lag[col])
#         )

#     return pd.DataFrame(
#         result,
#         index=x.index
#     )


# # ============================================================
# # BETA ROLLING
# # ============================================================

# def rolling_beta_with_intercept(
#     x,
#     y,
#     window,
#     min_periods,
#     eps
# ):

#     rx = x.rolling(
#         window,
#         min_periods=min_periods
#     )

#     ry = y.rolling(
#         window,
#         min_periods=min_periods
#     )

#     ex = rx.mean()
#     ey = ry.mean()

#     exy = (
#         (x * y)
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .mean()
#     )

#     ex2 = (
#         (x * x)
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .mean()
#     )

#     cov_xy = exy - ex * ey
#     var_x = ex2 - ex * ex

#     beta = (
#         cov_xy
#         / (var_x + eps)
#     )

#     return beta.clip(lower=0.0)


# # ============================================================
# # STRESS
# # ============================================================

# def rolling_stress_threshold(
#     stress,
#     window,
#     min_periods,
#     q
# ):

#     return (
#         stress
#         .shift(1)
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .quantile(q)
#     )


# def conditional_rolling_median_ratio(
#     value,
#     stress,
#     threshold,
#     window,
#     min_periods,
#     eps
# ):

#     is_stress = (
#         stress > threshold
#     )

#     numerator = (
#         value
#         .where(is_stress)
#         .rolling(
#             window,
#             min_periods=max(
#                 5,
#                 min_periods // 10
#             )
#         )
#         .median()
#     )

#     denominator = (
#         value
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .median()
#     )

#     return (
#         numerator
#         / (denominator + eps)
#     )


# # ============================================================
# # PROXY POSITIVO LATENTE
# # ============================================================

# def softplus_df(x):

#     values = np.logaddexp(
#         0.0,
#         x.to_numpy(
#             dtype=np.float64,
#             copy=False
#         )
#     )

#     return pd.DataFrame(
#         values,
#         index=x.index,
#         columns=x.columns
#     )


# def composite_positive_proxy(
#     components,
#     cfg
# ):

#     total = None
#     count = None

#     for component in components:

#         z = robust_z_causal(
#             component,
#             cfg.primary_window,
#             cfg.min_periods,
#             cfg.eps
#         )

#         valid = z.notna()

#         if total is None:

#             total = z.fillna(0.0)

#             count = valid.astype(
#                 "float64"
#             )

#         else:

#             total += z.fillna(0.0)

#             count += valid.astype(
#                 "float64"
#             )

#     score = (
#         total
#         / count.replace(0.0, np.nan)
#     )

#     return softplus_df(score)


# # ============================================================
# # RECOVERY SPEED CAUSAL
# # ============================================================

# @njit(parallel=True)
# def _recovery_speed_numba(
#     g,
#     s,
#     q,
#     b,
#     tolerance,
#     hold_bars,
#     alpha,
#     eps
# ):
#     T, N = g.shape
#     output = np.full((T, N), np.nan, dtype=np.float64)

#     for j in prange(N):
#         in_event = False
#         event_start = -1
#         event_baseline = np.nan
#         consecutive = 0
#         duration_ewma = np.nan

#         for t in range(T):
#             if not in_event:
#                 if (
#                     np.isfinite(s[t, j])
#                     and np.isfinite(q[t, j])
#                     and np.isfinite(b[t, j])
#                     and s[t, j] > q[t, j]
#                     and abs(b[t, j]) > eps
#                 ):
#                     in_event = True
#                     event_start = t
#                     event_baseline = b[t, j]
#                     consecutive = 0

#             elif np.isfinite(g[t, j]):
#                 distance = abs(g[t, j] - event_baseline) / (
#                     abs(event_baseline) + eps
#                 )

#                 if distance <= tolerance:
#                     consecutive += 1
#                 else:
#                     consecutive = 0

#                 if consecutive >= hold_bars:
#                     recovery_start = t - hold_bars + 1
#                     duration = max(1, recovery_start - event_start)

#                     if np.isnan(duration_ewma):
#                         duration_ewma = float(duration)
#                     else:
#                         duration_ewma = (
#                             alpha * duration
#                             + (1.0 - alpha) * duration_ewma
#                         )

#                     in_event = False
#                     event_start = -1
#                     event_baseline = np.nan
#                     consecutive = 0

#             if np.isfinite(duration_ewma):
#                 output[t, j] = 1.0 / (1.0 + duration_ewma)

#     return output


# def recovery_speed_causal(
#     gp0,
#     stress,
#     stress_threshold,
#     baseline,
#     tolerance,
#     hold_bars,
#     alpha,
#     eps
# ):
#     frames = (stress, stress_threshold, baseline)

#     if any(
#         not gp0.index.equals(x.index)
#         or not gp0.columns.equals(x.columns)
#         for x in frames
#     ):
#         raise ValueError(
#             "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
#         )

#     output = _recovery_speed_numba(
#         gp0.to_numpy(dtype=np.float64, copy=False),
#         stress.to_numpy(dtype=np.float64, copy=False),
#         stress_threshold.to_numpy(dtype=np.float64, copy=False),
#         baseline.to_numpy(dtype=np.float64, copy=False),
#         tolerance,
#         hold_bars,
#         alpha,
#         eps,
#     )

#     return pd.DataFrame(
#         output,
#         index=gp0.index,
#         columns=gp0.columns,
#     )

# # ============================================================
# # INICIALIZACIÓN
# # ============================================================

# DATASET = validate_time(DATASET, cfg)

# assets = discover_assets(
#     DATASET,
#     cfg
# )

# print("Dataset:", DATASET.shape)
# print("Activos detectados:", len(assets))

Dataset: (43776, 20918)
Activos detectados: 510

In [ ]:
# from __future__ import annotations

# from dataclasses import dataclass
# from typing import Sequence
# import warnings

# import numpy as np
# import pandas as pd


# # ============================================================
# # DATASET DE TRABAJO
# # ============================================================

# DATASET = df_c3


# # ============================================================
# # CONFIGURACIÓN
# # ============================================================

# @dataclass(frozen=True)
# class FeatureConfig:
#     time_col: str = "bar_end"
#     ys_col: str = "YS"

#     price_suffix: str = "USDT"
#     volume_suffix: str = "_v"
#     trades_suffix: str = "_activity_trades_proxy"
#     range_suffix: str = "_range_rel_proxy"
#     illiq_suffix: str = "_illiquidity_proxy"
#     active_suffix: str = "_active_trading"
#     observed_suffix: str = "_observed"
#     buy_suffix: str = "_taker_buy_usdt_proxy"
#     sell_suffix: str = "_taker_sell_usdt_proxy"
#     yp_suffix: str = "_yp"

#     primary_window: int = 288
#     min_periods: int = 72
#     ewm_span: int = 72

#     multiscale_windows: tuple[int, ...] = (
#         3,
#         12,
#         72,
#         288,
#     )

#     return_lag: int = 1

#     stress_quantile: float = 0.90

#     recovery_tolerance: float = 0.15
#     recovery_hold_bars: int = 3
#     recovery_event_ewm_alpha: float = 0.20

#     eps: float = 1e-12
#     dtype: str = "float32"

#     asset_block_size: int = 32


# cfg = FeatureConfig()


# # ============================================================
# # TIEMPO
# # ============================================================

# def validate_time(df, cfg):
#     df = df.copy()

#     df[cfg.time_col] = pd.to_datetime(
#         df[cfg.time_col],
#         utc=True,
#         errors="raise"
#     )

#     df = (
#         df.sort_values(cfg.time_col)
#           .reset_index(drop=True)
#     )

#     if df[cfg.time_col].duplicated().any():
#         raise ValueError("Existen timestamps duplicados.")

#     delta = df[cfg.time_col].diff().dropna()

#     expected = pd.Timedelta(minutes=5)

#     if not delta.eq(expected).all():
#         raise ValueError(
#             "La serie no posee una grilla estricta de 5 minutos."
#         )

#     return df


# # ============================================================
# # ACTIVOS
# # ============================================================

# def discover_assets(df, cfg):

#     price_cols = [
#         c for c in df.columns
#         if c.endswith(cfg.price_suffix)
#         and "_" not in c
#     ]

#     candidates = sorted(
#         c[:-len(cfg.price_suffix)]
#         for c in price_cols
#     )

#     required_suffixes = (
#         cfg.volume_suffix,
#         cfg.trades_suffix,
#         cfg.range_suffix,
#         cfg.illiq_suffix,
#         cfg.active_suffix,
#         cfg.observed_suffix,
#         cfg.buy_suffix,
#         cfg.sell_suffix,
#         cfg.yp_suffix,
#     )

#     assets = []

#     for asset in candidates:

#         if all(
#             f"{asset}{suffix}" in df.columns
#             for suffix in required_suffixes
#         ):
#             assets.append(asset)

#     if len(assets) != 510:
#         warnings.warn(
#             f"Se detectaron {len(assets)} activos completos."
#         )

#     return assets


# def chunks(seq, size):
#     for start in range(0, len(seq), size):
#         yield list(seq[start:start + size])


# # ============================================================
# # NOMBRES
# # ============================================================

# def base_col(asset, kind, cfg):

#     if kind == "P":
#         return f"{asset}{cfg.price_suffix}"

#     suffix = {
#         "V": cfg.volume_suffix,
#         "C": cfg.trades_suffix,
#         "R": cfg.range_suffix,
#         "L": cfg.illiq_suffix,
#         "A": cfg.active_suffix,
#         "O": cfg.observed_suffix,
#         "B": cfg.buy_suffix,
#         "S": cfg.sell_suffix,
#         "yp": cfg.yp_suffix,
#     }[kind]

#     return f"{asset}{suffix}"


# def feat_col(asset, feature):
#     return f"{asset}__{feature}"


# # ============================================================
# # CARGA POR BLOQUES
# # ============================================================

# def load_base(df, assets, kind, cfg):

#     cols = [
#         base_col(a, kind, cfg)
#         for a in assets
#     ]

#     out = df.loc[:, cols].astype(
#         "float64",
#         copy=False
#     )

#     out.columns = assets

#     return out


# def load_feature(df, assets, feature):

#     cols = [
#         feat_col(a, feature)
#         for a in assets
#     ]

#     out = df.loc[:, cols].astype(
#         "float64",
#         copy=False
#     )

#     out.columns = assets

#     return out


# def name_block(x, feature, cfg):

#     out = x.astype(
#         cfg.dtype,
#         copy=False
#     )

#     out.columns = [
#         feat_col(a, feature)
#         for a in out.columns
#     ]

#     return out


# def merge_blocks(df, blocks):

#     block = pd.concat(
#         blocks,
#         axis=1,
#         copy=False
#     )

#     overlap = df.columns.intersection(
#         block.columns
#     )

#     if len(overlap):
#         df = df.drop(columns=list(overlap))

#     return pd.concat(
#         [df, block],
#         axis=1,
#         copy=False
#     )


# # ============================================================
# # ROBUST Z CAUSAL
# # ============================================================

# def robust_z_causal(
#     x,
#     window,
#     min_periods,
#     eps
# ):

#     hist = x.shift(1)

#     roll = hist.rolling(
#         window=window,
#         min_periods=min_periods
#     )

#     median = roll.median()

#     q25 = roll.quantile(0.25)
#     q75 = roll.quantile(0.75)

#     scale = (
#         q75 - q25
#     ) / 1.349

#     return (
#         x - median
#     ) / (
#         scale + eps
#     )


# # ============================================================
# # DISPERSIÓN ROBUSTA
# # ============================================================

# def rolling_robust_dispersion(
#     x,
#     window,
#     min_periods,
#     eps
# ):

#     roll = x.rolling(
#         window=window,
#         min_periods=min_periods
#     )

#     q25 = roll.quantile(0.25)
#     q75 = roll.quantile(0.75)

#     return (
#         (q75 - q25) / 1.349
#         + eps
#     )


# # ============================================================
# # AUTOCORRELACIÓN ROLLING
# # ============================================================

# def rolling_autocorr_lag1(
#     x,
#     window,
#     min_periods
# ):

#     lag = x.shift(1)

#     result = {}

#     for col in x.columns:
#         result[col] = (
#             x[col]
#             .rolling(
#                 window=window,
#                 min_periods=min_periods
#             )
#             .corr(lag[col])
#         )

#     return pd.DataFrame(
#         result,
#         index=x.index
#     )


# # ============================================================
# # BETA ROLLING
# # ============================================================

# def rolling_beta_with_intercept(
#     x,
#     y,
#     window,
#     min_periods,
#     eps
# ):

#     rx = x.rolling(
#         window,
#         min_periods=min_periods
#     )

#     ry = y.rolling(
#         window,
#         min_periods=min_periods
#     )

#     ex = rx.mean()
#     ey = ry.mean()

#     exy = (
#         (x * y)
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .mean()
#     )

#     ex2 = (
#         (x * x)
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .mean()
#     )

#     cov_xy = exy - ex * ey
#     var_x = ex2 - ex * ex

#     beta = (
#         cov_xy
#         / (var_x + eps)
#     )

#     return beta.clip(lower=0.0)


# # ============================================================
# # STRESS
# # ============================================================

# def rolling_stress_threshold(
#     stress,
#     window,
#     min_periods,
#     q
# ):

#     return (
#         stress
#         .shift(1)
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .quantile(q)
#     )


# def conditional_rolling_median_ratio(
#     value,
#     stress,
#     threshold,
#     window,
#     min_periods,
#     eps
# ):

#     is_stress = (
#         stress > threshold
#     )

#     numerator = (
#         value
#         .where(is_stress)
#         .rolling(
#             window,
#             min_periods=max(
#                 5,
#                 min_periods // 10
#             )
#         )
#         .median()
#     )

#     denominator = (
#         value
#         .rolling(
#             window,
#             min_periods=min_periods
#         )
#         .median()
#     )

#     return (
#         numerator
#         / (denominator + eps)
#     )


# # ============================================================
# # PROXY POSITIVO LATENTE
# # ============================================================

# def softplus_df(x):

#     values = np.logaddexp(
#         0.0,
#         x.to_numpy(
#             dtype=np.float64,
#             copy=False
#         )
#     )

#     return pd.DataFrame(
#         values,
#         index=x.index,
#         columns=x.columns
#     )


# def composite_positive_proxy(
#     components,
#     cfg
# ):

#     total = None
#     count = None

#     for component in components:

#         z = robust_z_causal(
#             component,
#             cfg.primary_window,
#             cfg.min_periods,
#             cfg.eps
#         )

#         valid = z.notna()

#         if total is None:

#             total = z.fillna(0.0)

#             count = valid.astype(
#                 "float64"
#             )

#         else:

#             total += z.fillna(0.0)

#             count += valid.astype(
#                 "float64"
#             )

#     score = (
#         total
#         / count.replace(0.0, np.nan)
#     )

#     return softplus_df(score)


# # ============================================================
# # RECOVERY SPEED CAUSAL
# # ============================================================

# @njit(parallel=True)
# def _recovery_speed_numba(
#     g,
#     s,
#     q,
#     b,
#     tolerance,
#     hold_bars,
#     alpha,
#     eps
# ):
#     T, N = g.shape
#     output = np.full((T, N), np.nan, dtype=np.float64)

#     for j in prange(N):
#         in_event = False
#         event_start = -1
#         event_baseline = np.nan
#         consecutive = 0
#         duration_ewma = np.nan

#         for t in range(T):
#             if not in_event:
#                 if (
#                     np.isfinite(s[t, j])
#                     and np.isfinite(q[t, j])
#                     and np.isfinite(b[t, j])
#                     and s[t, j] > q[t, j]
#                     and abs(b[t, j]) > eps
#                 ):
#                     in_event = True
#                     event_start = t
#                     event_baseline = b[t, j]
#                     consecutive = 0

#             elif np.isfinite(g[t, j]):
#                 distance = abs(g[t, j] - event_baseline) / (
#                     abs(event_baseline) + eps
#                 )

#                 if distance <= tolerance:
#                     consecutive += 1
#                 else:
#                     consecutive = 0

#                 if consecutive >= hold_bars:
#                     recovery_start = t - hold_bars + 1
#                     duration = max(1, recovery_start - event_start)

#                     if np.isnan(duration_ewma):
#                         duration_ewma = float(duration)
#                     else:
#                         duration_ewma = (
#                             alpha * duration
#                             + (1.0 - alpha) * duration_ewma
#                         )

#                     in_event = False
#                     event_start = -1
#                     event_baseline = np.nan
#                     consecutive = 0

#             if np.isfinite(duration_ewma):
#                 output[t, j] = 1.0 / (1.0 + duration_ewma)

#     return output


# def recovery_speed_causal(
#     gp0,
#     stress,
#     stress_threshold,
#     baseline,
#     tolerance,
#     hold_bars,
#     alpha,
#     eps
# ):
#     frames = (stress, stress_threshold, baseline)

#     if any(
#         not gp0.index.equals(x.index)
#         or not gp0.columns.equals(x.columns)
#         for x in frames
#     ):
#         raise ValueError(
#             "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
#         )

#     output = _recovery_speed_numba(
#         gp0.to_numpy(dtype=np.float64, copy=False),
#         stress.to_numpy(dtype=np.float64, copy=False),
#         stress_threshold.to_numpy(dtype=np.float64, copy=False),
#         baseline.to_numpy(dtype=np.float64, copy=False),
#         tolerance,
#         hold_bars,
#         alpha,
#         eps,
#     )

#     return pd.DataFrame(
#         output,
#         index=gp0.index,
#         columns=gp0.columns,
#     )

# # ============================================================
# # INICIALIZACIÓN
# # ============================================================

# DATASET = validate_time(DATASET, cfg)

# assets = discover_assets(
#     DATASET,
#     cfg
# )

# print("Dataset:", DATASET.shape)
# print("Activos detectados:", len(assets))

Dataset: (44064, 20918)
Activos detectados: 510

## 10. Estructura competitiva y anidada de N

- Persistencia competiviva de gp

NRANK = R^g_{i,t}=PercentileRank_j(gp_{j,t}),\ NRANK=e^({-\Delta R^g})

Permanencia de posicion competiviva

- Simplex de resistencia familia[qg_W3, qg_W12, qg_W72, qg_W288]

q_g_i,t,W_ = GW_i,t /SUMj(Gw_j,t)

Distribucion competitiva de la resistencia

-Coherencia anidada

NEST= exp[-Var_W*(ln(qg_t,i,W_))]

In [48]:
from pathlib import Path
import os
import gc


# ============================================================
# DATASETS DE TRABAJO
# ============================================================

DATASETS = {
    "df_c1": df_c1,
    "df_c2": df_c2,
    "df_c3": df_c3,
}


# ============================================================
# ARCHIVOS DE SALIDA
# ============================================================

ruta = Path(
    "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"
)

OUTPUTS = {
    "df_c1": ruta / "112024-042025_clean_add_gp_fgp_nmetrics_nrank_qg_nest.parquet",
    "df_c2": ruta / "042025-092025_clean_add_gp_fgp_nmetrics_nrank_qg_nest.parquet",
    "df_c3": ruta / "092025-022026_clean_add_gp_fgp_nmetrics_nrank_qg_nest.parquet",
}


# ============================================================
# CONTROL DE PROCESO
# ============================================================

saved_files = []
completed_datasets = []

current_dataset = None
current_stage = None
current_chunk = 0
total_chunks = 0


try:

    for dataset_name, DATASET in DATASETS.items():

        current_dataset = dataset_name

        asset_chunks = list(
            chunks(
                assets,
                cfg.asset_block_size
            )
        )

        total_chunks = len(asset_chunks)

        print("\n" + "=" * 70)
        print(
            f"{dataset_name} | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas | "
            f"{total_chunks} chunks"
        )
        print("=" * 70)


        # ============================================================
        # NRANK
        # ============================================================

        current_stage = "NRANK"
        current_chunk = 0

        gp_all = load_feature(
            DATASET,
            assets,
            "gp"
        ).astype("float32")


        A_all = load_base(
            DATASET,
            assets,
            "A",
            cfg
        ).astype("float32")


        gp_active = gp_all.where(
            A_all > 0
        )


        gp_rank = gp_active.rank(
            axis=1,
            pct=True,
            method="average"
        )


        NRANK_all = np.exp(
            -gp_rank.diff().abs()
        )


        for i, chunk in enumerate(
            asset_chunks,
            start=1
        ):

            # ====================================================
            # PREPARACIÓN DEL CHUNK
            # ====================================================

            chunk_blocks = [
                name_block(
                    NRANK_all.loc[:, chunk],
                    "NRANK",
                    cfg
                )
            ]


            # ====================================================
            # COMMIT DEL CHUNK
            # ====================================================

            DATASET = merge_blocks(
                DATASET,
                chunk_blocks
            )

            DATASETS[dataset_name] = DATASET
            globals()[dataset_name] = DATASET

            current_chunk = i

            print(
                f"{dataset_name} | "
                f"NRANK | "
                f"chunk {i:02d}/{total_chunks} OK | "
                f"{len(chunk):02d} activos | "
                f"{DATASET.shape[1]:,} columnas"
            )

            del chunk_blocks
            gc.collect()


        del (
            gp_all,
            A_all,
            gp_active,
            gp_rank,
            NRANK_all,
        )

        gc.collect()


        # ============================================================
        # SIMPLEX qg POR ESCALA
        # ============================================================

        for w in cfg.multiscale_windows:

            current_stage = f"qg_W{w}"
            current_chunk = 0


            # --------------------------------------------------------
            # Suma transversal
            # Debe completarse sobre TODOS los activos antes del qg
            # --------------------------------------------------------

            total = np.zeros(
                len(DATASET),
                dtype=np.float64
            )


            for i, chunk in enumerate(
                asset_chunks,
                start=1
            ):

                G = load_feature(
                    DATASET,
                    chunk,
                    f"gp_W{w}"
                )

                A = load_base(
                    DATASET,
                    chunk,
                    "A",
                    cfg
                )

                G = G.where(
                    A > 0
                )

                total += (
                    G.sum(axis=1)
                     .to_numpy()
                )

                print(
                    f"{dataset_name} | "
                    f"qg_W{w} denominador | "
                    f"chunk {i:02d}/{total_chunks} OK"
                )

                del G, A
                gc.collect()


            total = pd.Series(
                total,
                index=DATASET.index
            ).replace(
                0,
                np.nan
            )


            # --------------------------------------------------------
            # qg por chunk
            # --------------------------------------------------------

            for i, chunk in enumerate(
                asset_chunks,
                start=1
            ):

                G = load_feature(
                    DATASET,
                    chunk,
                    f"gp_W{w}"
                )

                A = load_base(
                    DATASET,
                    chunk,
                    "A",
                    cfg
                )

                qg = (
                    G.where(A > 0)
                     .div(
                         total,
                         axis=0
                     )
                )


                # ====================================================
                # PREPARACIÓN DEL CHUNK
                # ====================================================

                chunk_blocks = [
                    name_block(
                        qg,
                        f"qg_W{w}",
                        cfg
                    )
                ]


                # ====================================================
                # COMMIT DEL CHUNK
                # ====================================================

                DATASET = merge_blocks(
                    DATASET,
                    chunk_blocks
                )

                DATASETS[dataset_name] = DATASET
                globals()[dataset_name] = DATASET

                current_chunk = i

                print(
                    f"{dataset_name} | "
                    f"qg_W{w} | "
                    f"chunk {i:02d}/{total_chunks} OK | "
                    f"{len(chunk):02d} activos | "
                    f"{DATASET.shape[1]:,} columnas"
                )

                del (
                    G,
                    A,
                    qg,
                    chunk_blocks,
                )

                gc.collect()


            del total
            gc.collect()


        # ============================================================
        # NEST
        # ============================================================

        current_stage = "NEST"
        current_chunk = 0


        for i, chunk in enumerate(
            asset_chunks,
            start=1
        ):

            q_logs = []


            for w in cfg.multiscale_windows:

                qg = load_feature(
                    DATASET,
                    chunk,
                    f"qg_W{w}"
                )

                q_logs.append(
                    np.log(
                        qg.clip(
                            lower=cfg.eps
                        )
                    )
                )


            stack = np.stack(
                [
                    x.to_numpy()
                    for x in q_logs
                ],
                axis=2
            )

            variance = np.nanvar(
                stack,
                axis=2
            )

            NEST = pd.DataFrame(
                np.exp(-variance),
                index=DATASET.index,
                columns=chunk
            )


            # ====================================================
            # PREPARACIÓN DEL CHUNK
            # ====================================================

            chunk_blocks = [
                name_block(
                    NEST,
                    "NEST",
                    cfg
                )
            ]


            # ====================================================
            # COMMIT DEL CHUNK
            # ====================================================

            DATASET = merge_blocks(
                DATASET,
                chunk_blocks
            )

            DATASETS[dataset_name] = DATASET
            globals()[dataset_name] = DATASET

            current_chunk = i

            print(
                f"{dataset_name} | "
                f"NEST | "
                f"chunk {i:02d}/{total_chunks} OK | "
                f"{len(chunk):02d} activos | "
                f"{DATASET.shape[1]:,} columnas"
            )


            del (
                q_logs,
                qg,
                stack,
                variance,
                NEST,
                chunk_blocks,
            )

            gc.collect()


        # ============================================================
        # GUARDADO DEL DATASET COMPLETO
        # ============================================================

        output_file = OUTPUTS[dataset_name]
        temp_file = output_file.with_suffix(
            ".tmp.parquet"
        )

        DATASET.to_parquet(
            temp_file,
            index=False
        )

        os.replace(
            temp_file,
            output_file
        )

        saved_files.append(
            str(output_file)
        )

        completed_datasets.append(
            dataset_name
        )

        print(
            f"\n{dataset_name} COMPLETO | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas"
        )

        print(
            f"Guardado: {output_file}"
        )


except KeyboardInterrupt:

    print(
        "\nPROCESO INTERRUMPIDO MANUALMENTE"
    )


except Exception as e:

    print(
        f"\nERROR: "
        f"{type(e).__name__}: {e}"
    )


finally:

    # ============================================================
    # ESTADO FINAL
    # ============================================================

    print("\n" + "=" * 70)
    print("ESTADO FINAL")
    print("=" * 70)


    if current_dataset is not None:

        print(
            f"Último dataset: {current_dataset}"
        )

        print(
            f"Última etapa: {current_stage}"
        )

        print(
            f"Chunks confirmados en la etapa: "
            f"{current_chunk}/{total_chunks}"
        )


    if completed_datasets:

        print(
            "\nDatasets completados:",
            ", ".join(
                completed_datasets
            )
        )

    else:

        print(
            "\nDatasets completados: ninguno"
        )


    if saved_files:

        print(
            "\nArchivos guardados exitosamente:"
        )

        for file in saved_files:

            print(
                f"  ✓ {file}"
            )

    else:

        print(
            "\nArchivos completos guardados: ninguno"
        )

======================================================================
df_c1 | 43,775 filas × 27,038 columnas | 16 chunks
======================================================================
df_c1 | NRANK | chunk 01/16 OK | 32 activos | 27,070 columnas
df_c1 | NRANK | chunk 02/16 OK | 32 activos | 27,102 columnas
df_c1 | NRANK | chunk 03/16 OK | 32 activos | 27,134 columnas
df_c1 | NRANK | chunk 04/16 OK | 32 activos | 27,166 columnas
df_c1 | NRANK | chunk 05/16 OK | 32 activos | 27,198 columnas
df_c1 | NRANK | chunk 06/16 OK | 32 activos | 27,230 columnas
df_c1 | NRANK | chunk 07/16 OK | 32 activos | 27,262 columnas
df_c1 | NRANK | chunk 08/16 OK | 32 activos | 27,294 columnas
df_c1 | NRANK | chunk 09/16 OK | 32 activos | 27,326 columnas
df_c1 | NRANK | chunk 10/16 OK | 32 activos | 27,358 columnas
df_c1 | NRANK | chunk 11/16 OK | 32 activos | 27,390 columnas
df_c1 | NRANK | chunk 12/16 OK | 32 activos | 27,422 columnas
df_c1 | NRANK | chunk 13/16 OK | 32 activos | 27,454 columnas
df_c1 | NRANK | chunk 14/16 OK | 32 activos | 27,486 columnas
df_c1 | NRANK | chunk 15/16 OK | 32 activos | 27,518 columnas
df_c1 | NRANK | chunk 16/16 OK | 30 activos | 27,548 columnas
df_c1 | qg_W3 denominador | chunk 01/16 OK
df_c1 | qg_W3 denominador | chunk 02/16 OK
df_c1 | qg_W3 denominador | chunk 03/16 OK
df_c1 | qg_W3 denominador | chunk 04/16 OK
df_c1 | qg_W3 denominador | chunk 05/16 OK
df_c1 | qg_W3 denominador | chunk 06/16 OK
df_c1 | qg_W3 denominador | chunk 07/16 OK
df_c1 | qg_W3 denominador | chunk 08/16 OK
df_c1 | qg_W3 denominador | chunk 09/16 OK
df_c1 | qg_W3 denominador | chunk 10/16 OK
df_c1 | qg_W3 denominador | chunk 11/16 OK
df_c1 | qg_W3 denominador | chunk 12/16 OK
df_c1 | qg_W3 denominador | chunk 13/16 OK
df_c1 | qg_W3 denominador | chunk 14/16 OK
df_c1 | qg_W3 denominador | chunk 15/16 OK
df_c1 | qg_W3 denominador | chunk 16/16 OK
df_c1 | qg_W3 | chunk 01/16 OK | 32 activos | 27,580 columnas
df_c1 | qg_W3 | chunk 02/16 OK | 32 activos | 27,612 columnas
df_c1 | qg_W3 | chunk 03/16 OK | 32 activos | 27,644 columnas
df_c1 | qg_W3 | chunk 04/16 OK | 32 activos | 27,676 columnas
df_c1 | qg_W3 | chunk 05/16 OK | 32 activos | 27,708 columnas
df_c1 | qg_W3 | chunk 06/16 OK | 32 activos | 27,740 columnas
df_c1 | qg_W3 | chunk 07/16 OK | 32 activos | 27,772 columnas
df_c1 | qg_W3 | chunk 08/16 OK | 32 activos | 27,804 columnas
df_c1 | qg_W3 | chunk 09/16 OK | 32 activos | 27,836 columnas
df_c1 | qg_W3 | chunk 10/16 OK | 32 activos | 27,868 columnas
df_c1 | qg_W3 | chunk 11/16 OK | 32 activos | 27,900 columnas
df_c1 | qg_W3 | chunk 12/16 OK | 32 activos | 27,932 columnas
df_c1 | qg_W3 | chunk 13/16 OK | 32 activos | 27,964 columnas
df_c1 | qg_W3 | chunk 14/16 OK | 32 activos | 27,996 columnas
df_c1 | qg_W3 | chunk 15/16 OK | 32 activos | 28,028 columnas
df_c1 | qg_W3 | chunk 16/16 OK | 30 activos | 28,058 columnas
df_c1 | qg_W12 denominador | chunk 01/16 OK
df_c1 | qg_W12 denominador | chunk 02/16 OK
df_c1 | qg_W12 denominador | chunk 03/16 OK
df_c1 | qg_W12 denominador | chunk 04/16 OK
df_c1 | qg_W12 denominador | chunk 05/16 OK
df_c1 | qg_W12 denominador | chunk 06/16 OK
df_c1 | qg_W12 denominador | chunk 07/16 OK
df_c1 | qg_W12 denominador | chunk 08/16 OK
df_c1 | qg_W12 denominador | chunk 09/16 OK
df_c1 | qg_W12 denominador | chunk 10/16 OK
df_c1 | qg_W12 denominador | chunk 11/16 OK
df_c1 | qg_W12 denominador | chunk 12/16 OK
df_c1 | qg_W12 denominador | chunk 13/16 OK
df_c1 | qg_W12 denominador | chunk 14/16 OK
df_c1 | qg_W12 denominador | chunk 15/16 OK
df_c1 | qg_W12 denominador | chunk 16/16 OK
df_c1 | qg_W12 | chunk 01/16 OK | 32 activos | 28,090 columnas
df_c1 | qg_W12 | chunk 02/16 OK | 32 activos | 28,122 columnas
df_c1 | qg_W12 | chunk 03/16 OK | 32 activos | 28,154 columnas
df_c1 | qg_W12 | chunk 04/16 OK | 32 activos | 28,186 columnas
df_c1 | qg_W12 | chunk 05/16 OK | 32 activos | 28,218 columnas
df_c1 | qg_W12 | chunk 06/16 OK | 32 activos | 28,250 columnas
df_c1 | qg_W12 | chunk 07/16 OK | 32 activos | 28,282 columnas
df_c1 | qg_W12 | chunk 08/16 OK | 32 activos | 28,314 columnas
df_c1 | qg_W12 | chunk 09/16 OK | 32 activos | 28,346 columnas
df_c1 | qg_W12 | chunk 10/16 OK | 32 activos | 28,378 columnas
df_c1 | qg_W12 | chunk 11/16 OK | 32 activos | 28,410 columnas
df_c1 | qg_W12 | chunk 12/16 OK | 32 activos | 28,442 columnas
df_c1 | qg_W12 | chunk 13/16 OK | 32 activos | 28,474 columnas
df_c1 | qg_W12 | chunk 14/16 OK | 32 activos | 28,506 columnas
df_c1 | qg_W12 | chunk 15/16 OK | 32 activos | 28,538 columnas
df_c1 | qg_W12 | chunk 16/16 OK | 30 activos | 28,568 columnas
df_c1 | qg_W72 denominador | chunk 01/16 OK
df_c1 | qg_W72 denominador | chunk 02/16 OK
df_c1 | qg_W72 denominador | chunk 03/16 OK
df_c1 | qg_W72 denominador | chunk 04/16 OK
df_c1 | qg_W72 denominador | chunk 05/16 OK
df_c1 | qg_W72 denominador | chunk 06/16 OK
df_c1 | qg_W72 denominador | chunk 07/16 OK
df_c1 | qg_W72 denominador | chunk 08/16 OK
df_c1 | qg_W72 denominador | chunk 09/16 OK
df_c1 | qg_W72 denominador | chunk 10/16 OK
df_c1 | qg_W72 denominador | chunk 11/16 OK
df_c1 | qg_W72 denominador | chunk 12/16 OK
df_c1 | qg_W72 denominador | chunk 13/16 OK
df_c1 | qg_W72 denominador | chunk 14/16 OK
df_c1 | qg_W72 denominador | chunk 15/16 OK
df_c1 | qg_W72 denominador | chunk 16/16 OK
df_c1 | qg_W72 | chunk 01/16 OK | 32 activos | 28,600 columnas
df_c1 | qg_W72 | chunk 02/16 OK | 32 activos | 28,632 columnas
df_c1 | qg_W72 | chunk 03/16 OK | 32 activos | 28,664 columnas
df_c1 | qg_W72 | chunk 04/16 OK | 32 activos | 28,696 columnas
df_c1 | qg_W72 | chunk 05/16 OK | 32 activos | 28,728 columnas
df_c1 | qg_W72 | chunk 06/16 OK | 32 activos | 28,760 columnas
df_c1 | qg_W72 | chunk 07/16 OK | 32 activos | 28,792 columnas
df_c1 | qg_W72 | chunk 08/16 OK | 32 activos | 28,824 columnas
df_c1 | qg_W72 | chunk 09/16 OK | 32 activos | 28,856 columnas
df_c1 | qg_W72 | chunk 10/16 OK | 32 activos | 28,888 columnas
df_c1 | qg_W72 | chunk 11/16 OK | 32 activos | 28,920 columnas
df_c1 | qg_W72 | chunk 12/16 OK | 32 activos | 28,952 columnas
df_c1 | qg_W72 | chunk 13/16 OK | 32 activos | 28,984 columnas
df_c1 | qg_W72 | chunk 14/16 OK | 32 activos | 29,016 columnas
df_c1 | qg_W72 | chunk 15/16 OK | 32 activos | 29,048 columnas
df_c1 | qg_W72 | chunk 16/16 OK | 30 activos | 29,078 columnas
df_c1 | qg_W288 denominador | chunk 01/16 OK
df_c1 | qg_W288 denominador | chunk 02/16 OK
df_c1 | qg_W288 denominador | chunk 03/16 OK
df_c1 | qg_W288 denominador | chunk 04/16 OK
df_c1 | qg_W288 denominador | chunk 05/16 OK
df_c1 | qg_W288 denominador | chunk 06/16 OK
df_c1 | qg_W288 denominador | chunk 07/16 OK
df_c1 | qg_W288 denominador | chunk 08/16 OK
df_c1 | qg_W288 denominador | chunk 09/16 OK
df_c1 | qg_W288 denominador | chunk 10/16 OK
df_c1 | qg_W288 denominador | chunk 11/16 OK
df_c1 | qg_W288 denominador | chunk 12/16 OK
df_c1 | qg_W288 denominador | chunk 13/16 OK
df_c1 | qg_W288 denominador | chunk 14/16 OK
df_c1 | qg_W288 denominador | chunk 15/16 OK
df_c1 | qg_W288 denominador | chunk 16/16 OK
df_c1 | qg_W288 | chunk 01/16 OK | 32 activos | 29,110 columnas
df_c1 | qg_W288 | chunk 02/16 OK | 32 activos | 29,142 columnas
df_c1 | qg_W288 | chunk 03/16 OK | 32 activos | 29,174 columnas
df_c1 | qg_W288 | chunk 04/16 OK | 32 activos | 29,206 columnas
df_c1 | qg_W288 | chunk 05/16 OK | 32 activos | 29,238 columnas
df_c1 | qg_W288 | chunk 06/16 OK | 32 activos | 29,270 columnas
df_c1 | qg_W288 | chunk 07/16 OK | 32 activos | 29,302 columnas
df_c1 | qg_W288 | chunk 08/16 OK | 32 activos | 29,334 columnas
df_c1 | qg_W288 | chunk 09/16 OK | 32 activos | 29,366 columnas
df_c1 | qg_W288 | chunk 10/16 OK | 32 activos | 29,398 columnas
df_c1 | qg_W288 | chunk 11/16 OK | 32 activos | 29,430 columnas
df_c1 | qg_W288 | chunk 12/16 OK | 32 activos | 29,462 columnas
df_c1 | qg_W288 | chunk 13/16 OK | 32 activos | 29,494 columnas
df_c1 | qg_W288 | chunk 14/16 OK | 32 activos | 29,526 columnas
df_c1 | qg_W288 | chunk 15/16 OK | 32 activos | 29,558 columnas
df_c1 | qg_W288 | chunk 16/16 OK | 30 activos | 29,588 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 01/16 OK | 32 activos | 29,620 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 02/16 OK | 32 activos | 29,652 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 03/16 OK | 32 activos | 29,684 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 04/16 OK | 32 activos | 29,716 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 05/16 OK | 32 activos | 29,748 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 06/16 OK | 32 activos | 29,780 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 07/16 OK | 32 activos | 29,812 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 08/16 OK | 32 activos | 29,844 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 09/16 OK | 32 activos | 29,876 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 10/16 OK | 32 activos | 29,908 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 11/16 OK | 32 activos | 29,940 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 12/16 OK | 32 activos | 29,972 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 13/16 OK | 32 activos | 30,004 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 14/16 OK | 32 activos | 30,036 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 15/16 OK | 32 activos | 30,068 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c1 | NEST | chunk 16/16 OK | 30 activos | 30,098 columnas

df_c1 COMPLETO | 43,775 filas × 30,098 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_gp_fgp_nmetrics_nrank_qg_nest.parquet

======================================================================
df_c2 | 43,776 filas × 27,038 columnas | 16 chunks
======================================================================
df_c2 | NRANK | chunk 01/16 OK | 32 activos | 27,070 columnas
df_c2 | NRANK | chunk 02/16 OK | 32 activos | 27,102 columnas
df_c2 | NRANK | chunk 03/16 OK | 32 activos | 27,134 columnas
df_c2 | NRANK | chunk 04/16 OK | 32 activos | 27,166 columnas
df_c2 | NRANK | chunk 05/16 OK | 32 activos | 27,198 columnas
df_c2 | NRANK | chunk 06/16 OK | 32 activos | 27,230 columnas
df_c2 | NRANK | chunk 07/16 OK | 32 activos | 27,262 columnas
df_c2 | NRANK | chunk 08/16 OK | 32 activos | 27,294 columnas
df_c2 | NRANK | chunk 09/16 OK | 32 activos | 27,326 columnas
df_c2 | NRANK | chunk 10/16 OK | 32 activos | 27,358 columnas
df_c2 | NRANK | chunk 11/16 OK | 32 activos | 27,390 columnas
df_c2 | NRANK | chunk 12/16 OK | 32 activos | 27,422 columnas
df_c2 | NRANK | chunk 13/16 OK | 32 activos | 27,454 columnas
df_c2 | NRANK | chunk 14/16 OK | 32 activos | 27,486 columnas
df_c2 | NRANK | chunk 15/16 OK | 32 activos | 27,518 columnas
df_c2 | NRANK | chunk 16/16 OK | 30 activos | 27,548 columnas
df_c2 | qg_W3 denominador | chunk 01/16 OK
df_c2 | qg_W3 denominador | chunk 02/16 OK
df_c2 | qg_W3 denominador | chunk 03/16 OK
df_c2 | qg_W3 denominador | chunk 04/16 OK
df_c2 | qg_W3 denominador | chunk 05/16 OK
df_c2 | qg_W3 denominador | chunk 06/16 OK
df_c2 | qg_W3 denominador | chunk 07/16 OK
df_c2 | qg_W3 denominador | chunk 08/16 OK
df_c2 | qg_W3 denominador | chunk 09/16 OK
df_c2 | qg_W3 denominador | chunk 10/16 OK
df_c2 | qg_W3 denominador | chunk 11/16 OK
df_c2 | qg_W3 denominador | chunk 12/16 OK
df_c2 | qg_W3 denominador | chunk 13/16 OK
df_c2 | qg_W3 denominador | chunk 14/16 OK
df_c2 | qg_W3 denominador | chunk 15/16 OK
df_c2 | qg_W3 denominador | chunk 16/16 OK
df_c2 | qg_W3 | chunk 01/16 OK | 32 activos | 27,580 columnas
df_c2 | qg_W3 | chunk 02/16 OK | 32 activos | 27,612 columnas
df_c2 | qg_W3 | chunk 03/16 OK | 32 activos | 27,644 columnas
df_c2 | qg_W3 | chunk 04/16 OK | 32 activos | 27,676 columnas
df_c2 | qg_W3 | chunk 05/16 OK | 32 activos | 27,708 columnas
df_c2 | qg_W3 | chunk 06/16 OK | 32 activos | 27,740 columnas
df_c2 | qg_W3 | chunk 07/16 OK | 32 activos | 27,772 columnas
df_c2 | qg_W3 | chunk 08/16 OK | 32 activos | 27,804 columnas
df_c2 | qg_W3 | chunk 09/16 OK | 32 activos | 27,836 columnas
df_c2 | qg_W3 | chunk 10/16 OK | 32 activos | 27,868 columnas
df_c2 | qg_W3 | chunk 11/16 OK | 32 activos | 27,900 columnas
df_c2 | qg_W3 | chunk 12/16 OK | 32 activos | 27,932 columnas
df_c2 | qg_W3 | chunk 13/16 OK | 32 activos | 27,964 columnas
df_c2 | qg_W3 | chunk 14/16 OK | 32 activos | 27,996 columnas
df_c2 | qg_W3 | chunk 15/16 OK | 32 activos | 28,028 columnas
df_c2 | qg_W3 | chunk 16/16 OK | 30 activos | 28,058 columnas
df_c2 | qg_W12 denominador | chunk 01/16 OK
df_c2 | qg_W12 denominador | chunk 02/16 OK
df_c2 | qg_W12 denominador | chunk 03/16 OK
df_c2 | qg_W12 denominador | chunk 04/16 OK
df_c2 | qg_W12 denominador | chunk 05/16 OK
df_c2 | qg_W12 denominador | chunk 06/16 OK
df_c2 | qg_W12 denominador | chunk 07/16 OK
df_c2 | qg_W12 denominador | chunk 08/16 OK
df_c2 | qg_W12 denominador | chunk 09/16 OK
df_c2 | qg_W12 denominador | chunk 10/16 OK
df_c2 | qg_W12 denominador | chunk 11/16 OK
df_c2 | qg_W12 denominador | chunk 12/16 OK
df_c2 | qg_W12 denominador | chunk 13/16 OK
df_c2 | qg_W12 denominador | chunk 14/16 OK
df_c2 | qg_W12 denominador | chunk 15/16 OK
df_c2 | qg_W12 denominador | chunk 16/16 OK
df_c2 | qg_W12 | chunk 01/16 OK | 32 activos | 28,090 columnas
df_c2 | qg_W12 | chunk 02/16 OK | 32 activos | 28,122 columnas
df_c2 | qg_W12 | chunk 03/16 OK | 32 activos | 28,154 columnas
df_c2 | qg_W12 | chunk 04/16 OK | 32 activos | 28,186 columnas
df_c2 | qg_W12 | chunk 05/16 OK | 32 activos | 28,218 columnas
df_c2 | qg_W12 | chunk 06/16 OK | 32 activos | 28,250 columnas
df_c2 | qg_W12 | chunk 07/16 OK | 32 activos | 28,282 columnas
df_c2 | qg_W12 | chunk 08/16 OK | 32 activos | 28,314 columnas
df_c2 | qg_W12 | chunk 09/16 OK | 32 activos | 28,346 columnas
df_c2 | qg_W12 | chunk 10/16 OK | 32 activos | 28,378 columnas
df_c2 | qg_W12 | chunk 11/16 OK | 32 activos | 28,410 columnas
df_c2 | qg_W12 | chunk 12/16 OK | 32 activos | 28,442 columnas
df_c2 | qg_W12 | chunk 13/16 OK | 32 activos | 28,474 columnas
df_c2 | qg_W12 | chunk 14/16 OK | 32 activos | 28,506 columnas
df_c2 | qg_W12 | chunk 15/16 OK | 32 activos | 28,538 columnas
df_c2 | qg_W12 | chunk 16/16 OK | 30 activos | 28,568 columnas
df_c2 | qg_W72 denominador | chunk 01/16 OK
df_c2 | qg_W72 denominador | chunk 02/16 OK
df_c2 | qg_W72 denominador | chunk 03/16 OK
df_c2 | qg_W72 denominador | chunk 04/16 OK
df_c2 | qg_W72 denominador | chunk 05/16 OK
df_c2 | qg_W72 denominador | chunk 06/16 OK
df_c2 | qg_W72 denominador | chunk 07/16 OK
df_c2 | qg_W72 denominador | chunk 08/16 OK
df_c2 | qg_W72 denominador | chunk 09/16 OK
df_c2 | qg_W72 denominador | chunk 10/16 OK
df_c2 | qg_W72 denominador | chunk 11/16 OK
df_c2 | qg_W72 denominador | chunk 12/16 OK
df_c2 | qg_W72 denominador | chunk 13/16 OK
df_c2 | qg_W72 denominador | chunk 14/16 OK
df_c2 | qg_W72 denominador | chunk 15/16 OK
df_c2 | qg_W72 denominador | chunk 16/16 OK
df_c2 | qg_W72 | chunk 01/16 OK | 32 activos | 28,600 columnas
df_c2 | qg_W72 | chunk 02/16 OK | 32 activos | 28,632 columnas
df_c2 | qg_W72 | chunk 03/16 OK | 32 activos | 28,664 columnas
df_c2 | qg_W72 | chunk 04/16 OK | 32 activos | 28,696 columnas
df_c2 | qg_W72 | chunk 05/16 OK | 32 activos | 28,728 columnas
df_c2 | qg_W72 | chunk 06/16 OK | 32 activos | 28,760 columnas
df_c2 | qg_W72 | chunk 07/16 OK | 32 activos | 28,792 columnas
df_c2 | qg_W72 | chunk 08/16 OK | 32 activos | 28,824 columnas
df_c2 | qg_W72 | chunk 09/16 OK | 32 activos | 28,856 columnas
df_c2 | qg_W72 | chunk 10/16 OK | 32 activos | 28,888 columnas
df_c2 | qg_W72 | chunk 11/16 OK | 32 activos | 28,920 columnas
df_c2 | qg_W72 | chunk 12/16 OK | 32 activos | 28,952 columnas
df_c2 | qg_W72 | chunk 13/16 OK | 32 activos | 28,984 columnas
df_c2 | qg_W72 | chunk 14/16 OK | 32 activos | 29,016 columnas
df_c2 | qg_W72 | chunk 15/16 OK | 32 activos | 29,048 columnas
df_c2 | qg_W72 | chunk 16/16 OK | 30 activos | 29,078 columnas
df_c2 | qg_W288 denominador | chunk 01/16 OK
df_c2 | qg_W288 denominador | chunk 02/16 OK
df_c2 | qg_W288 denominador | chunk 03/16 OK
df_c2 | qg_W288 denominador | chunk 04/16 OK
df_c2 | qg_W288 denominador | chunk 05/16 OK
df_c2 | qg_W288 denominador | chunk 06/16 OK
df_c2 | qg_W288 denominador | chunk 07/16 OK
df_c2 | qg_W288 denominador | chunk 08/16 OK
df_c2 | qg_W288 denominador | chunk 09/16 OK
df_c2 | qg_W288 denominador | chunk 10/16 OK
df_c2 | qg_W288 denominador | chunk 11/16 OK
df_c2 | qg_W288 denominador | chunk 12/16 OK
df_c2 | qg_W288 denominador | chunk 13/16 OK
df_c2 | qg_W288 denominador | chunk 14/16 OK
df_c2 | qg_W288 denominador | chunk 15/16 OK
df_c2 | qg_W288 denominador | chunk 16/16 OK
df_c2 | qg_W288 | chunk 01/16 OK | 32 activos | 29,110 columnas
df_c2 | qg_W288 | chunk 02/16 OK | 32 activos | 29,142 columnas
df_c2 | qg_W288 | chunk 03/16 OK | 32 activos | 29,174 columnas
df_c2 | qg_W288 | chunk 04/16 OK | 32 activos | 29,206 columnas
df_c2 | qg_W288 | chunk 05/16 OK | 32 activos | 29,238 columnas
df_c2 | qg_W288 | chunk 06/16 OK | 32 activos | 29,270 columnas
df_c2 | qg_W288 | chunk 07/16 OK | 32 activos | 29,302 columnas
df_c2 | qg_W288 | chunk 08/16 OK | 32 activos | 29,334 columnas
df_c2 | qg_W288 | chunk 09/16 OK | 32 activos | 29,366 columnas
df_c2 | qg_W288 | chunk 10/16 OK | 32 activos | 29,398 columnas
df_c2 | qg_W288 | chunk 11/16 OK | 32 activos | 29,430 columnas
df_c2 | qg_W288 | chunk 12/16 OK | 32 activos | 29,462 columnas
df_c2 | qg_W288 | chunk 13/16 OK | 32 activos | 29,494 columnas
df_c2 | qg_W288 | chunk 14/16 OK | 32 activos | 29,526 columnas
df_c2 | qg_W288 | chunk 15/16 OK | 32 activos | 29,558 columnas
df_c2 | qg_W288 | chunk 16/16 OK | 30 activos | 29,588 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 01/16 OK | 32 activos | 29,620 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 02/16 OK | 32 activos | 29,652 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 03/16 OK | 32 activos | 29,684 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 04/16 OK | 32 activos | 29,716 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 05/16 OK | 32 activos | 29,748 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 06/16 OK | 32 activos | 29,780 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 07/16 OK | 32 activos | 29,812 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 08/16 OK | 32 activos | 29,844 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 09/16 OK | 32 activos | 29,876 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 10/16 OK | 32 activos | 29,908 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 11/16 OK | 32 activos | 29,940 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 12/16 OK | 32 activos | 29,972 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 13/16 OK | 32 activos | 30,004 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 14/16 OK | 32 activos | 30,036 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 15/16 OK | 32 activos | 30,068 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c2 | NEST | chunk 16/16 OK | 30 activos | 30,098 columnas

df_c2 COMPLETO | 43,776 filas × 30,098 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_gp_fgp_nmetrics_nrank_qg_nest.parquet

======================================================================
df_c3 | 44,064 filas × 27,038 columnas | 16 chunks
======================================================================
df_c3 | NRANK | chunk 01/16 OK | 32 activos | 27,070 columnas
df_c3 | NRANK | chunk 02/16 OK | 32 activos | 27,102 columnas
df_c3 | NRANK | chunk 03/16 OK | 32 activos | 27,134 columnas
df_c3 | NRANK | chunk 04/16 OK | 32 activos | 27,166 columnas
df_c3 | NRANK | chunk 05/16 OK | 32 activos | 27,198 columnas
df_c3 | NRANK | chunk 06/16 OK | 32 activos | 27,230 columnas
df_c3 | NRANK | chunk 07/16 OK | 32 activos | 27,262 columnas
df_c3 | NRANK | chunk 08/16 OK | 32 activos | 27,294 columnas
df_c3 | NRANK | chunk 09/16 OK | 32 activos | 27,326 columnas
df_c3 | NRANK | chunk 10/16 OK | 32 activos | 27,358 columnas
df_c3 | NRANK | chunk 11/16 OK | 32 activos | 27,390 columnas
df_c3 | NRANK | chunk 12/16 OK | 32 activos | 27,422 columnas
df_c3 | NRANK | chunk 13/16 OK | 32 activos | 27,454 columnas
df_c3 | NRANK | chunk 14/16 OK | 32 activos | 27,486 columnas
df_c3 | NRANK | chunk 15/16 OK | 32 activos | 27,518 columnas
df_c3 | NRANK | chunk 16/16 OK | 30 activos | 27,548 columnas
df_c3 | qg_W3 denominador | chunk 01/16 OK
df_c3 | qg_W3 denominador | chunk 02/16 OK
df_c3 | qg_W3 denominador | chunk 03/16 OK
df_c3 | qg_W3 denominador | chunk 04/16 OK
df_c3 | qg_W3 denominador | chunk 05/16 OK
df_c3 | qg_W3 denominador | chunk 06/16 OK
df_c3 | qg_W3 denominador | chunk 07/16 OK
df_c3 | qg_W3 denominador | chunk 08/16 OK
df_c3 | qg_W3 denominador | chunk 09/16 OK
df_c3 | qg_W3 denominador | chunk 10/16 OK
df_c3 | qg_W3 denominador | chunk 11/16 OK
df_c3 | qg_W3 denominador | chunk 12/16 OK
df_c3 | qg_W3 denominador | chunk 13/16 OK
df_c3 | qg_W3 denominador | chunk 14/16 OK
df_c3 | qg_W3 denominador | chunk 15/16 OK
df_c3 | qg_W3 denominador | chunk 16/16 OK
df_c3 | qg_W3 | chunk 01/16 OK | 32 activos | 27,580 columnas
df_c3 | qg_W3 | chunk 02/16 OK | 32 activos | 27,612 columnas
df_c3 | qg_W3 | chunk 03/16 OK | 32 activos | 27,644 columnas
df_c3 | qg_W3 | chunk 04/16 OK | 32 activos | 27,676 columnas
df_c3 | qg_W3 | chunk 05/16 OK | 32 activos | 27,708 columnas
df_c3 | qg_W3 | chunk 06/16 OK | 32 activos | 27,740 columnas
df_c3 | qg_W3 | chunk 07/16 OK | 32 activos | 27,772 columnas
df_c3 | qg_W3 | chunk 08/16 OK | 32 activos | 27,804 columnas
df_c3 | qg_W3 | chunk 09/16 OK | 32 activos | 27,836 columnas
df_c3 | qg_W3 | chunk 10/16 OK | 32 activos | 27,868 columnas
df_c3 | qg_W3 | chunk 11/16 OK | 32 activos | 27,900 columnas
df_c3 | qg_W3 | chunk 12/16 OK | 32 activos | 27,932 columnas
df_c3 | qg_W3 | chunk 13/16 OK | 32 activos | 27,964 columnas
df_c3 | qg_W3 | chunk 14/16 OK | 32 activos | 27,996 columnas
df_c3 | qg_W3 | chunk 15/16 OK | 32 activos | 28,028 columnas
df_c3 | qg_W3 | chunk 16/16 OK | 30 activos | 28,058 columnas
df_c3 | qg_W12 denominador | chunk 01/16 OK
df_c3 | qg_W12 denominador | chunk 02/16 OK
df_c3 | qg_W12 denominador | chunk 03/16 OK
df_c3 | qg_W12 denominador | chunk 04/16 OK
df_c3 | qg_W12 denominador | chunk 05/16 OK
df_c3 | qg_W12 denominador | chunk 06/16 OK
df_c3 | qg_W12 denominador | chunk 07/16 OK
df_c3 | qg_W12 denominador | chunk 08/16 OK
df_c3 | qg_W12 denominador | chunk 09/16 OK
df_c3 | qg_W12 denominador | chunk 10/16 OK
df_c3 | qg_W12 denominador | chunk 11/16 OK
df_c3 | qg_W12 denominador | chunk 12/16 OK
df_c3 | qg_W12 denominador | chunk 13/16 OK
df_c3 | qg_W12 denominador | chunk 14/16 OK
df_c3 | qg_W12 denominador | chunk 15/16 OK
df_c3 | qg_W12 denominador | chunk 16/16 OK
df_c3 | qg_W12 | chunk 01/16 OK | 32 activos | 28,090 columnas
df_c3 | qg_W12 | chunk 02/16 OK | 32 activos | 28,122 columnas
df_c3 | qg_W12 | chunk 03/16 OK | 32 activos | 28,154 columnas
df_c3 | qg_W12 | chunk 04/16 OK | 32 activos | 28,186 columnas
df_c3 | qg_W12 | chunk 05/16 OK | 32 activos | 28,218 columnas
df_c3 | qg_W12 | chunk 06/16 OK | 32 activos | 28,250 columnas
df_c3 | qg_W12 | chunk 07/16 OK | 32 activos | 28,282 columnas
df_c3 | qg_W12 | chunk 08/16 OK | 32 activos | 28,314 columnas
df_c3 | qg_W12 | chunk 09/16 OK | 32 activos | 28,346 columnas
df_c3 | qg_W12 | chunk 10/16 OK | 32 activos | 28,378 columnas
df_c3 | qg_W12 | chunk 11/16 OK | 32 activos | 28,410 columnas
df_c3 | qg_W12 | chunk 12/16 OK | 32 activos | 28,442 columnas
df_c3 | qg_W12 | chunk 13/16 OK | 32 activos | 28,474 columnas
df_c3 | qg_W12 | chunk 14/16 OK | 32 activos | 28,506 columnas
df_c3 | qg_W12 | chunk 15/16 OK | 32 activos | 28,538 columnas
df_c3 | qg_W12 | chunk 16/16 OK | 30 activos | 28,568 columnas
df_c3 | qg_W72 denominador | chunk 01/16 OK
df_c3 | qg_W72 denominador | chunk 02/16 OK
df_c3 | qg_W72 denominador | chunk 03/16 OK
df_c3 | qg_W72 denominador | chunk 04/16 OK
df_c3 | qg_W72 denominador | chunk 05/16 OK
df_c3 | qg_W72 denominador | chunk 06/16 OK
df_c3 | qg_W72 denominador | chunk 07/16 OK
df_c3 | qg_W72 denominador | chunk 08/16 OK
df_c3 | qg_W72 denominador | chunk 09/16 OK
df_c3 | qg_W72 denominador | chunk 10/16 OK
df_c3 | qg_W72 denominador | chunk 11/16 OK
df_c3 | qg_W72 denominador | chunk 12/16 OK
df_c3 | qg_W72 denominador | chunk 13/16 OK
df_c3 | qg_W72 denominador | chunk 14/16 OK
df_c3 | qg_W72 denominador | chunk 15/16 OK
df_c3 | qg_W72 denominador | chunk 16/16 OK
df_c3 | qg_W72 | chunk 01/16 OK | 32 activos | 28,600 columnas
df_c3 | qg_W72 | chunk 02/16 OK | 32 activos | 28,632 columnas
df_c3 | qg_W72 | chunk 03/16 OK | 32 activos | 28,664 columnas
df_c3 | qg_W72 | chunk 04/16 OK | 32 activos | 28,696 columnas
df_c3 | qg_W72 | chunk 05/16 OK | 32 activos | 28,728 columnas
df_c3 | qg_W72 | chunk 06/16 OK | 32 activos | 28,760 columnas
df_c3 | qg_W72 | chunk 07/16 OK | 32 activos | 28,792 columnas
df_c3 | qg_W72 | chunk 08/16 OK | 32 activos | 28,824 columnas
df_c3 | qg_W72 | chunk 09/16 OK | 32 activos | 28,856 columnas
df_c3 | qg_W72 | chunk 10/16 OK | 32 activos | 28,888 columnas
df_c3 | qg_W72 | chunk 11/16 OK | 32 activos | 28,920 columnas
df_c3 | qg_W72 | chunk 12/16 OK | 32 activos | 28,952 columnas
df_c3 | qg_W72 | chunk 13/16 OK | 32 activos | 28,984 columnas
df_c3 | qg_W72 | chunk 14/16 OK | 32 activos | 29,016 columnas
df_c3 | qg_W72 | chunk 15/16 OK | 32 activos | 29,048 columnas
df_c3 | qg_W72 | chunk 16/16 OK | 30 activos | 29,078 columnas
df_c3 | qg_W288 denominador | chunk 01/16 OK
df_c3 | qg_W288 denominador | chunk 02/16 OK
df_c3 | qg_W288 denominador | chunk 03/16 OK
df_c3 | qg_W288 denominador | chunk 04/16 OK
df_c3 | qg_W288 denominador | chunk 05/16 OK
df_c3 | qg_W288 denominador | chunk 06/16 OK
df_c3 | qg_W288 denominador | chunk 07/16 OK
df_c3 | qg_W288 denominador | chunk 08/16 OK
df_c3 | qg_W288 denominador | chunk 09/16 OK
df_c3 | qg_W288 denominador | chunk 10/16 OK
df_c3 | qg_W288 denominador | chunk 11/16 OK
df_c3 | qg_W288 denominador | chunk 12/16 OK
df_c3 | qg_W288 denominador | chunk 13/16 OK
df_c3 | qg_W288 denominador | chunk 14/16 OK
df_c3 | qg_W288 denominador | chunk 15/16 OK
df_c3 | qg_W288 denominador | chunk 16/16 OK
df_c3 | qg_W288 | chunk 01/16 OK | 32 activos | 29,110 columnas
df_c3 | qg_W288 | chunk 02/16 OK | 32 activos | 29,142 columnas
df_c3 | qg_W288 | chunk 03/16 OK | 32 activos | 29,174 columnas
df_c3 | qg_W288 | chunk 04/16 OK | 32 activos | 29,206 columnas
df_c3 | qg_W288 | chunk 05/16 OK | 32 activos | 29,238 columnas
df_c3 | qg_W288 | chunk 06/16 OK | 32 activos | 29,270 columnas
df_c3 | qg_W288 | chunk 07/16 OK | 32 activos | 29,302 columnas
df_c3 | qg_W288 | chunk 08/16 OK | 32 activos | 29,334 columnas
df_c3 | qg_W288 | chunk 09/16 OK | 32 activos | 29,366 columnas
df_c3 | qg_W288 | chunk 10/16 OK | 32 activos | 29,398 columnas
df_c3 | qg_W288 | chunk 11/16 OK | 32 activos | 29,430 columnas
df_c3 | qg_W288 | chunk 12/16 OK | 32 activos | 29,462 columnas
df_c3 | qg_W288 | chunk 13/16 OK | 32 activos | 29,494 columnas
df_c3 | qg_W288 | chunk 14/16 OK | 32 activos | 29,526 columnas
df_c3 | qg_W288 | chunk 15/16 OK | 32 activos | 29,558 columnas
df_c3 | qg_W288 | chunk 16/16 OK | 30 activos | 29,588 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 01/16 OK | 32 activos | 29,620 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 02/16 OK | 32 activos | 29,652 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 03/16 OK | 32 activos | 29,684 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 04/16 OK | 32 activos | 29,716 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 05/16 OK | 32 activos | 29,748 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 06/16 OK | 32 activos | 29,780 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 07/16 OK | 32 activos | 29,812 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 08/16 OK | 32 activos | 29,844 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 09/16 OK | 32 activos | 29,876 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 10/16 OK | 32 activos | 29,908 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 11/16 OK | 32 activos | 29,940 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 12/16 OK | 32 activos | 29,972 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 13/16 OK | 32 activos | 30,004 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 14/16 OK | 32 activos | 30,036 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 15/16 OK | 32 activos | 30,068 columnas

/tmp/ipykernel_13441/23700742.py:352: RuntimeWarning: Degrees of freedom <= 0 for slice.
  variance = np.nanvar(

df_c3 | NEST | chunk 16/16 OK | 30 activos | 30,098 columnas

df_c3 COMPLETO | 44,064 filas × 30,098 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_gp_fgp_nmetrics_nrank_qg_nest.parquet

======================================================================
ESTADO FINAL
======================================================================
Último dataset: df_c3
Última etapa: NEST
Chunks confirmados en la etapa: 16/16

Datasets completados: df_c1, df_c2, df_c3

Archivos guardados exitosamente:
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_gp_fgp_nmetrics_nrank_qg_nest.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_gp_fgp_nmetrics_nrank_qg_nest.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_gp_fgp_nmetrics_nrank_qg_nest.parquet

In [49]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43775 entries, 0 to 43774
Columns: 30098 entries, bar_end to 币安人生__NEST
dtypes: datetime64[ns, UTC](1), float32(29077), int8(1020)
memory usage: 4.8 GB
<class 'pandas.core.frame.DataFrame'>
Index: 43776 entries, 43775 to 87550
Columns: 30098 entries, bar_end to 币安人生__NEST
dtypes: datetime64[ns, UTC](1), float32(29077), int8(1020)
memory usage: 4.8 GB
<class 'pandas.core.frame.DataFrame'>
Index: 44064 entries, 87551 to 131614
Columns: 30098 entries, bar_end to 币安人生__NEST
dtypes: datetime64[ns, UTC](1), float32(29077), int8(1020)
memory usage: 4.8 GB

##11. N, energia y target
- N_context
N_ctx= softplus(fn(("NSTAB","NPERS","NCOH", "NRET", NRANK","NEST",...)))
Estimacion de neguentropia

- N_theory
N_th= f(gp_proxy)/-ln(yp)
Estimacion teorica indice de neguentropia, sobre todo por el gp esto es todavia un proy

- E_context
E_ctx = gp/N_ctx + epsilon
Potencial neguentropico independiente del simplex

- E_theory
E_th = gp/N_th + epsilon
Potencial del proxy del indice teorico

- TARGET_yp_t1 = yp_t+1

In [50]:
from pathlib import Path
import os
import gc


# ============================================================
# DATASETS DE TRABAJO
# ============================================================

DATASETS = {
    "df_c1": df_c1,
    "df_c2": df_c2,
    "df_c3": df_c3,
}


# ============================================================
# ARCHIVOS DE SALIDA
# ============================================================

ruta = Path(
    "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"
)

OUTPUTS = {
    "df_c1": ruta / "112024-042025_clean_add_final.parquet",
    "df_c2": ruta / "042025-092025_clean_add_final.parquet",
    "df_c3": ruta / "092025-022026_clean_add_final.parquet",
}


# ============================================================
# INPUTS N_context
# ============================================================

N_inputs = (
    "NSTAB",
    "NPERS",
    "NCOH",
    "NRET",
    "NRANK",
    "NEST",
)


# ============================================================
# CONTROL DE PROCESO
# ============================================================

saved_files = []
completed_datasets = []

current_dataset = None
current_stage = None
current_chunk = 0
total_chunks = 0


try:

    for dataset_name, DATASET in DATASETS.items():

        current_dataset = dataset_name
        current_stage = "N_context / N_theory / Energía / TARGET"

        asset_chunks = list(
            chunks(
                assets,
                cfg.asset_block_size
            )
        )

        total_chunks = len(asset_chunks)
        current_chunk = 0

        print("\n" + "=" * 70)
        print(
            f"{dataset_name} | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas | "
            f"{total_chunks} chunks"
        )
        print("=" * 70)


        for i, chunk in enumerate(
            asset_chunks,
            start=1
        ):

            # ========================================================
            # N_context
            # ========================================================

            components = [
                load_feature(
                    DATASET,
                    chunk,
                    feature
                )
                for feature in N_inputs
            ]

            N_context = composite_positive_proxy(
                components,
                cfg
            )


            # ========================================================
            # N_theory
            # ========================================================

            fgp = load_feature(
                DATASET,
                chunk,
                "fgp_nested"
            )

            yp = load_base(
                DATASET,
                chunk,
                "yp",
                cfg
            )

            yp_safe = yp.clip(
                lower=cfg.eps,
                upper=1.0
            )

            surprise = -np.log(
                yp_safe
            )

            N_theory = (
                fgp
                /
                (surprise + cfg.eps)
            )


            # ========================================================
            # Energía
            # ========================================================

            gp = load_feature(
                DATASET,
                chunk,
                "gp"
            )

            E_context = (
                gp
                /
                (N_context + cfg.eps)
            )

            E_theory = (
                gp
                /
                (N_theory + cfg.eps)
            )


            # ========================================================
            # TARGET t+1
            # ÚNICA VARIABLE QUE MIRA HACIA ADELANTE
            # ========================================================

            target = yp.shift(-1)

            target.columns = [
                f"{a}__TARGET_yp_t1"
                for a in chunk
            ]


            # ========================================================
            # PREPARACIÓN DEL CHUNK
            # ========================================================

            chunk_blocks = [
                name_block(
                    N_context,
                    "N_context",
                    cfg
                ),

                name_block(
                    N_theory,
                    "N_theory",
                    cfg
                ),

                name_block(
                    E_context,
                    "E_context",
                    cfg
                ),

                name_block(
                    E_theory,
                    "E_theory",
                    cfg
                ),

                target.astype(
                    cfg.dtype
                ),
            ]


            # ========================================================
            # COMMIT DEL CHUNK
            # Solo se ejecuta si TODO el chunk terminó correctamente
            # ========================================================

            DATASET = merge_blocks(
                DATASET,
                chunk_blocks
            )

            DATASETS[dataset_name] = DATASET
            globals()[dataset_name] = DATASET

            current_chunk = i

            print(
                f"{dataset_name} | "
                f"chunk {i:02d}/{total_chunks} OK | "
                f"{len(chunk):02d} activos | "
                f"{DATASET.shape[1]:,} columnas"
            )


            del (
                components,
                N_context,
                fgp,
                yp,
                yp_safe,
                surprise,
                N_theory,
                gp,
                E_context,
                E_theory,
                target,
                chunk_blocks,
            )

            gc.collect()


        # ============================================================
        # GUARDADO DEL DATASET COMPLETO
        # ============================================================

        output_file = OUTPUTS[dataset_name]

        temp_file = output_file.with_suffix(
            ".tmp.parquet"
        )

        DATASET.to_parquet(
            temp_file,
            index=False
        )

        os.replace(
            temp_file,
            output_file
        )

        saved_files.append(
            str(output_file)
        )

        completed_datasets.append(
            dataset_name
        )

        print(
            f"\n{dataset_name} COMPLETO | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas"
        )

        print(
            f"Guardado: {output_file}"
        )


except KeyboardInterrupt:

    print(
        "\nPROCESO INTERRUMPIDO MANUALMENTE"
    )


except Exception as e:

    print(
        f"\nERROR: "
        f"{type(e).__name__}: {e}"
    )


finally:

    # ============================================================
    # ESTADO FINAL
    # ============================================================

    print("\n" + "=" * 70)
    print("ESTADO FINAL")
    print("=" * 70)


    if current_dataset is not None:

        print(
            f"Último dataset: {current_dataset}"
        )

        print(
            f"Última etapa: {current_stage}"
        )

        print(
            f"Chunks confirmados en la etapa: "
            f"{current_chunk}/{total_chunks}"
        )


    if completed_datasets:

        print(
            "\nDatasets completados:",
            ", ".join(
                completed_datasets
            )
        )

    else:

        print(
            "\nDatasets completados: ninguno"
        )


    if saved_files:

        print(
            "\nArchivos guardados exitosamente:"
        )

        for file in saved_files:

            print(
                f"  ✓ {file}"
            )

    else:

        print(
            "\nArchivos completos guardados: ninguno"
        )

======================================================================
df_c1 | 43,775 filas × 30,098 columnas | 16 chunks
======================================================================

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 01/16 OK | 32 activos | 30,258 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 02/16 OK | 32 activos | 30,418 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 03/16 OK | 32 activos | 30,578 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 04/16 OK | 32 activos | 30,738 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 05/16 OK | 32 activos | 30,898 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 06/16 OK | 32 activos | 31,058 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 07/16 OK | 32 activos | 31,218 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 08/16 OK | 32 activos | 31,378 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 09/16 OK | 32 activos | 31,538 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 10/16 OK | 32 activos | 31,698 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 11/16 OK | 32 activos | 31,858 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 12/16 OK | 32 activos | 32,018 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 13/16 OK | 32 activos | 32,178 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 14/16 OK | 32 activos | 32,338 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 15/16 OK | 32 activos | 32,498 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c1 | chunk 16/16 OK | 30 activos | 32,648 columnas

df_c1 COMPLETO | 43,775 filas × 32,648 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_final.parquet

======================================================================
df_c2 | 43,776 filas × 30,098 columnas | 16 chunks
======================================================================

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 01/16 OK | 32 activos | 30,258 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 02/16 OK | 32 activos | 30,418 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 03/16 OK | 32 activos | 30,578 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 04/16 OK | 32 activos | 30,738 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 05/16 OK | 32 activos | 30,898 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 06/16 OK | 32 activos | 31,058 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 07/16 OK | 32 activos | 31,218 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 08/16 OK | 32 activos | 31,378 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 09/16 OK | 32 activos | 31,538 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 10/16 OK | 32 activos | 31,698 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 11/16 OK | 32 activos | 31,858 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 12/16 OK | 32 activos | 32,018 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 13/16 OK | 32 activos | 32,178 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 14/16 OK | 32 activos | 32,338 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 15/16 OK | 32 activos | 32,498 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c2 | chunk 16/16 OK | 30 activos | 32,648 columnas

df_c2 COMPLETO | 43,776 filas × 32,648 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_final.parquet

======================================================================
df_c3 | 44,064 filas × 30,098 columnas | 16 chunks
======================================================================

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 01/16 OK | 32 activos | 30,258 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 02/16 OK | 32 activos | 30,418 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 03/16 OK | 32 activos | 30,578 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 04/16 OK | 32 activos | 30,738 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 05/16 OK | 32 activos | 30,898 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 06/16 OK | 32 activos | 31,058 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 07/16 OK | 32 activos | 31,218 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 08/16 OK | 32 activos | 31,378 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 09/16 OK | 32 activos | 31,538 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 10/16 OK | 32 activos | 31,698 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 11/16 OK | 32 activos | 31,858 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 12/16 OK | 32 activos | 32,018 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 13/16 OK | 32 activos | 32,178 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 14/16 OK | 32 activos | 32,338 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 15/16 OK | 32 activos | 32,498 columnas

/tmp/ipykernel_13441/1000353780.py:466: RuntimeWarning: invalid value encountered in logaddexp
  values = np.logaddexp(

df_c3 | chunk 16/16 OK | 30 activos | 32,648 columnas

df_c3 COMPLETO | 44,064 filas × 32,648 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_final.parquet

======================================================================
ESTADO FINAL
======================================================================
Último dataset: df_c3
Última etapa: N_context / N_theory / Energía / TARGET
Chunks confirmados en la etapa: 16/16

Datasets completados: df_c1, df_c2, df_c3

Archivos guardados exitosamente:
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_final.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_final.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_final.parquet

### 8 checkpoint

In [2]:
ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

df_c1 = pd.read_parquet(ruta + "112024-042025_clean_add_final.parquet")
df_c2 = pd.read_parquet(ruta + "042025-092025_clean_add_final.parquet")
df_c3 = pd.read_parquet(ruta + "092025-022026_clean_add_final.parquet")

In [3]:
from numba import njit, prange

In [4]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# DATASET DE TRABAJO
# ============================================================

DATASET = df_c1


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    primary_window: int = 288
    min_periods: int = 72
    ewm_span: int = 72

    multiscale_windows: tuple[int, ...] = (
        3,
        12,
        72,
        288,
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):

    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

@njit(parallel=True)
def _recovery_speed_numba(
    g,
    s,
    q,
    b,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    T, N = g.shape
    output = np.full((T, N), np.nan, dtype=np.float64)

    for j in prange(N):
        in_event = False
        event_start = -1
        event_baseline = np.nan
        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):
            if not in_event:
                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):
                    in_event = True
                    event_start = t
                    event_baseline = b[t, j]
                    consecutive = 0

            elif np.isfinite(g[t, j]):
                distance = abs(g[t, j] - event_baseline) / (
                    abs(event_baseline) + eps
                )

                if distance <= tolerance:
                    consecutive += 1
                else:
                    consecutive = 0

                if consecutive >= hold_bars:
                    recovery_start = t - hold_bars + 1
                    duration = max(1, recovery_start - event_start)

                    if np.isnan(duration_ewma):
                        duration_ewma = float(duration)
                    else:
                        duration_ewma = (
                            alpha * duration
                            + (1.0 - alpha) * duration_ewma
                        )

                    in_event = False
                    event_start = -1
                    event_baseline = np.nan
                    consecutive = 0

            if np.isfinite(duration_ewma):
                output[t, j] = 1.0 / (1.0 + duration_ewma)

    return output


def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    frames = (stress, stress_threshold, baseline)

    if any(
        not gp0.index.equals(x.index)
        or not gp0.columns.equals(x.columns)
        for x in frames
    ):
        raise ValueError(
            "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
        )

    output = _recovery_speed_numba(
        gp0.to_numpy(dtype=np.float64, copy=False),
        stress.to_numpy(dtype=np.float64, copy=False),
        stress_threshold.to_numpy(dtype=np.float64, copy=False),
        baseline.to_numpy(dtype=np.float64, copy=False),
        tolerance,
        hold_bars,
        alpha,
        eps,
    )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns,
    )

# ============================================================
# INICIALIZACIÓN
# ============================================================

DATASET = validate_time(DATASET, cfg)

assets = discover_assets(
    DATASET,
    cfg
)

print("Dataset:", DATASET.shape)
print("Activos detectados:", len(assets))

Dataset: (43775, 32648)
Activos detectados: 510

In [5]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# DATASET DE TRABAJO
# ============================================================

DATASET = df_c2


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    primary_window: int = 288
    min_periods: int = 72
    ewm_span: int = 72

    multiscale_windows: tuple[int, ...] = (
        3,
        12,
        72,
        288,
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):

    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

@njit(parallel=True)
def _recovery_speed_numba(
    g,
    s,
    q,
    b,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    T, N = g.shape
    output = np.full((T, N), np.nan, dtype=np.float64)

    for j in prange(N):
        in_event = False
        event_start = -1
        event_baseline = np.nan
        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):
            if not in_event:
                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):
                    in_event = True
                    event_start = t
                    event_baseline = b[t, j]
                    consecutive = 0

            elif np.isfinite(g[t, j]):
                distance = abs(g[t, j] - event_baseline) / (
                    abs(event_baseline) + eps
                )

                if distance <= tolerance:
                    consecutive += 1
                else:
                    consecutive = 0

                if consecutive >= hold_bars:
                    recovery_start = t - hold_bars + 1
                    duration = max(1, recovery_start - event_start)

                    if np.isnan(duration_ewma):
                        duration_ewma = float(duration)
                    else:
                        duration_ewma = (
                            alpha * duration
                            + (1.0 - alpha) * duration_ewma
                        )

                    in_event = False
                    event_start = -1
                    event_baseline = np.nan
                    consecutive = 0

            if np.isfinite(duration_ewma):
                output[t, j] = 1.0 / (1.0 + duration_ewma)

    return output


def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    frames = (stress, stress_threshold, baseline)

    if any(
        not gp0.index.equals(x.index)
        or not gp0.columns.equals(x.columns)
        for x in frames
    ):
        raise ValueError(
            "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
        )

    output = _recovery_speed_numba(
        gp0.to_numpy(dtype=np.float64, copy=False),
        stress.to_numpy(dtype=np.float64, copy=False),
        stress_threshold.to_numpy(dtype=np.float64, copy=False),
        baseline.to_numpy(dtype=np.float64, copy=False),
        tolerance,
        hold_bars,
        alpha,
        eps,
    )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns,
    )

# ============================================================
# INICIALIZACIÓN
# ============================================================

DATASET = validate_time(DATASET, cfg)

assets = discover_assets(
    DATASET,
    cfg
)

print("Dataset:", DATASET.shape)
print("Activos detectados:", len(assets))

Dataset: (43776, 32648)
Activos detectados: 510

In [6]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# DATASET DE TRABAJO
# ============================================================

DATASET = df_c3


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    primary_window: int = 288
    min_periods: int = 72
    ewm_span: int = 72

    multiscale_windows: tuple[int, ...] = (
        3,
        12,
        72,
        288,
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):

    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

@njit(parallel=True)
def _recovery_speed_numba(
    g,
    s,
    q,
    b,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    T, N = g.shape
    output = np.full((T, N), np.nan, dtype=np.float64)

    for j in prange(N):
        in_event = False
        event_start = -1
        event_baseline = np.nan
        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):
            if not in_event:
                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):
                    in_event = True
                    event_start = t
                    event_baseline = b[t, j]
                    consecutive = 0

            elif np.isfinite(g[t, j]):
                distance = abs(g[t, j] - event_baseline) / (
                    abs(event_baseline) + eps
                )

                if distance <= tolerance:
                    consecutive += 1
                else:
                    consecutive = 0

                if consecutive >= hold_bars:
                    recovery_start = t - hold_bars + 1
                    duration = max(1, recovery_start - event_start)

                    if np.isnan(duration_ewma):
                        duration_ewma = float(duration)
                    else:
                        duration_ewma = (
                            alpha * duration
                            + (1.0 - alpha) * duration_ewma
                        )

                    in_event = False
                    event_start = -1
                    event_baseline = np.nan
                    consecutive = 0

            if np.isfinite(duration_ewma):
                output[t, j] = 1.0 / (1.0 + duration_ewma)

    return output


def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    frames = (stress, stress_threshold, baseline)

    if any(
        not gp0.index.equals(x.index)
        or not gp0.columns.equals(x.columns)
        for x in frames
    ):
        raise ValueError(
            "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
        )

    output = _recovery_speed_numba(
        gp0.to_numpy(dtype=np.float64, copy=False),
        stress.to_numpy(dtype=np.float64, copy=False),
        stress_threshold.to_numpy(dtype=np.float64, copy=False),
        baseline.to_numpy(dtype=np.float64, copy=False),
        tolerance,
        hold_bars,
        alpha,
        eps,
    )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns,
    )

# ============================================================
# INICIALIZACIÓN
# ============================================================

DATASET = validate_time(DATASET, cfg)

assets = discover_assets(
    DATASET,
    cfg
)

print("Dataset:", DATASET.shape)
print("Activos detectados:", len(assets))

Dataset: (44064, 32648)
Activos detectados: 510

In [7]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43775 entries, 0 to 43774
Columns: 32648 entries, bar_end to 币安人生__TARGET_yp_t1
dtypes: datetime64[ns, UTC](1), float32(31627), int8(1020)
memory usage: 5.2 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43776 entries, 0 to 43775
Columns: 32648 entries, bar_end to 币安人生__TARGET_yp_t1
dtypes: datetime64[ns, UTC](1), float32(31627), int8(1020)
memory usage: 5.2 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44064 entries, 0 to 44063
Columns: 32648 entries, bar_end to 币安人生__TARGET_yp_t1
dtypes: datetime64[ns, UTC](1), float32(31627), int8(1020)
memory usage: 5.2 GB

##12. Derivadas de E_Context

- Log-energia
Eth_logE = ln(gp)- ln(N)
Estabilidad numerica y seperabilida multiplicativa

- Energia relativa
Eth_Erel_i = Ei - Median_j(Ej)
Posicion relativa transaversal

- Velocidad Energetica
Et_dE = E_t - E_t-1
Cambio de estado energetico

- Aceleracion Energetica
Eth_ddE = Et_dE - Et-1_dE
Rupturas dinamicas

- Energia de schock
Eth_ESH = Z_w(E)
Desviacion energetica respecto a ventan W (regimen inexacto)

- Ranking de Energia
Eth_ERANK = PerncentialRank_j(Ej)
Posicion energética competitiva

In [8]:
from pathlib import Path
import os
import gc


# ============================================================
# DATASETS DE TRABAJO
# ============================================================

DATASETS = {
    "df_c1": df_c1,
    "df_c2": df_c2,
    "df_c3": df_c3,
}


# ============================================================
# ARCHIVOS DE SALIDA
# ============================================================

ruta = Path(
    "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"
)

OUTPUTS = {
    "df_c1": ruta / "112024-042025_clean_add_final_Ectx.parquet",
    "df_c2": ruta / "042025-092025_clean_add_final_Ectx.parquet",
    "df_c3": ruta / "092025-022026_clean_add_final_Ectx.parquet",
}


# ============================================================
# CONTROL DE PROCESO
# ============================================================

saved_files = []
completed_datasets = []

current_dataset = None
current_stage = None
current_chunk = 0
total_chunks = 0


try:

    for dataset_name, DATASET in DATASETS.items():

        current_dataset = dataset_name
        current_stage = "E_context features"

        asset_chunks = list(
            chunks(
                assets,
                cfg.asset_block_size
            )
        )

        total_chunks = len(asset_chunks)
        current_chunk = 0

        print("\n" + "=" * 70)
        print(
            f"{dataset_name} | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas | "
            f"{total_chunks} chunks"
        )
        print("=" * 70)


        # ============================================================
        # E_context GLOBAL
        # ============================================================

        E_all = load_feature(
            DATASET,
            assets,
            "E_context"
        ).astype("float32")


        A_all = load_base(
            DATASET,
            assets,
            "A",
            cfg
        ).astype("float32")


        E_active = E_all.where(
            A_all > 0
        )


        # --------------------------------------------
        # Estadísticos transversales
        # --------------------------------------------

        E_median = E_active.median(
            axis=1
        )

        E_rank = E_active.rank(
            axis=1,
            pct=True,
            method="average"
        )


        # ============================================================
        # CÁLCULO POR CHUNK
        # ============================================================

        for i, chunk in enumerate(
            asset_chunks,
            start=1
        ):

            E = E_all.loc[
                :,
                chunk
            ]


            # --------------------------------------------
            # Log energía
            # --------------------------------------------

            logE = np.log(
                E.clip(
                    lower=cfg.eps
                )
            )


            # --------------------------------------------
            # Energía relativa transversal
            # --------------------------------------------

            Erel = E.sub(
                E_median,
                axis=0
            )


            # --------------------------------------------
            # Primera diferencia
            # --------------------------------------------

            dE = E.diff()


            # --------------------------------------------
            # Segunda diferencia
            # --------------------------------------------

            ddE = dE.diff()


            # --------------------------------------------
            # Shock robusto causal
            # --------------------------------------------

            ESH = robust_z_causal(
                E,
                cfg.primary_window,
                cfg.min_periods,
                cfg.eps
            )


            # --------------------------------------------
            # Ranking transversal
            # --------------------------------------------

            ERANK = E_rank.loc[
                :,
                chunk
            ]


            # ========================================================
            # PREPARACIÓN DEL CHUNK
            # ========================================================

            chunk_blocks = [
                name_block(
                    logE,
                    "Ectx_logE",
                    cfg
                ),

                name_block(
                    Erel,
                    "Ectx_Erel",
                    cfg
                ),

                name_block(
                    dE,
                    "Ectx_dE",
                    cfg
                ),

                name_block(
                    ddE,
                    "Ectx_ddE",
                    cfg
                ),

                name_block(
                    ESH,
                    "Ectx_ESH",
                    cfg
                ),

                name_block(
                    ERANK,
                    "Ectx_ERANK",
                    cfg
                ),
            ]


            # ========================================================
            # COMMIT DEL CHUNK
            # Solo se ejecuta si TODO el chunk terminó correctamente
            # ========================================================

            DATASET = merge_blocks(
                DATASET,
                chunk_blocks
            )

            DATASETS[dataset_name] = DATASET
            globals()[dataset_name] = DATASET

            current_chunk = i

            print(
                f"{dataset_name} | "
                f"chunk {i:02d}/{total_chunks} OK | "
                f"{len(chunk):02d} activos | "
                f"{DATASET.shape[1]:,} columnas"
            )


            del (
                E,
                logE,
                Erel,
                dE,
                ddE,
                ESH,
                ERANK,
                chunk_blocks,
            )

            gc.collect()


        # ============================================================
        # LIMPIEZA DE OBJETOS GLOBALES DEL DATASET
        # ============================================================

        del (
            E_all,
            A_all,
            E_active,
            E_median,
            E_rank,
        )

        gc.collect()


        # ============================================================
        # GUARDADO DEL DATASET COMPLETO
        # ============================================================

        output_file = OUTPUTS[
            dataset_name
        ]

        temp_file = output_file.with_suffix(
            ".tmp.parquet"
        )

        DATASET.to_parquet(
            temp_file,
            index=False
        )

        os.replace(
            temp_file,
            output_file
        )

        saved_files.append(
            str(output_file)
        )

        completed_datasets.append(
            dataset_name
        )

        print(
            f"\n{dataset_name} COMPLETO | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas"
        )

        print(
            f"Guardado: {output_file}"
        )


except KeyboardInterrupt:

    print(
        "\nPROCESO INTERRUMPIDO MANUALMENTE"
    )


except Exception as e:

    print(
        f"\nERROR: "
        f"{type(e).__name__}: {e}"
    )


finally:

    # ============================================================
    # ESTADO FINAL
    # ============================================================

    print("\n" + "=" * 70)
    print("ESTADO FINAL")
    print("=" * 70)


    if current_dataset is not None:

        print(
            f"Último dataset: {current_dataset}"
        )

        print(
            f"Última etapa: {current_stage}"
        )

        print(
            f"Chunks confirmados en la etapa: "
            f"{current_chunk}/{total_chunks}"
        )


    if completed_datasets:

        print(
            "\nDatasets completados:",
            ", ".join(
                completed_datasets
            )
        )

    else:

        print(
            "\nDatasets completados: ninguno"
        )


    if saved_files:

        print(
            "\nArchivos guardados exitosamente:"
        )

        for file in saved_files:

            print(
                f"  ✓ {file}"
            )

    else:

        print(
            "\nArchivos completos guardados: ninguno"
        )

======================================================================
df_c1 | 43,775 filas × 32,648 columnas | 16 chunks
======================================================================
df_c1 | chunk 01/16 OK | 32 activos | 32,840 columnas
df_c1 | chunk 02/16 OK | 32 activos | 33,032 columnas
df_c1 | chunk 03/16 OK | 32 activos | 33,224 columnas
df_c1 | chunk 04/16 OK | 32 activos | 33,416 columnas
df_c1 | chunk 05/16 OK | 32 activos | 33,608 columnas
df_c1 | chunk 06/16 OK | 32 activos | 33,800 columnas
df_c1 | chunk 07/16 OK | 32 activos | 33,992 columnas
df_c1 | chunk 08/16 OK | 32 activos | 34,184 columnas
df_c1 | chunk 09/16 OK | 32 activos | 34,376 columnas
df_c1 | chunk 10/16 OK | 32 activos | 34,568 columnas
df_c1 | chunk 11/16 OK | 32 activos | 34,760 columnas
df_c1 | chunk 12/16 OK | 32 activos | 34,952 columnas
df_c1 | chunk 13/16 OK | 32 activos | 35,144 columnas
df_c1 | chunk 14/16 OK | 32 activos | 35,336 columnas
df_c1 | chunk 15/16 OK | 32 activos | 35,528 columnas
df_c1 | chunk 16/16 OK | 30 activos | 35,708 columnas

df_c1 COMPLETO | 43,775 filas × 35,708 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_final_Ectx.parquet

======================================================================
df_c2 | 43,776 filas × 32,648 columnas | 16 chunks
======================================================================
df_c2 | chunk 01/16 OK | 32 activos | 32,840 columnas
df_c2 | chunk 02/16 OK | 32 activos | 33,032 columnas
df_c2 | chunk 03/16 OK | 32 activos | 33,224 columnas
df_c2 | chunk 04/16 OK | 32 activos | 33,416 columnas
df_c2 | chunk 05/16 OK | 32 activos | 33,608 columnas
df_c2 | chunk 06/16 OK | 32 activos | 33,800 columnas
df_c2 | chunk 07/16 OK | 32 activos | 33,992 columnas
df_c2 | chunk 08/16 OK | 32 activos | 34,184 columnas
df_c2 | chunk 09/16 OK | 32 activos | 34,376 columnas
df_c2 | chunk 10/16 OK | 32 activos | 34,568 columnas
df_c2 | chunk 11/16 OK | 32 activos | 34,760 columnas
df_c2 | chunk 12/16 OK | 32 activos | 34,952 columnas
df_c2 | chunk 13/16 OK | 32 activos | 35,144 columnas
df_c2 | chunk 14/16 OK | 32 activos | 35,336 columnas
df_c2 | chunk 15/16 OK | 32 activos | 35,528 columnas
df_c2 | chunk 16/16 OK | 30 activos | 35,708 columnas

df_c2 COMPLETO | 43,776 filas × 35,708 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_final_Ectx.parquet

======================================================================
df_c3 | 44,064 filas × 32,648 columnas | 16 chunks
======================================================================
df_c3 | chunk 01/16 OK | 32 activos | 32,840 columnas
df_c3 | chunk 02/16 OK | 32 activos | 33,032 columnas
df_c3 | chunk 03/16 OK | 32 activos | 33,224 columnas
df_c3 | chunk 04/16 OK | 32 activos | 33,416 columnas
df_c3 | chunk 05/16 OK | 32 activos | 33,608 columnas
df_c3 | chunk 06/16 OK | 32 activos | 33,800 columnas
df_c3 | chunk 07/16 OK | 32 activos | 33,992 columnas
df_c3 | chunk 08/16 OK | 32 activos | 34,184 columnas
df_c3 | chunk 09/16 OK | 32 activos | 34,376 columnas
df_c3 | chunk 10/16 OK | 32 activos | 34,568 columnas
df_c3 | chunk 11/16 OK | 32 activos | 34,760 columnas
df_c3 | chunk 12/16 OK | 32 activos | 34,952 columnas
df_c3 | chunk 13/16 OK | 32 activos | 35,144 columnas
df_c3 | chunk 14/16 OK | 32 activos | 35,336 columnas
df_c3 | chunk 15/16 OK | 32 activos | 35,528 columnas
df_c3 | chunk 16/16 OK | 30 activos | 35,708 columnas

df_c3 COMPLETO | 44,064 filas × 35,708 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_final_Ectx.parquet

======================================================================
ESTADO FINAL
======================================================================
Último dataset: df_c3
Última etapa: E_context features
Chunks confirmados en la etapa: 16/16

Datasets completados: df_c1, df_c2, df_c3

Archivos guardados exitosamente:
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_final_Ectx.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_final_Ectx.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_final_Ectx.parquet

In [9]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43775 entries, 0 to 43774
Columns: 35708 entries, bar_end to 币安人生__Ectx_ERANK
dtypes: datetime64[ns, UTC](1), float32(34687), int8(1020)
memory usage: 5.7 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43776 entries, 0 to 43775
Columns: 35708 entries, bar_end to 币安人生__Ectx_ERANK
dtypes: datetime64[ns, UTC](1), float32(34687), int8(1020)
memory usage: 5.7 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44064 entries, 0 to 44063
Columns: 35708 entries, bar_end to 币安人生__Ectx_ERANK
dtypes: datetime64[ns, UTC](1), float32(34687), int8(1020)
memory usage: 5.7 GB

### 8 checkpoint

In [2]:
ruta = "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"

df_c1 = pd.read_parquet(ruta + "112024-042025_clean_add_final.parquet")
df_c2 = pd.read_parquet(ruta + "042025-092025_clean_add_final.parquet")
df_c3 = pd.read_parquet(ruta + "092025-022026_clean_add_final.parquet")

In [3]:
from numba import njit, prange

In [4]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# DATASET DE TRABAJO
# ============================================================

DATASET = df_c1


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    primary_window: int = 288
    min_periods: int = 72
    ewm_span: int = 72

    multiscale_windows: tuple[int, ...] = (
        3,
        12,
        72,
        288,
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):

    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

@njit(parallel=True)
def _recovery_speed_numba(
    g,
    s,
    q,
    b,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    T, N = g.shape
    output = np.full((T, N), np.nan, dtype=np.float64)

    for j in prange(N):
        in_event = False
        event_start = -1
        event_baseline = np.nan
        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):
            if not in_event:
                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):
                    in_event = True
                    event_start = t
                    event_baseline = b[t, j]
                    consecutive = 0

            elif np.isfinite(g[t, j]):
                distance = abs(g[t, j] - event_baseline) / (
                    abs(event_baseline) + eps
                )

                if distance <= tolerance:
                    consecutive += 1
                else:
                    consecutive = 0

                if consecutive >= hold_bars:
                    recovery_start = t - hold_bars + 1
                    duration = max(1, recovery_start - event_start)

                    if np.isnan(duration_ewma):
                        duration_ewma = float(duration)
                    else:
                        duration_ewma = (
                            alpha * duration
                            + (1.0 - alpha) * duration_ewma
                        )

                    in_event = False
                    event_start = -1
                    event_baseline = np.nan
                    consecutive = 0

            if np.isfinite(duration_ewma):
                output[t, j] = 1.0 / (1.0 + duration_ewma)

    return output


def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    frames = (stress, stress_threshold, baseline)

    if any(
        not gp0.index.equals(x.index)
        or not gp0.columns.equals(x.columns)
        for x in frames
    ):
        raise ValueError(
            "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
        )

    output = _recovery_speed_numba(
        gp0.to_numpy(dtype=np.float64, copy=False),
        stress.to_numpy(dtype=np.float64, copy=False),
        stress_threshold.to_numpy(dtype=np.float64, copy=False),
        baseline.to_numpy(dtype=np.float64, copy=False),
        tolerance,
        hold_bars,
        alpha,
        eps,
    )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns,
    )

# ============================================================
# INICIALIZACIÓN
# ============================================================

DATASET = validate_time(DATASET, cfg)

assets = discover_assets(
    DATASET,
    cfg
)

print("Dataset:", DATASET.shape)
print("Activos detectados:", len(assets))

Dataset: (43775, 32648)
Activos detectados: 510

In [5]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# DATASET DE TRABAJO
# ============================================================

DATASET = df_c2


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    primary_window: int = 288
    min_periods: int = 72
    ewm_span: int = 72

    multiscale_windows: tuple[int, ...] = (
        3,
        12,
        72,
        288,
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):

    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

@njit(parallel=True)
def _recovery_speed_numba(
    g,
    s,
    q,
    b,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    T, N = g.shape
    output = np.full((T, N), np.nan, dtype=np.float64)

    for j in prange(N):
        in_event = False
        event_start = -1
        event_baseline = np.nan
        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):
            if not in_event:
                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):
                    in_event = True
                    event_start = t
                    event_baseline = b[t, j]
                    consecutive = 0

            elif np.isfinite(g[t, j]):
                distance = abs(g[t, j] - event_baseline) / (
                    abs(event_baseline) + eps
                )

                if distance <= tolerance:
                    consecutive += 1
                else:
                    consecutive = 0

                if consecutive >= hold_bars:
                    recovery_start = t - hold_bars + 1
                    duration = max(1, recovery_start - event_start)

                    if np.isnan(duration_ewma):
                        duration_ewma = float(duration)
                    else:
                        duration_ewma = (
                            alpha * duration
                            + (1.0 - alpha) * duration_ewma
                        )

                    in_event = False
                    event_start = -1
                    event_baseline = np.nan
                    consecutive = 0

            if np.isfinite(duration_ewma):
                output[t, j] = 1.0 / (1.0 + duration_ewma)

    return output


def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    frames = (stress, stress_threshold, baseline)

    if any(
        not gp0.index.equals(x.index)
        or not gp0.columns.equals(x.columns)
        for x in frames
    ):
        raise ValueError(
            "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
        )

    output = _recovery_speed_numba(
        gp0.to_numpy(dtype=np.float64, copy=False),
        stress.to_numpy(dtype=np.float64, copy=False),
        stress_threshold.to_numpy(dtype=np.float64, copy=False),
        baseline.to_numpy(dtype=np.float64, copy=False),
        tolerance,
        hold_bars,
        alpha,
        eps,
    )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns,
    )

# ============================================================
# INICIALIZACIÓN
# ============================================================

DATASET = validate_time(DATASET, cfg)

assets = discover_assets(
    DATASET,
    cfg
)

print("Dataset:", DATASET.shape)
print("Activos detectados:", len(assets))

Dataset: (43776, 32648)
Activos detectados: 510

In [6]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import warnings

import numpy as np
import pandas as pd


# ============================================================
# DATASET DE TRABAJO
# ============================================================

DATASET = df_c3


# ============================================================
# CONFIGURACIÓN
# ============================================================

@dataclass(frozen=True)
class FeatureConfig:
    time_col: str = "bar_end"
    ys_col: str = "YS"

    price_suffix: str = "USDT"
    volume_suffix: str = "_v"
    trades_suffix: str = "_activity_trades_proxy"
    range_suffix: str = "_range_rel_proxy"
    illiq_suffix: str = "_illiquidity_proxy"
    active_suffix: str = "_active_trading"
    observed_suffix: str = "_observed"
    buy_suffix: str = "_taker_buy_usdt_proxy"
    sell_suffix: str = "_taker_sell_usdt_proxy"
    yp_suffix: str = "_yp"

    primary_window: int = 288
    min_periods: int = 72
    ewm_span: int = 72

    multiscale_windows: tuple[int, ...] = (
        3,
        12,
        72,
        288,
    )

    return_lag: int = 1

    stress_quantile: float = 0.90

    recovery_tolerance: float = 0.15
    recovery_hold_bars: int = 3
    recovery_event_ewm_alpha: float = 0.20

    eps: float = 1e-12
    dtype: str = "float32"

    asset_block_size: int = 32


cfg = FeatureConfig()


# ============================================================
# TIEMPO
# ============================================================

def validate_time(df, cfg):
    df = df.copy()

    df[cfg.time_col] = pd.to_datetime(
        df[cfg.time_col],
        utc=True,
        errors="raise"
    )

    df = (
        df.sort_values(cfg.time_col)
          .reset_index(drop=True)
    )

    if df[cfg.time_col].duplicated().any():
        raise ValueError("Existen timestamps duplicados.")

    delta = df[cfg.time_col].diff().dropna()

    expected = pd.Timedelta(minutes=5)

    if not delta.eq(expected).all():
        raise ValueError(
            "La serie no posee una grilla estricta de 5 minutos."
        )

    return df


# ============================================================
# ACTIVOS
# ============================================================

def discover_assets(df, cfg):

    price_cols = [
        c for c in df.columns
        if c.endswith(cfg.price_suffix)
        and "_" not in c
    ]

    candidates = sorted(
        c[:-len(cfg.price_suffix)]
        for c in price_cols
    )

    required_suffixes = (
        cfg.volume_suffix,
        cfg.trades_suffix,
        cfg.range_suffix,
        cfg.illiq_suffix,
        cfg.active_suffix,
        cfg.observed_suffix,
        cfg.buy_suffix,
        cfg.sell_suffix,
        cfg.yp_suffix,
    )

    assets = []

    for asset in candidates:

        if all(
            f"{asset}{suffix}" in df.columns
            for suffix in required_suffixes
        ):
            assets.append(asset)

    if len(assets) != 510:
        warnings.warn(
            f"Se detectaron {len(assets)} activos completos."
        )

    return assets


def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# NOMBRES
# ============================================================

def base_col(asset, kind, cfg):

    if kind == "P":
        return f"{asset}{cfg.price_suffix}"

    suffix = {
        "V": cfg.volume_suffix,
        "C": cfg.trades_suffix,
        "R": cfg.range_suffix,
        "L": cfg.illiq_suffix,
        "A": cfg.active_suffix,
        "O": cfg.observed_suffix,
        "B": cfg.buy_suffix,
        "S": cfg.sell_suffix,
        "yp": cfg.yp_suffix,
    }[kind]

    return f"{asset}{suffix}"


def feat_col(asset, feature):
    return f"{asset}__{feature}"


# ============================================================
# CARGA POR BLOQUES
# ============================================================

def load_base(df, assets, kind, cfg):

    cols = [
        base_col(a, kind, cfg)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def load_feature(df, assets, feature):

    cols = [
        feat_col(a, feature)
        for a in assets
    ]

    out = df.loc[:, cols].astype(
        "float64",
        copy=False
    )

    out.columns = assets

    return out


def name_block(x, feature, cfg):

    out = x.astype(
        cfg.dtype,
        copy=False
    )

    out.columns = [
        feat_col(a, feature)
        for a in out.columns
    ]

    return out


def merge_blocks(df, blocks):

    block = pd.concat(
        blocks,
        axis=1,
        copy=False
    )

    overlap = df.columns.intersection(
        block.columns
    )

    if len(overlap):
        df = df.drop(columns=list(overlap))

    return pd.concat(
        [df, block],
        axis=1,
        copy=False
    )


# ============================================================
# ROBUST Z CAUSAL
# ============================================================

def robust_z_causal(
    x,
    window,
    min_periods,
    eps
):

    hist = x.shift(1)

    roll = hist.rolling(
        window=window,
        min_periods=min_periods
    )

    median = roll.median()

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    scale = (
        q75 - q25
    ) / 1.349

    return (
        x - median
    ) / (
        scale + eps
    )


# ============================================================
# DISPERSIÓN ROBUSTA
# ============================================================

def rolling_robust_dispersion(
    x,
    window,
    min_periods,
    eps
):

    roll = x.rolling(
        window=window,
        min_periods=min_periods
    )

    q25 = roll.quantile(0.25)
    q75 = roll.quantile(0.75)

    return (
        (q75 - q25) / 1.349
        + eps
    )


# ============================================================
# AUTOCORRELACIÓN ROLLING
# ============================================================

def rolling_autocorr_lag1(
    x,
    window,
    min_periods
):

    lag = x.shift(1)

    result = {}

    for col in x.columns:
        result[col] = (
            x[col]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .corr(lag[col])
        )

    return pd.DataFrame(
        result,
        index=x.index
    )


# ============================================================
# BETA ROLLING
# ============================================================

def rolling_beta_with_intercept(
    x,
    y,
    window,
    min_periods,
    eps
):

    rx = x.rolling(
        window,
        min_periods=min_periods
    )

    ry = y.rolling(
        window,
        min_periods=min_periods
    )

    ex = rx.mean()
    ey = ry.mean()

    exy = (
        (x * y)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    ex2 = (
        (x * x)
        .rolling(
            window,
            min_periods=min_periods
        )
        .mean()
    )

    cov_xy = exy - ex * ey
    var_x = ex2 - ex * ex

    beta = (
        cov_xy
        / (var_x + eps)
    )

    return beta.clip(lower=0.0)


# ============================================================
# STRESS
# ============================================================

def rolling_stress_threshold(
    stress,
    window,
    min_periods,
    q
):

    return (
        stress
        .shift(1)
        .rolling(
            window,
            min_periods=min_periods
        )
        .quantile(q)
    )


def conditional_rolling_median_ratio(
    value,
    stress,
    threshold,
    window,
    min_periods,
    eps
):

    is_stress = (
        stress > threshold
    )

    numerator = (
        value
        .where(is_stress)
        .rolling(
            window,
            min_periods=max(
                5,
                min_periods // 10
            )
        )
        .median()
    )

    denominator = (
        value
        .rolling(
            window,
            min_periods=min_periods
        )
        .median()
    )

    return (
        numerator
        / (denominator + eps)
    )


# ============================================================
# PROXY POSITIVO LATENTE
# ============================================================

def softplus_df(x):

    values = np.logaddexp(
        0.0,
        x.to_numpy(
            dtype=np.float64,
            copy=False
        )
    )

    return pd.DataFrame(
        values,
        index=x.index,
        columns=x.columns
    )


def composite_positive_proxy(
    components,
    cfg
):

    total = None
    count = None

    for component in components:

        z = robust_z_causal(
            component,
            cfg.primary_window,
            cfg.min_periods,
            cfg.eps
        )

        valid = z.notna()

        if total is None:

            total = z.fillna(0.0)

            count = valid.astype(
                "float64"
            )

        else:

            total += z.fillna(0.0)

            count += valid.astype(
                "float64"
            )

    score = (
        total
        / count.replace(0.0, np.nan)
    )

    return softplus_df(score)


# ============================================================
# RECOVERY SPEED CAUSAL
# ============================================================

@njit(parallel=True)
def _recovery_speed_numba(
    g,
    s,
    q,
    b,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    T, N = g.shape
    output = np.full((T, N), np.nan, dtype=np.float64)

    for j in prange(N):
        in_event = False
        event_start = -1
        event_baseline = np.nan
        consecutive = 0
        duration_ewma = np.nan

        for t in range(T):
            if not in_event:
                if (
                    np.isfinite(s[t, j])
                    and np.isfinite(q[t, j])
                    and np.isfinite(b[t, j])
                    and s[t, j] > q[t, j]
                    and abs(b[t, j]) > eps
                ):
                    in_event = True
                    event_start = t
                    event_baseline = b[t, j]
                    consecutive = 0

            elif np.isfinite(g[t, j]):
                distance = abs(g[t, j] - event_baseline) / (
                    abs(event_baseline) + eps
                )

                if distance <= tolerance:
                    consecutive += 1
                else:
                    consecutive = 0

                if consecutive >= hold_bars:
                    recovery_start = t - hold_bars + 1
                    duration = max(1, recovery_start - event_start)

                    if np.isnan(duration_ewma):
                        duration_ewma = float(duration)
                    else:
                        duration_ewma = (
                            alpha * duration
                            + (1.0 - alpha) * duration_ewma
                        )

                    in_event = False
                    event_start = -1
                    event_baseline = np.nan
                    consecutive = 0

            if np.isfinite(duration_ewma):
                output[t, j] = 1.0 / (1.0 + duration_ewma)

    return output


def recovery_speed_causal(
    gp0,
    stress,
    stress_threshold,
    baseline,
    tolerance,
    hold_bars,
    alpha,
    eps
):
    frames = (stress, stress_threshold, baseline)

    if any(
        not gp0.index.equals(x.index)
        or not gp0.columns.equals(x.columns)
        for x in frames
    ):
        raise ValueError(
            "gp0, stress, stress_threshold y baseline deben compartir índice y columnas."
        )

    output = _recovery_speed_numba(
        gp0.to_numpy(dtype=np.float64, copy=False),
        stress.to_numpy(dtype=np.float64, copy=False),
        stress_threshold.to_numpy(dtype=np.float64, copy=False),
        baseline.to_numpy(dtype=np.float64, copy=False),
        tolerance,
        hold_bars,
        alpha,
        eps,
    )

    return pd.DataFrame(
        output,
        index=gp0.index,
        columns=gp0.columns,
    )

# ============================================================
# INICIALIZACIÓN
# ============================================================

DATASET = validate_time(DATASET, cfg)

assets = discover_assets(
    DATASET,
    cfg
)

print("Dataset:", DATASET.shape)
print("Activos detectados:", len(assets))

Dataset: (44064, 32648)
Activos detectados: 510

In [7]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43775 entries, 0 to 43774
Columns: 32648 entries, bar_end to 币安人生__TARGET_yp_t1
dtypes: datetime64[ns, UTC](1), float32(31627), int8(1020)
memory usage: 5.2 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43776 entries, 0 to 43775
Columns: 32648 entries, bar_end to 币安人生__TARGET_yp_t1
dtypes: datetime64[ns, UTC](1), float32(31627), int8(1020)
memory usage: 5.2 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44064 entries, 0 to 44063
Columns: 32648 entries, bar_end to 币安人生__TARGET_yp_t1
dtypes: datetime64[ns, UTC](1), float32(31627), int8(1020)
memory usage: 5.2 GB

##13. Derivadas de E_theory
- Log-energia
Eth_logE = ln(gp)- ln(N)
Estabilidad numerica y seperabilida multiplicativa

- Energia relativa
Eth_Erel_i = Ei - Median_j(Ej)
Posicion relativa transaversal

- Velocidad Energetica
Et_dE = E_t - E_t-1
Cambio de estado energetico

- Aceleracion Energetica
Eth_ddE = Et_dE - Et-1_dE
Rupturas dinamicas

- Energia de schock
Eth_ESH = Z_w(E)
Desviacion energetica respecto a ventan W (regimen inexacto)

- Ranking de Energia
Eth_ERANK = PerncentialRank_j(Ej)
Posicion energética competitiva

In [8]:
from pathlib import Path
import os
import gc

# ============================================================
# CHUNKING
# ============================================================

def chunks(seq, size):
    for start in range(0, len(seq), size):
        yield list(seq[start:start + size])


# ============================================================
# DATASETS DE TRABAJO
# ============================================================

DATASETS = {
    "df_c1": df_c1,
    "df_c2": df_c2,
    "df_c3": df_c3,
}


# ============================================================
# ARCHIVOS DE SALIDA
# ============================================================

ruta = Path(
    "/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/"
)

OUTPUTS = {
    "df_c1": ruta / "112024-042025_clean_add_final_Eth.parquet",
    "df_c2": ruta / "042025-092025_clean_add_final_Eth.parquet",
    "df_c3": ruta / "092025-022026_clean_add_final_Eth.parquet",
}


# ============================================================
# CONTROL DE PROCESO
# ============================================================

saved_files = []
completed_datasets = []

current_dataset = None
current_stage = None
current_chunk = 0
total_chunks = 0


try:

    for dataset_name, DATASET in DATASETS.items():

        current_dataset = dataset_name
        current_stage = "E_theory features"

        asset_chunks = list(
            chunks(
                assets,
                cfg.asset_block_size
            )
        )

        total_chunks = len(asset_chunks)
        current_chunk = 0

        print("\n" + "=" * 70)
        print(
            f"{dataset_name} | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas | "
            f"{total_chunks} chunks"
        )
        print("=" * 70)


        # ============================================================
        # E_theory GLOBAL
        # ============================================================

        E_all = load_feature(
            DATASET,
            assets,
            "E_theory"
        ).astype("float32")


        A_all = load_base(
            DATASET,
            assets,
            "A",
            cfg
        ).astype("float32")


        E_active = E_all.where(
            A_all > 0
        )


        # --------------------------------------------
        # Estadísticos transversales
        # --------------------------------------------

        E_median = E_active.median(
            axis=1
        )

        E_rank = E_active.rank(
            axis=1,
            pct=True,
            method="average"
        )


        # ============================================================
        # CÁLCULO POR CHUNK
        # ============================================================

        for i, chunk in enumerate(
            asset_chunks,
            start=1
        ):

            E = E_all.loc[
                :,
                chunk
            ]


            # --------------------------------------------
            # Log energía
            # --------------------------------------------

            logE = np.log(
                E.clip(
                    lower=cfg.eps
                )
            )


            # --------------------------------------------
            # Energía relativa transversal
            # --------------------------------------------

            Erel = E.sub(
                E_median,
                axis=0
            )


            # --------------------------------------------
            # Primera diferencia
            # --------------------------------------------

            dE = E.diff()


            # --------------------------------------------
            # Segunda diferencia
            # --------------------------------------------

            ddE = dE.diff()


            # --------------------------------------------
            # Shock robusto causal
            # --------------------------------------------

            ESH = robust_z_causal(
                E,
                cfg.primary_window,
                cfg.min_periods,
                cfg.eps
            )


            # --------------------------------------------
            # Ranking transversal
            # --------------------------------------------

            ERANK = E_rank.loc[
                :,
                chunk
            ]


            # ========================================================
            # PREPARACIÓN DEL CHUNK
            # ========================================================

            chunk_blocks = [
                name_block(
                    logE,
                    "Eth_logE",
                    cfg
                ),

                name_block(
                    Erel,
                    "Eth_Erel",
                    cfg
                ),

                name_block(
                    dE,
                    "Eth_dE",
                    cfg
                ),

                name_block(
                    ddE,
                    "Eth_ddE",
                    cfg
                ),

                name_block(
                    ESH,
                    "Eth_ESH",
                    cfg
                ),

                name_block(
                    ERANK,
                    "Eth_ERANK",
                    cfg
                ),
            ]


            # ========================================================
            # COMMIT DEL CHUNK
            # Solo se ejecuta si TODO el chunk terminó correctamente
            # ========================================================

            DATASET = merge_blocks(
                DATASET,
                chunk_blocks
            )

            DATASETS[dataset_name] = DATASET
            globals()[dataset_name] = DATASET

            current_chunk = i

            print(
                f"{dataset_name} | "
                f"chunk {i:02d}/{total_chunks} OK | "
                f"{len(chunk):02d} activos | "
                f"{DATASET.shape[1]:,} columnas"
            )


            del (
                E,
                logE,
                Erel,
                dE,
                ddE,
                ESH,
                ERANK,
                chunk_blocks,
            )

            gc.collect()


        # ============================================================
        # LIMPIEZA DE OBJETOS GLOBALES DEL DATASET
        # ============================================================

        del (
            E_all,
            A_all,
            E_active,
            E_median,
            E_rank,
        )

        gc.collect()


        # ============================================================
        # GUARDADO DEL DATASET COMPLETO
        # ============================================================

        output_file = OUTPUTS[
            dataset_name
        ]

        temp_file = output_file.with_suffix(
            ".tmp.parquet"
        )

        DATASET.to_parquet(
            temp_file,
            index=False
        )

        os.replace(
            temp_file,
            output_file
        )

        saved_files.append(
            str(output_file)
        )

        completed_datasets.append(
            dataset_name
        )

        print(
            f"\n{dataset_name} COMPLETO | "
            f"{DATASET.shape[0]:,} filas × "
            f"{DATASET.shape[1]:,} columnas"
        )

        print(
            f"Guardado: {output_file}"
        )


except KeyboardInterrupt:

    print(
        "\nPROCESO INTERRUMPIDO MANUALMENTE"
    )


except Exception as e:

    print(
        f"\nERROR: "
        f"{type(e).__name__}: {e}"
    )


finally:

    # ============================================================
    # ESTADO FINAL
    # ============================================================

    print("\n" + "=" * 70)
    print("ESTADO FINAL")
    print("=" * 70)


    if current_dataset is not None:

        print(
            f"Último dataset: {current_dataset}"
        )

        print(
            f"Última etapa: {current_stage}"
        )

        print(
            f"Chunks confirmados en la etapa: "
            f"{current_chunk}/{total_chunks}"
        )


    if completed_datasets:

        print(
            "\nDatasets completados:",
            ", ".join(
                completed_datasets
            )
        )

    else:

        print(
            "\nDatasets completados: ninguno"
        )


    if saved_files:

        print(
            "\nArchivos guardados exitosamente:"
        )

        for file in saved_files:

            print(
                f"  ✓ {file}"
            )

    else:

        print(
            "\nArchivos completos guardados: ninguno"
        )

======================================================================
df_c1 | 43,775 filas × 32,648 columnas | 16 chunks
======================================================================
df_c1 | chunk 01/16 OK | 32 activos | 32,840 columnas
df_c1 | chunk 02/16 OK | 32 activos | 33,032 columnas
df_c1 | chunk 03/16 OK | 32 activos | 33,224 columnas
df_c1 | chunk 04/16 OK | 32 activos | 33,416 columnas
df_c1 | chunk 05/16 OK | 32 activos | 33,608 columnas
df_c1 | chunk 06/16 OK | 32 activos | 33,800 columnas
df_c1 | chunk 07/16 OK | 32 activos | 33,992 columnas
df_c1 | chunk 08/16 OK | 32 activos | 34,184 columnas
df_c1 | chunk 09/16 OK | 32 activos | 34,376 columnas
df_c1 | chunk 10/16 OK | 32 activos | 34,568 columnas
df_c1 | chunk 11/16 OK | 32 activos | 34,760 columnas
df_c1 | chunk 12/16 OK | 32 activos | 34,952 columnas
df_c1 | chunk 13/16 OK | 32 activos | 35,144 columnas
df_c1 | chunk 14/16 OK | 32 activos | 35,336 columnas
df_c1 | chunk 15/16 OK | 32 activos | 35,528 columnas
df_c1 | chunk 16/16 OK | 30 activos | 35,708 columnas

df_c1 COMPLETO | 43,775 filas × 35,708 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_final_Eth.parquet

======================================================================
df_c2 | 43,776 filas × 32,648 columnas | 16 chunks
======================================================================
df_c2 | chunk 01/16 OK | 32 activos | 32,840 columnas
df_c2 | chunk 02/16 OK | 32 activos | 33,032 columnas
df_c2 | chunk 03/16 OK | 32 activos | 33,224 columnas
df_c2 | chunk 04/16 OK | 32 activos | 33,416 columnas
df_c2 | chunk 05/16 OK | 32 activos | 33,608 columnas
df_c2 | chunk 06/16 OK | 32 activos | 33,800 columnas
df_c2 | chunk 07/16 OK | 32 activos | 33,992 columnas
df_c2 | chunk 08/16 OK | 32 activos | 34,184 columnas
df_c2 | chunk 09/16 OK | 32 activos | 34,376 columnas
df_c2 | chunk 10/16 OK | 32 activos | 34,568 columnas
df_c2 | chunk 11/16 OK | 32 activos | 34,760 columnas
df_c2 | chunk 12/16 OK | 32 activos | 34,952 columnas
df_c2 | chunk 13/16 OK | 32 activos | 35,144 columnas
df_c2 | chunk 14/16 OK | 32 activos | 35,336 columnas
df_c2 | chunk 15/16 OK | 32 activos | 35,528 columnas
df_c2 | chunk 16/16 OK | 30 activos | 35,708 columnas

df_c2 COMPLETO | 43,776 filas × 35,708 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_final_Eth.parquet

======================================================================
df_c3 | 44,064 filas × 32,648 columnas | 16 chunks
======================================================================
df_c3 | chunk 01/16 OK | 32 activos | 32,840 columnas
df_c3 | chunk 02/16 OK | 32 activos | 33,032 columnas
df_c3 | chunk 03/16 OK | 32 activos | 33,224 columnas
df_c3 | chunk 04/16 OK | 32 activos | 33,416 columnas
df_c3 | chunk 05/16 OK | 32 activos | 33,608 columnas
df_c3 | chunk 06/16 OK | 32 activos | 33,800 columnas
df_c3 | chunk 07/16 OK | 32 activos | 33,992 columnas
df_c3 | chunk 08/16 OK | 32 activos | 34,184 columnas
df_c3 | chunk 09/16 OK | 32 activos | 34,376 columnas
df_c3 | chunk 10/16 OK | 32 activos | 34,568 columnas
df_c3 | chunk 11/16 OK | 32 activos | 34,760 columnas
df_c3 | chunk 12/16 OK | 32 activos | 34,952 columnas
df_c3 | chunk 13/16 OK | 32 activos | 35,144 columnas
df_c3 | chunk 14/16 OK | 32 activos | 35,336 columnas
df_c3 | chunk 15/16 OK | 32 activos | 35,528 columnas
df_c3 | chunk 16/16 OK | 30 activos | 35,708 columnas

df_c3 COMPLETO | 44,064 filas × 35,708 columnas
Guardado: /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_final_Eth.parquet

======================================================================
ESTADO FINAL
======================================================================
Último dataset: df_c3
Última etapa: E_theory features
Chunks confirmados en la etapa: 16/16

Datasets completados: df_c1, df_c2, df_c3

Archivos guardados exitosamente:
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-042025_clean_add_final_Eth.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/042025-092025_clean_add_final_Eth.parquet
  ✓ /content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/092025-022026_clean_add_final_Eth.parquet

In [9]:
df_c1.info()
df_c2.info()
df_c3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43775 entries, 0 to 43774
Columns: 35708 entries, bar_end to 币安人生__Eth_ERANK
dtypes: datetime64[ns, UTC](1), float32(34687), int8(1020)
memory usage: 5.7 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43776 entries, 0 to 43775
Columns: 35708 entries, bar_end to 币安人生__Eth_ERANK
dtypes: datetime64[ns, UTC](1), float32(34687), int8(1020)
memory usage: 5.7 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44064 entries, 0 to 44063
Columns: 35708 entries, bar_end to 币安人生__Eth_ERANK
dtypes: datetime64[ns, UTC](1), float32(34687), int8(1020)
memory usage: 5.7 GB

In [10]:
btc_cols = [c for c in df_c1.columns if c.startswith("BTC")]

btc_info = pd.DataFrame({
    "columna": btc_cols,
    "dtype": [df_c1[c].dtype for c in btc_cols],
    "n_nans": [df_c1[c].isna().sum() for c in btc_cols],
    "pct_nans": [df_c1[c].isna().mean() * 100 for c in btc_cols],
})

btc_info

           columna    dtype  n_nans  pct_nans
0            BTC_y  float32       0  0.000000
1          BTCUSDT  float32       0  0.000000
2            BTC_v  float32       0  0.000000
3           BTC_yp  float32       0  0.000000
4     BTC_observed     int8       0  0.000000
..             ...      ...     ...       ...
65   BTC__Eth_Erel  float32     143  0.326670
66     BTC__Eth_dE  float32     144  0.328955
67    BTC__Eth_ddE  float32     145  0.331239
68    BTC__Eth_ESH  float32     215  0.491148
69  BTC__Eth_ERANK  float32     143  0.326670

[70 rows x 4 columns]

##EXPERIMIENTOS HASTA 5 CHECKPOINT

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

***APERTURA***

In [ ]:
df = pd.read_parquet('/content/drive/MyDrive/Neural/NPP/Cripto/Crypto 5 minutos/112024-122025_clean_add.parquet')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131616 entries, 0 to 131615
Columns: 20918 entries, bar_end to 币安人生__TURNOVER_PER_TRADE_AUDIT
dtypes: datetime64[ns, UTC](1), float32(14796), float64(5101), int8(1020)
memory usage: 12.4 GB

In [ ]:
import numpy as np
import pandas as pd

from scipy.optimize import minimize_scalar
from scipy.special import softmax
from scipy.stats import wasserstein_distance

from sklearn.feature_selection import mutual_info_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


# ============================================================
# VARIABLES DISPONIBLES HASTA CELDA 6
# ============================================================

NODE_FEATURES = {

    # Precio / volumen
    "return_k1": "price_volume",
    "rolling_volatility": "price_volume",
    "dlogV": "price_volume",
    "VSTAB": "price_volume",

    # Actividad
    "TI": "activity",
    "PERS_C": "activity",
    "Arel": "activity",
    "CA": "activity",
    "CO": "activity",

    # Buy / Sell
    "SI": "flow",
    "SG": "flow",
    "SP": "flow",
    "imbalance": "flow",
    "sell_share": "flow",
    "LR_BS": "flow",
    "BIL": "flow",

    # Absorción / liquidez
    "BILST": "absorption_liquidity",
    "ABS": "absorption_liquidity",
    "ABS_S": "absorption_liquidity",
    "RLIQ": "absorption_liquidity",
    "RLIQ_S": "absorption_liquidity",
    "LIQ": "absorption_liquidity",

    # Stress / resistencia
    "IR": "stress_resistance",
    "STRESS": "stress_resistance",
    "SSR": "stress_resistance",
    "SSR_S": "stress_resistance",
    "AST_S": "stress_resistance",

    # Auditoría: NO usar en NPP estricto
    "FLOW_TOTAL_AUDIT": "audit_only",
    "TURNOVER_PER_TRADE_AUDIT": "audit_only",
}


SYSTEM_FEATURES = [
    "SYS_active_nodes",
    "SYS_trades",
    "SYS_imbalance",
    "YS_log",
    "YS_growth",
    "YS_volatility",
]


# ============================================================
# FAMILIAS PARA MODELOS
# ============================================================

MODEL_FAMILIES = {

    "price_volume": [
        "return_k1",
        "rolling_volatility",
        "dlogV",
        "VSTAB",
    ],

    "activity": [
        "TI",
        "PERS_C",
        "Arel",
        "CA",
        "CO",
    ],

    "flow": [
        "SI",
        "SG",
        "SP",
        "imbalance",
        "sell_share",
        "LR_BS",
        "BIL",
    ],

    "absorption_liquidity": [
        "BILST",
        "ABS",
        "ABS_S",
        "RLIQ",
        "RLIQ_S",
        "LIQ",
    ],

    "stress_resistance": [
        "IR",
        "STRESS",
        "SSR",
        "SSR_S",
        "AST_S",
    ],
}


# ============================================================
# SOPORTES TEÓRICOS
# None = sin cota dura
# ============================================================

SUPPORT = {

    "return_k1": (None, None),
    "rolling_volatility": (0.0, None),

    "dlogV": (None, None),
    "VSTAB": (0.0, 1.0),

    "TI": (None, None),
    "PERS_C": (-1.0, 1.0),
    "Arel": (0.0, 1.0),
    "CA": (0.0, 1.0),
    "CO": (0.0, 1.0),

    "SI": (None, None),
    "SG": (None, None),
    "SP": (None, None),

    "imbalance": (-1.0, 1.0),
    "sell_share": (0.0, 1.0),
    "LR_BS": (None, None),
    "BIL": (0.0, 1.0),

    "BILST": (0.0, 1.0),

    "ABS": (0.0, None),
    "ABS_S": (0.0, None),

    "RLIQ": (0.0, None),
    "RLIQ_S": (0.0, None),

    "LIQ": (None, 0.0),

    "IR": (0.0, None),

    "STRESS": (None, None),
    "SSR": (0.0, None),
    "SSR_S": (0.0, None),
    "AST_S": (0.0, None),

    "FLOW_TOTAL_AUDIT": (0.0, None),
    "TURNOVER_PER_TRADE_AUDIT": (0.0, None),
}


STRICT_FEATURES = [
    f
    for f, family in NODE_FEATURES.items()
    if family != "audit_only"
]

In [ ]:
def add_target_yp_t1(
    df,
    assets,
    cfg,
):
    blocks = []

    for chunk in chunks(
        assets,
        cfg.asset_block_size,
    ):

        yp_cols = [
            f"{a}{cfg.yp_suffix}"
            for a in chunk
        ]

        target = (
            df.loc[:, yp_cols]
            .shift(-1)
            .astype(cfg.dtype)
        )

        target.columns = [
            f"{a}__TARGET_yp_t1"
            for a in chunk
        ]

        blocks.append(target)

    target = pd.concat(
        blocks,
        axis=1,
        copy=False,
    )

    existing = df.columns.intersection(
        target.columns
    )

    if len(existing):
        df = df.drop(
            columns=list(existing)
        )

    return pd.concat(
        [df, target],
        axis=1,
        copy=False,
    )


df = add_target_yp_t1(
    df,
    assets,
    cfg,
)

NameError: name 'assets' is not defined

In [ ]:
target_cols = [
    f"{a}__TARGET_yp_t1"
    for a in assets
]

assert df[target_cols].iloc[-1].isna().all()

print(
    "Targets creados:",
    len(target_cols)
)

In [ ]:
def chronological_splits(
    df,
    horizon=1,
    train_frac=0.70,
    val_frac=0.15,
    purge=None,
):
    if purge is None:
        purge = horizon

    n = len(df)

    # Últimas h filas no tienen target conocido
    usable_end = n - horizon

    train_end = int(
        usable_end * train_frac
    )

    val_end = int(
        usable_end
        * (train_frac + val_frac)
    )

    train_idx = np.arange(
        0,
        max(
            0,
            train_end - horizon
        )
    )

    val_idx = np.arange(
        train_end + purge,
        max(
            train_end + purge,
            val_end - horizon
        )
    )

    test_idx = np.arange(
        val_end + purge,
        usable_end
    )

    return {
        "train": train_idx,
        "val": val_idx,
        "test": test_idx,
    }


SPLITS = chronological_splits(
    df,
    horizon=1,
    purge=1,
)


for name, idx in SPLITS.items():

    print(
        name,
        len(idx),
        df[cfg.time_col].iloc[idx[0]],
        "→",
        df[cfg.time_col].iloc[idx[-1]],
    )

In [ ]:
def audit_node_feature(
    df,
    feature,
    assets,
    cfg,
    sample_rows=5000,
    seed=42,
):

    rng = np.random.default_rng(seed)

    if len(df) > sample_rows:
        row_sample = np.sort(
            rng.choice(
                len(df),
                sample_rows,
                replace=False,
            )
        )
    else:
        row_sample = np.arange(len(df))

    total = 0
    nan_count = 0
    inf_count = 0
    zero_count = 0
    support_bad = 0

    constant_assets = 0
    asset_count = 0

    sample_values = []

    lower, upper = SUPPORT.get(
        feature,
        (None, None),
    )

    for chunk in chunks(
        assets,
        cfg.asset_block_size,
    ):

        X = load_feature(
            df,
            chunk,
            feature,
        )

        arr = X.to_numpy(
            dtype=np.float64,
            copy=False,
        )

        total += arr.size

        nan_count += np.isnan(
            arr
        ).sum()

        inf_count += np.isinf(
            arr
        ).sum()

        finite = np.isfinite(arr)

        zero_count += (
            (arr == 0)
            & finite
        ).sum()

        if lower is not None:
            support_bad += (
                (arr < lower - 1e-7)
                & finite
            ).sum()

        if upper is not None:
            support_bad += (
                (arr > upper + 1e-7)
                & finite
            ).sum()

        # Activos degenerados
        for j in range(arr.shape[1]):

            x = arr[:, j]

            x = x[
                np.isfinite(x)
            ]

            asset_count += 1

            if (
                len(x) == 0
                or np.nanstd(x) < 1e-12
            ):
                constant_assets += 1

        sampled = arr[
            row_sample,
            :
        ].ravel()

        sampled = sampled[
            np.isfinite(sampled)
        ]

        if len(sampled):
            sample_values.append(
                sampled
            )

    if sample_values:
        sample_values = np.concatenate(
            sample_values
        )

        q = np.quantile(
            sample_values,
            [
                0.001,
                0.01,
                0.50,
                0.99,
                0.999,
            ]
        )

        q001, q01, med, q99, q999 = q

    else:
        q001 = q01 = med = q99 = q999 = np.nan

    return {
        "feature": feature,
        "family": NODE_FEATURES[feature],

        "nan_pct":
            100 * nan_count / total,

        "inf_pct":
            100 * inf_count / total,

        "zero_pct":
            100 * zero_count / total,

        "support_violation_pct":
            100 * support_bad / total,

        "constant_asset_pct":
            100 * constant_assets
            / max(asset_count, 1),

        "q_0.001": q001,
        "q_0.01": q01,
        "median": med,
        "q_0.99": q99,
        "q_0.999": q999,
    }


quality_rows = []

for feature in NODE_FEATURES:

    print("Auditando:", feature)

    quality_rows.append(
        audit_node_feature(
            df,
            feature,
            assets,
            cfg,
        )
    )


QUALITY_TABLE = (
    pd.DataFrame(quality_rows)
    .sort_values(
        [
            "family",
            "feature",
        ]
    )
    .reset_index(drop=True)
)


display(QUALITY_TABLE)

In [ ]:
def audit_system_features(
    df,
    features,
):

    rows = []

    for feature in features:

        x = (
            df[feature]
            .to_numpy(
                dtype=np.float64,
                copy=False
            )
        )

        finite = np.isfinite(x)

        xf = x[finite]

        rows.append({

            "feature": feature,

            "nan_pct":
                100
                * np.isnan(x).mean(),

            "inf_pct":
                100
                * np.isinf(x).mean(),

            "zero_pct":
                100
                * (
                    (x == 0)
                    & finite
                ).mean(),

            "median":
                np.nanmedian(xf)
                if len(xf)
                else np.nan,

            "IQR":
                (
                    np.nanquantile(
                        xf,
                        0.75
                    )
                    -
                    np.nanquantile(
                        xf,
                        0.25
                    )
                )
                if len(xf)
                else np.nan,

            "std":
                np.nanstd(xf)
                if len(xf)
                else np.nan,
        })

    return pd.DataFrame(rows)


SYSTEM_QUALITY = audit_system_features(
    df,
    SYSTEM_FEATURES,
)

display(SYSTEM_QUALITY)

In [ ]:
def sampled_node_panel(
    df,
    assets,
    features,
    cfg,
    n_times=3000,
    n_assets=96,
    seed=42,
):

    rng = np.random.default_rng(seed)

    chosen_assets = (
        list(assets)
        if len(assets) <= n_assets
        else list(
            rng.choice(
                assets,
                n_assets,
                replace=False,
            )
        )
    )

    valid_rows = np.arange(
        0,
        len(df) - 1
    )

    if len(valid_rows) > n_times:

        time_idx = np.sort(
            rng.choice(
                valid_rows,
                n_times,
                replace=False,
            )
        )

    else:
        time_idx = valid_rows

    data = {}

    for feature in features:

        X = load_feature(
            df,
            chosen_assets,
            feature,
        )

        data[feature] = (
            X.iloc[time_idx]
            .to_numpy(
                dtype=np.float32,
                copy=False
            )
            .reshape(-1)
        )

    yp_cols = [
        f"{a}{cfg.yp_suffix}"
        for a in chosen_assets
    ]

    yp = (
        df.loc[
            df.index[time_idx],
            yp_cols,
        ]
        .to_numpy(
            dtype=np.float32,
            copy=False
        )
        .reshape(-1)
    )

    panel = pd.DataFrame(data)

    panel["yp_t"] = yp

    panel["log_yp_t"] = np.log(
        np.clip(
            yp,
            cfg.eps,
            None,
        )
    )

    return panel


AUDIT_PANEL = sampled_node_panel(
    df,
    assets,
    STRICT_FEATURES,
    cfg,
)

In [ ]:
def redundancy_report(
    panel,
    features,
    threshold=0.97,
):

    X = panel[features]

    corr = X.corr(
        method="spearman"
    )

    rows = []

    for i in range(len(features)):

        for j in range(
            i + 1,
            len(features)
        ):

            a = features[i]
            b = features[j]

            rho = corr.loc[a, b]

            if (
                np.isfinite(rho)
                and abs(rho) >= threshold
            ):

                rows.append({
                    "feature_1": a,
                    "feature_2": b,
                    "spearman": rho,
                })

    return (
        pd.DataFrame(rows)
        .sort_values(
            "spearman",
            key=np.abs,
            ascending=False,
        )
        if rows
        else pd.DataFrame(
            columns=[
                "feature_1",
                "feature_2",
                "spearman",
            ]
        )
    )


REDUNDANCY = redundancy_report(
    AUDIT_PANEL,
    STRICT_FEATURES,
    threshold=0.97,
)

display(REDUNDANCY)

In [ ]:
def circularity_report(
    panel,
    features,
    max_samples=50000,
    seed=42,
):

    rng = np.random.default_rng(seed)

    work = panel[
        features
        + ["log_yp_t"]
    ].replace(
        [np.inf, -np.inf],
        np.nan
    ).dropna()

    if len(work) > max_samples:

        idx = rng.choice(
            len(work),
            max_samples,
            replace=False,
        )

        work = work.iloc[idx]

    y = work[
        "log_yp_t"
    ].to_numpy()

    rows = []

    for feature in features:

        x = work[
            feature
        ].to_numpy()

        # Spearman
        rho = (
            pd.Series(x)
            .corr(
                pd.Series(y),
                method="spearman",
            )
        )

        # Información mutua
        mi = mutual_info_regression(
            x.reshape(-1, 1),
            y,
            random_state=seed,
        )[0]

        # Capacidad lineal de reconstrucción
        split = int(
            len(x) * 0.70
        )

        model = LinearRegression()

        model.fit(
            x[:split].reshape(-1, 1),
            y[:split],
        )

        pred = model.predict(
            x[split:].reshape(-1, 1)
        )

        r2 = r2_score(
            y[split:],
            pred,
        )

        rows.append({
            "feature": feature,
            "family": NODE_FEATURES[feature],
            "spearman_logyp": rho,
            "MI_logyp": mi,
            "linear_R2_logyp": r2,
        })

    return (
        pd.DataFrame(rows)
        .sort_values(
            "MI_logyp",
            ascending=False,
        )
        .reset_index(drop=True)
    )


CIRCULARITY = circularity_report(
    AUDIT_PANEL,
    STRICT_FEATURES,
)

display(CIRCULARITY)

In [ ]:
def temporal_stability(
    df,
    assets,
    features,
    cfg,
    n_blocks=4,
    n_assets=64,
    rows_per_block=3000,
    seed=42,
):

    rng = np.random.default_rng(seed)

    chosen_assets = (
        list(assets)
        if len(assets) <= n_assets
        else list(
            rng.choice(
                assets,
                n_assets,
                replace=False,
            )
        )
    )

    blocks_idx = np.array_split(
        np.arange(len(df)),
        n_blocks,
    )

    output = []

    for feature in features:

        distributions = []

        for b, idx in enumerate(
            blocks_idx
        ):

            if len(idx) > rows_per_block:

                sample_idx = np.sort(
                    rng.choice(
                        idx,
                        rows_per_block,
                        replace=False,
                    )
                )

            else:
                sample_idx = idx

            X = load_feature(
                df,
                chosen_assets,
                feature,
            )

            values = (
                X.iloc[sample_idx]
                .to_numpy(
                    dtype=np.float32,
                    copy=False,
                )
                .reshape(-1)
            )

            values = values[
                np.isfinite(values)
            ]

            distributions.append(
                values
            )

        base = distributions[0]

        base_iqr = (
            np.quantile(base, 0.75)
            - np.quantile(base, 0.25)
        )

        for b, values in enumerate(
            distributions
        ):

            med = np.median(values)

            iqr = (
                np.quantile(
                    values,
                    0.75
                )
                -
                np.quantile(
                    values,
                    0.25
                )
            )

            if b == 0:
                w_norm = 0.0
            else:
                w = wasserstein_distance(
                    base,
                    values,
                )

                w_norm = (
                    w
                    /
                    (
                        base_iqr
                        + cfg.eps
                    )
                )

            output.append({
                "feature": feature,
                "block": b,
                "median": med,
                "IQR": iqr,
                "wasserstein_vs_block0_IQR": w_norm,
            })

    return pd.DataFrame(output)


STABILITY = temporal_stability(
    df,
    assets,
    STRICT_FEATURES,
    cfg,
)

display(STABILITY)

In [ ]:
from statsmodels.tsa.stattools import (
    adfuller,
    kpss,
)


def stationarity_screen(
    df,
    assets,
    features,
    cfg,
):

    rows = []

    for feature in features:

        X = load_feature(
            df,
            assets,
            feature,
        )

        x = (
            X.median(
                axis=1,
                skipna=True,
            )
            .replace(
                [np.inf, -np.inf],
                np.nan,
            )
            .dropna()
        )

        if len(x) < 100:
            continue

        try:
            adf_p = adfuller(
                x,
                autolag="AIC",
            )[1]
        except Exception:
            adf_p = np.nan

        try:
            kpss_p = kpss(
                x,
                regression="c",
                nlags="auto",
            )[1]
        except Exception:
            kpss_p = np.nan

        rows.append({
            "feature": feature,
            "ADF_p": adf_p,
            "KPSS_p": kpss_p,
        })

    return pd.DataFrame(rows)


STATIONARITY = stationarity_screen(
    df,
    assets,
    STRICT_FEATURES,
    cfg,
)

display(STATIONARITY)

In [ ]:
def yp_matrix(
    df,
    assets,
    rows,
    cfg,
    horizon=0,
):

    rows = np.asarray(rows)

    target_rows = (
        rows + horizon
    )

    cols = [
        f"{a}{cfg.yp_suffix}"
        for a in assets
    ]

    return (
        df.iloc[target_rows][cols]
        .to_numpy(
            dtype=np.float64,
            copy=False,
        )
    )


def normalize_simplex(
    X,
    eps=1e-12,
    smooth=False,
):

    X = np.nan_to_num(
        X,
        nan=0.0,
        posinf=0.0,
        neginf=0.0,
    )

    X = np.clip(
        X,
        0.0,
        None,
    )

    if smooth:
        X = X + eps

    denom = X.sum(
        axis=1,
        keepdims=True,
    )

    return (
        X
        /
        np.maximum(
            denom,
            eps,
        )
    )


def simplex_metrics(
    y,
    q,
    eps=1e-12,
):

    y = normalize_simplex(
        y,
        eps,
        smooth=False,
    )

    q = normalize_simplex(
        q,
        eps,
        smooth=True,
    )

    log_y = np.log(
        np.clip(
            y,
            eps,
            None,
        )
    )

    log_q = np.log(
        np.clip(
            q,
            eps,
            None,
        )
    )

    CE_t = -np.sum(
        y * log_q,
        axis=1,
    )

    KL_t = np.sum(
        y * (
            log_y
            - log_q
        ),
        axis=1,
    )

    m = 0.5 * (
        y + q
    )

    log_m = np.log(
        np.clip(
            m,
            eps,
            None,
        )
    )

    JS_t = 0.5 * (
        np.sum(
            y * (
                log_y - log_m
            ),
            axis=1,
        )
        +
        np.sum(
            q * (
                log_q - log_m
            ),
            axis=1,
        )
    )

    return {
        "CE": CE_t.mean(),
        "KL": KL_t.mean(),
        "JS": JS_t.mean(),
        "MAE": np.mean(
            np.abs(
                y - q
            )
        ),
        "RMSE": np.sqrt(
            np.mean(
                (y - q) ** 2
            )
        ),
        "CE_t": CE_t,
    }

In [ ]:
def sample_rows_evenly(
    idx,
    max_rows,
):

    idx = np.asarray(idx)

    if len(idx) <= max_rows:
        return idx

    positions = np.linspace(
        0,
        len(idx) - 1,
        max_rows,
        dtype=int,
    )

    return idx[positions]


def load_feature_matrix(
    df,
    assets,
    feature,
    rows,
):

    cols = [
        f"{a}__{feature}"
        for a in assets
    ]

    return (
        df.iloc[rows][cols]
        .to_numpy(
            dtype=np.float64,
            copy=False,
        )
    )


def fit_robust_scaler(
    X,
    eps=1e-12,
):

    values = X[
        np.isfinite(X)
    ]

    median = np.median(
        values
    )

    q25, q75 = np.quantile(
        values,
        [0.25, 0.75]
    )

    scale = (
        q75 - q25
    ) / 1.349

    return (
        median,
        max(scale, eps),
    )


def transform_feature(
    X,
    median,
    scale,
):

    Z = (
        X - median
    ) / scale

    Z = np.nan_to_num(
        Z,
        nan=0.0,
        posinf=8.0,
        neginf=-8.0,
    )

    return np.clip(
        Z,
        -8.0,
        8.0,
    )


def tilted_simplex(
    p,
    x,
    beta,
    eps=1e-12,
):

    p = normalize_simplex(
        p,
        eps,
        smooth=True,
    )

    logits = (
        np.log(
            np.clip(
                p,
                eps,
                None,
            )
        )
        +
        beta * x
    )

    return softmax(
        logits,
        axis=1,
    )

In [ ]:
def screen_single_feature(
    df,
    assets,
    feature,
    cfg,
    splits,
    horizon=1,
    train_max_rows=15000,
):

    # --------------------------------------------
    # Train para beta
    # --------------------------------------------

    train_rows = sample_rows_evenly(
        splits["train"],
        train_max_rows,
    )

    # Evitar desbordar final
    train_rows = train_rows[
        train_rows + horizon
        < len(df)
    ]

    X_train = load_feature_matrix(
        df,
        assets,
        feature,
        train_rows,
    )

    med, scale = fit_robust_scaler(
        X_train,
        cfg.eps,
    )

    X_train = transform_feature(
        X_train,
        med,
        scale,
    )

    p_train = yp_matrix(
        df,
        assets,
        train_rows,
        cfg,
        horizon=0,
    )

    y_train = yp_matrix(
        df,
        assets,
        train_rows,
        cfg,
        horizon=horizon,
    )

    p_train = normalize_simplex(
        p_train,
        cfg.eps,
        smooth=True,
    )

    y_train = normalize_simplex(
        y_train,
        cfg.eps,
        smooth=False,
    )


    def objective(beta):

        q = tilted_simplex(
            p_train,
            X_train,
            beta,
            cfg.eps,
        )

        return simplex_metrics(
            y_train,
            q,
            cfg.eps,
        )["CE"]


    result = minimize_scalar(
        objective,
        bounds=(-5.0, 5.0),
        method="bounded",
    )

    beta = result.x


    # --------------------------------------------
    # Test completo
    # --------------------------------------------

    test_rows = splits["test"]

    test_rows = test_rows[
        test_rows + horizon
        < len(df)
    ]

    X_test = load_feature_matrix(
        df,
        assets,
        feature,
        test_rows,
    )

    X_test = transform_feature(
        X_test,
        med,
        scale,
    )

    p_test = yp_matrix(
        df,
        assets,
        test_rows,
        cfg,
        horizon=0,
    )

    y_test = yp_matrix(
        df,
        assets,
        test_rows,
        cfg,
        horizon=horizon,
    )

    p_test = normalize_simplex(
        p_test,
        cfg.eps,
        smooth=True,
    )

    y_test = normalize_simplex(
        y_test,
        cfg.eps,
        smooth=False,
    )

    # Persistence
    baseline_metrics = simplex_metrics(
        y_test,
        p_test,
        cfg.eps,
    )

    # Feature
    q_test = tilted_simplex(
        p_test,
        X_test,
        beta,
        cfg.eps,
    )

    feature_metrics = simplex_metrics(
        y_test,
        q_test,
        cfg.eps,
    )

    return {

        "feature": feature,
        "family": NODE_FEATURES[feature],
        "horizon_bars": horizon,
        "horizon_minutes": horizon * 5,

        "beta": beta,

        "CE_baseline":
            baseline_metrics["CE"],

        "CE_feature":
            feature_metrics["CE"],

        "delta_CE":
            baseline_metrics["CE"]
            - feature_metrics["CE"],

        "KL":
            feature_metrics["KL"],

        "JS":
            feature_metrics["JS"],

        "MAE":
            feature_metrics["MAE"],

        "RMSE":
            feature_metrics["RMSE"],

        # Necesario para bootstrap
        "delta_CE_t":
            baseline_metrics["CE_t"]
            - feature_metrics["CE_t"],
    }

In [ ]:
PREDICTIVE_RESULTS_RAW = []

for feature in STRICT_FEATURES:

    print(
        "Predictive audit:",
        feature
    )

    result = screen_single_feature(
        df=df,
        assets=assets,
        feature=feature,
        cfg=cfg,
        splits=SPLITS,
        horizon=1,
    )

    PREDICTIVE_RESULTS_RAW.append(
        result
    )


PREDICTIVE_TABLE = pd.DataFrame([
    {
        k: v
        for k, v in r.items()
        if k != "delta_CE_t"
    }
    for r in PREDICTIVE_RESULTS_RAW
])


PREDICTIVE_TABLE = (
    PREDICTIVE_TABLE
    .sort_values(
        "delta_CE",
        ascending=False,
    )
    .reset_index(drop=True)
)


display(PREDICTIVE_TABLE)

In [ ]:
def moving_block_bootstrap(
    x,
    block_size=288,
    n_boot=1000,
    seed=42,
):

    rng = np.random.default_rng(
        seed
    )

    x = np.asarray(
        x,
        dtype=float,
    )

    x = x[
        np.isfinite(x)
    ]

    n = len(x)

    if n < block_size:
        raise ValueError(
            "Serie demasiado corta."
        )

    means = np.empty(
        n_boot
    )

    max_start = (
        n - block_size
    )

    n_blocks = int(
        np.ceil(
            n / block_size
        )
    )

    for b in range(n_boot):

        starts = rng.integers(
            0,
            max_start + 1,
            size=n_blocks,
        )

        sample = np.concatenate([
            x[
                s:s + block_size
            ]
            for s in starts
        ])[:n]

        means[b] = sample.mean()

    return {
        "mean": x.mean(),

        "CI_2.5":
            np.quantile(
                means,
                0.025,
            ),

        "CI_97.5":
            np.quantile(
                means,
                0.975,
            ),

        "P_mean_gt_0":
            np.mean(
                means > 0
            ),
    }

In [ ]:
BOOTSTRAP_ROWS = []

for result in PREDICTIVE_RESULTS_RAW:

    boot = moving_block_bootstrap(
        result["delta_CE_t"],
        block_size=288,
        n_boot=1000,
    )

    BOOTSTRAP_ROWS.append({
        "feature":
            result["feature"],

        **boot,
    })


BOOTSTRAP_TABLE = (
    pd.DataFrame(
        BOOTSTRAP_ROWS
    )
    .sort_values(
        "mean",
        ascending=False,
    )
)


display(BOOTSTRAP_TABLE)

In [ ]:
def signal_half_life_screen(
    df,
    assets,
    features,
    cfg,
    splits,
    horizons=(1, 2, 3, 6, 12),
):

    rows = []

    for feature in features:

        for h in horizons:

            print(
                feature,
                f"{h*5}m"
            )

            result = screen_single_feature(
                df=df,
                assets=assets,
                feature=feature,
                cfg=cfg,
                splits=splits,
                horizon=h,
            )

            rows.append({
                k: v
                for k, v in result.items()
                if k != "delta_CE_t"
            })

    return pd.DataFrame(rows)


# Recomiendo primero sólo las mejores variables:
TOP_FEATURES = (
    PREDICTIVE_TABLE
    .head(10)["feature"]
    .tolist()
)


HALF_LIFE_TABLE = signal_half_life_screen(
    df,
    assets,
    TOP_FEATURES,
    cfg,
    SPLITS,
)

In [ ]:
def build_family_panel(
    df,
    assets,
    rows,
    node_features,
    system_features=None,
    cfg=None,
    horizon=1,
):

    rows = np.asarray(rows)

    rows = rows[
        rows + horizon
        < len(df)
    ]

    N = len(assets)
    T = len(rows)

    X_parts = {}

    # --------------------------------------------
    # Features nodales
    # --------------------------------------------

    for feature in node_features:

        M = load_feature_matrix(
            df,
            assets,
            feature,
            rows,
        )

        X_parts[feature] = (
            M.reshape(-1)
        )

    # --------------------------------------------
    # yp actual / futuro
    # --------------------------------------------

    p = yp_matrix(
        df,
        assets,
        rows,
        cfg,
        horizon=0,
    )

    y = yp_matrix(
        df,
        assets,
        rows,
        cfg,
        horizon=horizon,
    )

    p = normalize_simplex(
        p,
        cfg.eps,
        smooth=True,
    )

    y = normalize_simplex(
        y,
        cfg.eps,
        smooth=True,
    )

    log_p = np.log(
        np.clip(
            p,
            cfg.eps,
            None,
        )
    )

    delta_target = (
        np.log(
            np.clip(
                y,
                cfg.eps,
                None,
            )
        )
        - log_p
    )

    # Baseline importante
    X_parts["log_yp_t"] = (
        log_p.reshape(-1)
    )

    # --------------------------------------------
    # Contexto sistémico
    # --------------------------------------------

    if system_features:

        for feature in system_features:

            values = (
                df[feature]
                .iloc[rows]
                .to_numpy(
                    dtype=np.float32,
                    copy=False,
                )
            )

            X_parts[
                f"SYS__{feature}"
            ] = np.repeat(
                values,
                N,
            )

    X = pd.DataFrame(
        X_parts
    )

    target = (
        delta_target
        .reshape(-1)
    )

    # Información necesaria para reconstruir
    metadata = {
        "rows": rows,
        "n_times": T,
        "n_assets": N,
        "p": p,
        "y": y,
    }

    valid = (
        np.isfinite(target)
    )

    # Para árboles, dejamos NaN en features:
    # XGB/LGBM los pueden manejar.
    return (
        X.loc[valid].reset_index(drop=True),
        target[valid],
        metadata,
        valid,
    )

In [ ]:
def evaluate_family_delta(
    delta_prediction,
    metadata,
    valid,
    eps=1e-12,
):

    T = metadata["n_times"]
    N = metadata["n_assets"]

    full_delta = np.zeros(
        T * N,
        dtype=np.float64,
    )

    full_delta[valid] = (
        delta_prediction
    )

    delta = full_delta.reshape(
        T,
        N,
    )

    p = metadata["p"]
    y = metadata["y"]

    logits = (
        np.log(
            np.clip(
                p,
                eps,
                None,
            )
        )
        + delta
    )

    q = softmax(
        logits,
        axis=1,
    )

    baseline = simplex_metrics(
        y,
        p,
        eps,
    )

    model = simplex_metrics(
        y,
        q,
        eps,
    )

    return {
        "CE_baseline":
            baseline["CE"],

        "CE_model":
            model["CE"],

        "delta_CE":
            baseline["CE"]
            - model["CE"],

        "KL":
            model["KL"],

        "JS":
            model["JS"],

        "MAE":
            model["MAE"],

        "RMSE":
            model["RMSE"],
    }

In [ ]:
def sampled_split_rows(
    idx,
    n_times,
):

    return sample_rows_evenly(
        idx,
        n_times,
    )


XGB_ROWS = {
    "train": sampled_split_rows(
        SPLITS["train"],
        2500,
    ),

    "val": sampled_split_rows(
        SPLITS["val"],
        750,
    ),

    "test": sampled_split_rows(
        SPLITS["test"],
        1000,
    ),
}

In [ ]:
from xgboost import XGBRegressor


def run_xgb_family(
    family,
    df,
    assets,
    cfg,
    use_system_context=True,
):

    features = MODEL_FAMILIES[
        family
    ]

    system = (
        SYSTEM_FEATURES
        if use_system_context
        else None
    )

    X_train, y_train, _, _ = (
        build_family_panel(
            df,
            assets,
            XGB_ROWS["train"],
            features,
            system,
            cfg,
        )
    )

    X_val, y_val, _, _ = (
        build_family_panel(
            df,
            assets,
            XGB_ROWS["val"],
            features,
            system,
            cfg,
        )
    )

    X_test, y_test, meta_test, valid_test = (
        build_family_panel(
            df,
            assets,
            XGB_ROWS["test"],
            features,
            system,
            cfg,
        )
    )

    model = XGBRegressor(
        objective="reg:squarederror",

        n_estimators=1200,
        learning_rate=0.03,

        max_depth=6,
        min_child_weight=20,

        subsample=0.80,
        colsample_bytree=0.80,

        reg_alpha=0.05,
        reg_lambda=1.0,

        tree_method="hist",

        n_jobs=-1,

        random_state=42,
    )

    model.fit(
        X_train,
        y_train,

        eval_set=[
            (X_val, y_val)
        ],

        verbose=False,
    )

    pred = model.predict(
        X_test
    )

    metrics = evaluate_family_delta(
        pred,
        meta_test,
        valid_test,
        cfg.eps,
    )

    metrics.update({
        "family": family,
        "model": "XGBoost",
        "n_features": len(features),
    })

    return (
        model,
        metrics,
    )

In [ ]:
XGB_MODELS = {}
XGB_RESULTS = []


for family in MODEL_FAMILIES:

    print(
        "XGBoost:",
        family
    )

    model, metrics = run_xgb_family(
        family,
        df,
        assets,
        cfg,
        use_system_context=True,
    )

    XGB_MODELS[family] = model

    XGB_RESULTS.append(
        metrics
    )


XGB_RESULTS = pd.DataFrame(
    XGB_RESULTS
).sort_values(
    "delta_CE",
    ascending=False,
)


display(XGB_RESULTS)

In [ ]:
try:
    from lightgbm import (
        LGBMRegressor,
        early_stopping,
        log_evaluation,
    )

    LIGHTGBM_AVAILABLE = True

except ImportError:

    LIGHTGBM_AVAILABLE = False

    print(
        "LightGBM no está instalado."
    )

In [ ]:
def run_lgb_family(
    family,
    df,
    assets,
    cfg,
    use_system_context=True,
):

    if not LIGHTGBM_AVAILABLE:
        raise ImportError(
            "Instala lightgbm antes de ejecutar."
        )

    features = MODEL_FAMILIES[
        family
    ]

    system = (
        SYSTEM_FEATURES
        if use_system_context
        else None
    )

    X_train, y_train, _, _ = (
        build_family_panel(
            df,
            assets,
            XGB_ROWS["train"],
            features,
            system,
            cfg,
        )
    )

    X_val, y_val, _, _ = (
        build_family_panel(
            df,
            assets,
            XGB_ROWS["val"],
            features,
            system,
            cfg,
        )
    )

    X_test, y_test, meta_test, valid_test = (
        build_family_panel(
            df,
            assets,
            XGB_ROWS["test"],
            features,
            system,
            cfg,
        )
    )

    model = LGBMRegressor(

        objective="regression",

        n_estimators=2000,
        learning_rate=0.025,

        num_leaves=63,
        max_depth=-1,

        min_child_samples=100,

        subsample=0.80,
        colsample_bytree=0.80,

        reg_alpha=0.05,
        reg_lambda=1.0,

        n_jobs=-1,

        random_state=42,
        verbosity=-1,
    )

    model.fit(

        X_train,
        y_train,

        eval_set=[
            (X_val, y_val)
        ],

        callbacks=[
            early_stopping(
                75,
                verbose=False,
            ),
            log_evaluation(0),
        ],
    )

    pred = model.predict(
        X_test
    )

    metrics = evaluate_family_delta(
        pred,
        meta_test,
        valid_test,
        cfg.eps,
    )

    metrics.update({
        "family": family,
        "model": "LightGBM",
        "n_features": len(features),
    })

    return (
        model,
        metrics,
    )

In [ ]:
LGB_MODELS = {}
LGB_RESULTS = []


if LIGHTGBM_AVAILABLE:

    for family in MODEL_FAMILIES:

        print(
            "LightGBM:",
            family
        )

        model, metrics = run_lgb_family(
            family,
            df,
            assets,
            cfg,
            use_system_context=True,
        )

        LGB_MODELS[family] = model

        LGB_RESULTS.append(
            metrics
        )


    LGB_RESULTS = pd.DataFrame(
        LGB_RESULTS
    ).sort_values(
        "delta_CE",
        ascending=False,
    )


    display(LGB_RESULTS)

In [ ]:
FAMILY_COMPARISON = []


for family in MODEL_FAMILIES:

    if family in XGB_MODELS:

        row = (
            XGB_RESULTS[
                XGB_RESULTS["family"]
                == family
            ]
            .iloc[0]
            .to_dict()
        )

        FAMILY_COMPARISON.append(
            row
        )


    if (
        LIGHTGBM_AVAILABLE
        and family in LGB_MODELS
    ):

        row = (
            LGB_RESULTS[
                LGB_RESULTS["family"]
                == family
            ]
            .iloc[0]
            .to_dict()
        )

        FAMILY_COMPARISON.append(
            row
        )


FAMILY_COMPARISON = (
    pd.DataFrame(
        FAMILY_COMPARISON
    )
    .sort_values(
        "delta_CE",
        ascending=False,
    )
)


display(
    FAMILY_COMPARISON
)

In [ ]:
def raw_base_dataframe(
    df,
    assets,
    cfg,
):

    cols = [
        cfg.time_col,
        cfg.ys_col,
    ]

    for a in assets:

        cols.extend([
            base_col(a, "P", cfg),
            base_col(a, "V", cfg),
            base_col(a, "C", cfg),
            base_col(a, "R", cfg),
            base_col(a, "L", cfg),
            base_col(a, "A", cfg),
            base_col(a, "O", cfg),
            base_col(a, "B", cfg),
            base_col(a, "S", cfg),
            base_col(a, "yp", cfg),
        ])

    return df.loc[:, cols].copy()


DF_RAW = raw_base_dataframe(
    df,
    assets,
    cfg,
)

In [ ]:
def prefix_invariance_test(
    raw_df,
    rebuild_fn,
    feature_cols,
    cuts,
    atol=1e-7,
    rtol=1e-6,
):

    # Pipeline completo
    full = rebuild_fn(
        raw_df.copy()
    )

    results = []

    for cut in cuts:

        prefix_raw = (
            raw_df
            .iloc[:cut + 1]
            .copy()
        )

        prefix = rebuild_fn(
            prefix_raw
        )

        for feature in feature_cols:

            a = full[
                feature
            ].iloc[cut]

            b = prefix[
                feature
            ].iloc[-1]

            if (
                pd.isna(a)
                and pd.isna(b)
            ):
                equal = True
            else:
                equal = np.isclose(
                    a,
                    b,
                    atol=atol,
                    rtol=rtol,
                    equal_nan=True,
                )

            results.append({
                "cut": cut,
                "feature": feature,
                "full": a,
                "prefix": b,
                "causal_equal": equal,
            })

    return pd.DataFrame(
        results
    )